local data = {}

-- AUTO-GENERATED by tools/adamrogue/generate_stage_d_data.py.
data.CONTENT_FACTION_KEY = "wh2_main_skv_clan_mors"

data.CHARACTER_SKILL_PLANS_BY_SUBTYPE = {
    wh2_dlc12_skv_warlock_master = {
        {
            node_key = "wh2_dlc12_skill_node_skv_master_engineer_mount_1",
            skill_key = "wh2_dlc12_skill_skv_warlock_master_mount_doom_flayer",
            category_key = "character",
            indent = 0,
            tier = 0,
            max_level = 1,
            is_mount_skill = true,
            unlock_ranks_by_level = { 6 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_dlc12_skill_node_skv_master_engineer_mount_2",
            skill_key = "wh2_dlc12_skill_skv_warlock_master_mount_doomwheel",
            category_key = "character",
            indent = 0,
            tier = 1,
            max_level = 1,
            is_mount_skill = true,
            unlock_ranks_by_level = { 14 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_dlc12_skill_node_skv_master_engineer_generic_1",
            skill_key = "wh2_main_skill_skv_generic_missile_ward",
            category_key = "character",
            indent = 0,
            tier = 2,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 7 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_dlc12_skill_node_skv_master_engineer_generic_2",
            skill_key = "wh2_main_skill_skv_generic_magic_ward",
            category_key = "character",
            indent = 0,
            tier = 3,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 7 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_dlc12_skill_node_skv_master_engineer_unique_00",
            skill_key = "wh2_dlc12_skill_skv_engineer_unique_0",
            category_key = "character",
            indent = 1,
            tier = 0,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 9 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_dlc12_skill_node_skv_master_engineer_unique_01",
            skill_key = "wh2_dlc12_skill_skv_engineer_unique_1",
            category_key = "character",
            indent = 1,
            tier = 1,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 9 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_dlc12_skill_node_skv_master_engineer_unique_02",
            skill_key = "wh2_dlc12_skill_skv_engineer_unique_2",
            category_key = "character",
            indent = 1,
            tier = 2,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 12 },
            locked_node_keys = {
                "wh2_dlc12_skill_node_skv_master_engineer_unique_03",
                "wh2_dlc12_skill_node_skv_master_engineer_unique_04",
            }
        },
        {
            node_key = "wh2_dlc12_skill_node_skv_master_engineer_unique_03",
            skill_key = "wh2_dlc12_skill_skv_engineer_unique_3",
            category_key = "character",
            indent = 1,
            tier = 3,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 12 },
            locked_node_keys = {
                "wh2_dlc12_skill_node_skv_master_engineer_unique_02",
                "wh2_dlc12_skill_node_skv_master_engineer_unique_04",
            }
        },
        {
            node_key = "wh2_dlc12_skill_node_skv_master_engineer_unique_04",
            skill_key = "wh2_dlc12_skill_skv_engineer_unique_4",
            category_key = "character",
            indent = 1,
            tier = 4,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 12 },
            locked_node_keys = {
                "wh2_dlc12_skill_node_skv_master_engineer_unique_02",
                "wh2_dlc12_skill_node_skv_master_engineer_unique_03",
            }
        },
        {
            node_key = "wh2_dlc12_skill_node_skv_master_engineer_unique_05",
            skill_key = "wh2_dlc12_skill_warlock_master_brass_orb",
            category_key = "character",
            indent = 1,
            tier = 5,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_dlc12_skill_node_skv_master_engineer_personal_00",
            skill_key = "wh2_main_skill_skv_combat_tail_weapon",
            category_key = "character",
            indent = 2,
            tier = 0,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_dlc12_skill_node_skv_master_engineer_personal_01",
            skill_key = "wh2_main_skill_skv_engineer_warlock_augmented_weapon",
            category_key = "character",
            indent = 2,
            tier = 1,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_dlc12_skill_node_skv_master_engineer_personal_02",
            skill_key = "wh2_dlc11_skill_all_lord_self_scarred_veteran",
            category_key = "character",
            indent = 2,
            tier = 2,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_dlc12_skill_node_skv_master_engineer_personal_03",
            skill_key = "wh2_main_skill_skv_engineer_warpforged_armour",
            category_key = "character",
            indent = 2,
            tier = 3,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_dlc12_skill_node_skv_master_engineer_personal_04",
            skill_key = "wh2_dlc12_skill_skv_engineer_personal_0",
            category_key = "character",
            indent = 2,
            tier = 4,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_dlc12_skill_node_skv_master_engineer_magic_00",
            skill_key = "wh2_main_skill_all_magic_ruin_01_warp_lightning",
            category_key = "character",
            indent = 3,
            tier = 0,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_dlc12_skill_node_skv_master_engineer_magic_04",
            skill_key = "wh2_main_skill_all_magic_ruin_03_lore_attribute",
            category_key = "character",
            indent = 3,
            tier = 1,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_dlc12_skill_node_skv_master_engineer_magic_01",
            skill_key = "wh2_main_skill_all_magic_ruin_02_howling_warpgale_lord",
            category_key = "character",
            indent = 3,
            tier = 2,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_dlc12_skill_node_skv_master_engineer_magic_02",
            skill_key = "wh2_main_skill_all_magic_ruin_04_death_frenzy_lord",
            category_key = "character",
            indent = 3,
            tier = 3,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_dlc12_skill_node_skv_master_engineer_magic_03",
            skill_key = "wh2_main_skill_all_magic_ruin_05_skaven_scorch_lord",
            category_key = "character",
            indent = 3,
            tier = 4,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_dlc12_skill_node_skv_master_engineer_magic_05",
            skill_key = "wh_main_skill_all_magic_all_06_evasion",
            category_key = "character",
            indent = 3,
            tier = 5,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_dlc12_skill_node_skv_master_engineer_magic_06",
            skill_key = "wh2_main_skill_all_magic_ruin_09_cracks_call_lord",
            category_key = "character",
            indent = 3,
            tier = 6,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_dlc12_skill_node_skv_master_engineer_magic_07",
            skill_key = "wh2_main_skill_all_magic_ruin_10_flensing_ruin_lord",
            category_key = "character",
            indent = 3,
            tier = 7,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_dlc12_skill_node_skv_master_engineer_magic_08",
            skill_key = "wh_main_skill_all_magic_all_07_earthing",
            category_key = "character",
            indent = 3,
            tier = 8,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_dlc12_skill_node_skv_master_engineer_magic_09",
            skill_key = "wh_main_skill_all_magic_all_08_power_drain",
            category_key = "character",
            indent = 3,
            tier = 9,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_dlc12_skill_node_skv_master_engineer_magic_10",
            skill_key = "wh_main_skill_all_magic_all_11_arcane_conduit",
            category_key = "character",
            indent = 3,
            tier = 10,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_dlc12_skill_node_skv_master_engineer_magic_dummy",
            skill_key = "wh2_main_skill_all_magic_ruin_dummy_warp_lightning_howling_warpgale",
            category_key = "character",
            indent = 3,
            tier = 11,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_dlc12_skill_node_skv_master_engineer_army_chain_00",
            skill_key = "wh_main_skill_all_lord_battle_inspiring_presence",
            category_key = "battle",
            indent = 4,
            tier = 0,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_dlc12_skill_node_skv_master_engineer_army_chain_01",
            skill_key = "wh2_main_skill_skv_army_buff_clanrats",
            category_key = "battle",
            indent = 4,
            tier = 1,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_dlc12_skill_node_skv_master_engineer_army_chain_02",
            skill_key = "wh2_main_skill_skv_army_buff_runners",
            category_key = "battle",
            indent = 4,
            tier = 2,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_dlc12_skill_node_skv_master_engineer_army_chain_03",
            skill_key = "wh2_main_skill_skv_army_buff_weaponteams",
            category_key = "battle",
            indent = 4,
            tier = 3,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_dlc12_skill_node_skv_master_engineer_army_chain_04",
            skill_key = "wh2_main_skill_skv_army_buff_eliteinf",
            category_key = "battle",
            indent = 4,
            tier = 4,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_dlc12_skill_node_skv_master_engineer_army_chain_05",
            skill_key = "wh2_main_skill_skv_army_buff_monsters",
            category_key = "battle",
            indent = 4,
            tier = 5,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_dlc12_skill_node_skv_master_engineer_army_chain_06",
            skill_key = "wh2_main_skill_skv_army_buff_artillery",
            category_key = "battle",
            indent = 4,
            tier = 6,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_dlc12_skill_node_skv_master_engineer_army_chain_07",
            skill_key = "wh_main_skill_all_lord_battle_rally",
            category_key = "battle",
            indent = 4,
            tier = 7,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_dlc12_skill_node_skv_master_engineer_army_chain_08",
            skill_key = "wh2_main_skill_skv_army_buff_straight_to_the_point",
            category_key = "battle",
            indent = 4,
            tier = 8,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_dlc12_skill_node_skv_master_engineer_army_chain_09",
            skill_key = "wh2_main_skill_skv_army_buff_gutter_wise",
            category_key = "battle",
            indent = 4,
            tier = 9,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_dlc12_skill_node_skv_master_engineer_army_chain_10",
            skill_key = "wh2_main_skill_skv_army_buff_warped_workshops",
            category_key = "battle",
            indent = 4,
            tier = 10,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_dlc12_skill_node_skv_master_engineer_army_chain_11",
            skill_key = "wh2_main_skill_skv_army_buff_mutagenic_elixirs",
            category_key = "battle",
            indent = 4,
            tier = 11,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_dlc12_skill_node_skv_master_engineer_army_chain_12",
            skill_key = "wh_main_skill_chs_lord_battle_stand_or_die",
            category_key = "battle",
            indent = 4,
            tier = 12,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
    },
    wh2_dlc14_skv_master_assassin = {
        {
            node_key = "wh2_dlc14_skill_node_skv_master_assassin_uinique_1",
            skill_key = "wh2_dlc14_skill_skv_tougher_than_he_seems",
            category_key = "character",
            indent = 0,
            tier = 1,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 7 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_dlc14_skill_node_skv_master_assassin_uinique_2",
            skill_key = "wh2_dlc14_skill_skv_snikch_hero_self_defence",
            category_key = "character",
            indent = 0,
            tier = 2,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 7 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_dlc14_skill_node_skv_master_assassin_uinique_3",
            skill_key = "wh2_main_skill_skv_generic_missile_ward",
            category_key = "character",
            indent = 0,
            tier = 3,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 7 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_dlc14_skill_node_skv_master_assassin_uinique_4",
            skill_key = "wh2_main_skill_skv_generic_magic_ward",
            category_key = "character",
            indent = 0,
            tier = 4,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 7 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_dlc14_skill_node_skv_master_assassin_uinique_5",
            skill_key = "wh2_dlc14_skill_skv_master_assassin_expert_ambusher",
            category_key = "character",
            indent = 1,
            tier = 0,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 5 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_dlc14_skill_node_skv_master_assassin_uinique_6",
            skill_key = "wh2_dlc14_skill_skv_stab_in_the_back",
            category_key = "character",
            indent = 1,
            tier = 1,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_dlc14_skill_node_skv_master_assassin_uinique_7",
            skill_key = "wh2_dlc14_skill_skv_master_assassin_concealment_bombs",
            category_key = "character",
            indent = 1,
            tier = 2,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_dlc14_skill_node_skv_master_assassin_uinique_9",
            skill_key = "wh2_dlc14_skill_skv_assassins_missile_damage",
            category_key = "character",
            indent = 1,
            tier = 4,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_dlc14_skill_node_skv_master_assassin_uinique_10",
            skill_key = "wh2_dlc14_skill_skv_master_assassin_cracklebombs",
            category_key = "character",
            indent = 1,
            tier = 5,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_dlc14_skill_node_skv_master_assassin_combat_0",
            skill_key = "wh2_main_skill_skv_combat_tail_weapon",
            category_key = "character",
            indent = 2,
            tier = 0,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_dlc14_skill_node_skv_master_assassin_combat_1_1",
            skill_key = "wh2_main_skill_skv_combat_ruin_and_decay",
            category_key = "character",
            indent = 2,
            tier = 1,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_dlc14_skill_node_skv_master_assassin_combat_1_2",
            skill_key = "wh2_dlc11_skill_all_lord_self_deadeye",
            category_key = "character",
            indent = 2,
            tier = 2,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_dlc14_skill_node_skv_master_assassin_combat_1_3",
            skill_key = "wh2_dlc11_skill_all_lord_self_blade_master",
            category_key = "character",
            indent = 2,
            tier = 3,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_dlc14_skill_node_skv_master_assassin_combat_1_4",
            skill_key = "wh2_dlc11_skill_all_lord_self_self_indomitable",
            category_key = "character",
            indent = 2,
            tier = 4,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_dlc14_skill_node_skv_master_assassin_combat_2",
            skill_key = "wh_main_skill_all_spy_self_slippery",
            category_key = "character",
            indent = 2,
            tier = 5,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_dlc14_skill_node_skv_master_assassin_combat_3_1",
            skill_key = "wh2_dlc11_skill_all_lord_self_wound-maker",
            category_key = "character",
            indent = 2,
            tier = 6,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_dlc14_skill_node_skv_master_assassin_combat_3_2",
            skill_key = "wh2_dlc11_skill_all_lord_self_scarred_veteran",
            category_key = "character",
            indent = 2,
            tier = 7,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_dlc14_skill_node_skv_master_assassin_combat_3_3",
            skill_key = "wh2_dlc11_skill_wef_lord_self_piercing_shots",
            category_key = "character",
            indent = 2,
            tier = 8,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_dlc14_skill_node_skv_master_assassin_combat_3_4",
            skill_key = "wh2_dlc11_skill_wef_lord_self_expeditious_endeavour",
            category_key = "character",
            indent = 2,
            tier = 9,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_dlc14_skill_node_skv_master_assassin_combat_4",
            skill_key = "wh_main_skill_all_all_self_deadly_onslaught",
            category_key = "character",
            indent = 2,
            tier = 10,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
                "wh_dlc05_skill_node_wef_glade_lord_fem_self_ranged_06",
                "wh_dlc05_skill_node_wef_glade_lord_self_ranged_06",
            }
        },
        {
            node_key = "wh2_dlc14_skill_node_skv_master_assassin_army_0",
            skill_key = "wh_main_skill_all_lord_battle_inspiring_presence",
            category_key = "battle",
            indent = 4,
            tier = 0,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_dlc14_skill_node_skv_master_assassin_army_1_1",
            skill_key = "wh2_main_skill_skv_army_buff_clanrats",
            category_key = "battle",
            indent = 4,
            tier = 1,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_dlc14_skill_node_skv_master_assassin_army_1_2",
            skill_key = "wh2_main_skill_skv_army_buff_runners",
            category_key = "battle",
            indent = 4,
            tier = 2,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_dlc14_skill_node_skv_master_assassin_army_1_3",
            skill_key = "wh2_main_skill_skv_army_buff_weaponteams",
            category_key = "battle",
            indent = 4,
            tier = 3,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_dlc14_skill_node_skv_master_assassin_army_1_4",
            skill_key = "wh2_main_skill_skv_army_buff_eliteinf",
            category_key = "battle",
            indent = 4,
            tier = 4,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_dlc14_skill_node_skv_master_assassin_army_1_5",
            skill_key = "wh2_main_skill_skv_army_buff_monsters",
            category_key = "battle",
            indent = 4,
            tier = 5,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_dlc14_skill_node_skv_master_assassin_army_1_6",
            skill_key = "wh2_main_skill_skv_army_buff_artillery",
            category_key = "battle",
            indent = 4,
            tier = 6,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_dlc14_skill_node_skv_master_assassin_army_2",
            skill_key = "wh_main_skill_all_lord_battle_rally",
            category_key = "battle",
            indent = 4,
            tier = 7,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_dlc14_skill_node_skv_master_assassin_army_3_1",
            skill_key = "wh2_main_skill_skv_army_buff_straight_to_the_point",
            category_key = "battle",
            indent = 4,
            tier = 8,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_dlc14_skill_node_skv_master_assassin_army_3_2",
            skill_key = "wh2_main_skill_skv_army_buff_gutter_wise",
            category_key = "battle",
            indent = 4,
            tier = 9,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_dlc14_skill_node_skv_master_assassin_army_3_3",
            skill_key = "wh2_main_skill_skv_army_buff_warped_workshops",
            category_key = "battle",
            indent = 4,
            tier = 10,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_dlc14_skill_node_skv_master_assassin_army_3_4",
            skill_key = "wh2_main_skill_skv_army_buff_mutagenic_elixirs",
            category_key = "battle",
            indent = 4,
            tier = 11,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_dlc14_skill_node_skv_master_assassin_army_4",
            skill_key = "wh_main_skill_chs_lord_battle_stand_or_die",
            category_key = "battle",
            indent = 4,
            tier = 12,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
    },
    wh2_main_skv_grey_seer_plague = {
        {
            node_key = "wh2_main_skill_node_skv_grey_seer_plague_mount_1",
            skill_key = "wh2_main_skill_skv_grey_seer_plague_mount_screaming_bell",
            category_key = "character",
            indent = 0,
            tier = 0,
            max_level = 1,
            is_mount_skill = true,
            unlock_ranks_by_level = { 15 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_main_skill_node_skv_grey_seer_plague_generic_0",
            skill_key = "wh2_main_skill_skv_unique_warptokens",
            category_key = "character",
            indent = 0,
            tier = 1,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 3 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_main_skill_node_skv_grey_seer_plague_generic_2",
            skill_key = "wh2_main_skill_skv_generic_missile_ward",
            category_key = "character",
            indent = 0,
            tier = 2,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 7 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_main_skill_node_skv_grey_seer_plague_generic_3",
            skill_key = "wh2_main_skill_skv_generic_magic_ward",
            category_key = "character",
            indent = 0,
            tier = 3,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 7 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_main_skill_node_skv_grey_seer_plague_unique_1",
            skill_key = "wh2_main_skill_skv_unique_voice_of_the_horned_rat",
            category_key = "character",
            indent = 1,
            tier = 0,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 12 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_main_skill_node_skv_grey_seer_plague_unique_2",
            skill_key = "wh2_main_skill_skv_unique_envoy_of_the_council",
            category_key = "character",
            indent = 1,
            tier = 1,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 12 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_main_skill_node_skv_grey_seer_plague_combat_0",
            skill_key = "wh2_main_skill_skv_combat_tail_weapon",
            category_key = "character",
            indent = 2,
            tier = 0,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_main_skill_node_skv_grey_seer_plague_combat_1_1",
            skill_key = "wh2_dlc11_skill_all_lord_self_wound-maker",
            category_key = "character",
            indent = 2,
            tier = 1,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_main_skill_node_skv_grey_seer_plague_combat_1_2",
            skill_key = "wh2_dlc11_skill_all_lord_self_scarred_veteran",
            category_key = "character",
            indent = 2,
            tier = 2,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_main_skill_node_skv_grey_seer_plague_combat_1_3",
            skill_key = "wh2_dlc11_skill_wef_lord_self_expeditious_endeavour",
            category_key = "character",
            indent = 2,
            tier = 3,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_main_skill_node_skv_grey_seer_plague_magic_0",
            skill_key = "wh2_main_skill_all_magic_plague_01_pestilent_breath",
            category_key = "character",
            indent = 3,
            tier = 0,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_main_skill_node_skv_grey_seer_plague_magic_1_4",
            skill_key = "wh2_main_skill_all_magic_plague_03_lore_attribute",
            category_key = "character",
            indent = 3,
            tier = 1,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_main_skill_node_skv_grey_seer_plague_magic_1_1",
            skill_key = "wh2_main_skill_all_magic_plague_02_bless_with_filth_lord",
            category_key = "character",
            indent = 3,
            tier = 2,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_main_skill_node_skv_grey_seer_plague_magic_1_2",
            skill_key = "wh2_main_skill_all_magic_plague_04_wither_lord",
            category_key = "character",
            indent = 3,
            tier = 3,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_main_skill_node_skv_grey_seer_plague_magic_1_3",
            skill_key = "wh2_main_skill_all_magic_plague_05_vermintide_lord",
            category_key = "character",
            indent = 3,
            tier = 4,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_main_skill_node_skv_grey_seer_plague_magic_2",
            skill_key = "wh_main_skill_all_magic_all_06_evasion",
            category_key = "character",
            indent = 3,
            tier = 5,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_main_skill_node_skv_grey_seer_plague_magic_3_1",
            skill_key = "wh2_main_skill_all_magic_plague_09_plague_lord",
            category_key = "character",
            indent = 3,
            tier = 6,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_main_skill_node_skv_grey_seer_plague_magic_3_2",
            skill_key = "wh2_main_skill_all_magic_plague_10_dreaded_thirteenth",
            category_key = "character",
            indent = 3,
            tier = 7,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_main_skill_node_skv_grey_seer_plague_magic_3_3",
            skill_key = "wh_main_skill_all_magic_all_07_earthing",
            category_key = "character",
            indent = 3,
            tier = 8,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_main_skill_node_skv_grey_seer_plague_magic_3_4",
            skill_key = "wh_main_skill_all_magic_all_08_power_drain",
            category_key = "character",
            indent = 3,
            tier = 9,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_main_skill_node_skv_grey_seer_plague_magic_4",
            skill_key = "wh_main_skill_all_magic_all_11_arcane_conduit",
            category_key = "character",
            indent = 3,
            tier = 10,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_main_skill_node_skv_grey_seer_plague_magic_dummy",
            skill_key = "wh2_main_skill_all_magic_plague_dummy_pestilent_breath_bless_with_filth",
            category_key = "character",
            indent = 3,
            tier = 11,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_main_skill_node_skv_grey_seer_plague_army_0",
            skill_key = "wh_main_skill_all_lord_battle_inspiring_presence",
            category_key = "battle",
            indent = 4,
            tier = 0,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_main_skill_node_skv_grey_seer_plague_army_1_1",
            skill_key = "wh2_main_skill_skv_army_buff_clanrats",
            category_key = "battle",
            indent = 4,
            tier = 1,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_main_skill_node_skv_grey_seer_plague_army_1_2",
            skill_key = "wh2_main_skill_skv_army_buff_runners",
            category_key = "battle",
            indent = 4,
            tier = 2,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_main_skill_node_skv_grey_seer_plague_army_1_3",
            skill_key = "wh2_main_skill_skv_army_buff_weaponteams",
            category_key = "battle",
            indent = 4,
            tier = 3,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_main_skill_node_skv_grey_seer_plague_army_1_4",
            skill_key = "wh2_main_skill_skv_army_buff_eliteinf",
            category_key = "battle",
            indent = 4,
            tier = 4,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_main_skill_node_skv_grey_seer_plague_army_1_5",
            skill_key = "wh2_main_skill_skv_army_buff_monsters",
            category_key = "battle",
            indent = 4,
            tier = 5,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_main_skill_node_skv_grey_seer_plague_army_1_6",
            skill_key = "wh2_main_skill_skv_army_buff_artillery",
            category_key = "battle",
            indent = 4,
            tier = 6,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_main_skill_node_skv_grey_seer_plague_army_2",
            skill_key = "wh_main_skill_all_lord_battle_rally",
            category_key = "battle",
            indent = 4,
            tier = 7,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_main_skill_node_skv_grey_seer_plague_army_3_1",
            skill_key = "wh2_main_skill_skv_army_buff_straight_to_the_point",
            category_key = "battle",
            indent = 4,
            tier = 8,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_main_skill_node_skv_grey_seer_plague_army_3_2",
            skill_key = "wh2_main_skill_skv_army_buff_gutter_wise",
            category_key = "battle",
            indent = 4,
            tier = 9,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_main_skill_node_skv_grey_seer_plague_army_3_3",
            skill_key = "wh2_main_skill_skv_army_buff_warped_workshops",
            category_key = "battle",
            indent = 4,
            tier = 10,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_main_skill_node_skv_grey_seer_plague_army_3_4",
            skill_key = "wh2_main_skill_skv_army_buff_mutagenic_elixirs",
            category_key = "battle",
            indent = 4,
            tier = 11,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_main_skill_node_skv_grey_seer_plague_army_4",
            skill_key = "wh_main_skill_chs_lord_battle_stand_or_die",
            category_key = "battle",
            indent = 4,
            tier = 12,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
    },
    wh2_main_skv_grey_seer_ruin = {
        {
            node_key = "wh2_main_skill_node_skv_grey_seer_ruin_mount_1",
            skill_key = "wh2_main_skill_skv_grey_seer_ruin_mount_screaming_bell",
            category_key = "character",
            indent = 0,
            tier = 0,
            max_level = 1,
            is_mount_skill = true,
            unlock_ranks_by_level = { 15 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_main_skill_node_skv_grey_seer_ruin_generic_0",
            skill_key = "wh2_main_skill_skv_unique_warptokens",
            category_key = "character",
            indent = 0,
            tier = 1,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 3 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_main_skill_node_skv_grey_seer_ruin_generic_2",
            skill_key = "wh2_main_skill_skv_generic_missile_ward",
            category_key = "character",
            indent = 0,
            tier = 2,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 7 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_main_skill_node_skv_grey_seer_ruin_generic_3",
            skill_key = "wh2_main_skill_skv_generic_magic_ward",
            category_key = "character",
            indent = 0,
            tier = 3,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 7 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_main_skill_node_skv_grey_seer_ruin_unique_1",
            skill_key = "wh2_main_skill_skv_unique_voice_of_the_horned_rat",
            category_key = "character",
            indent = 1,
            tier = 0,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 12 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_main_skill_node_skv_grey_seer_ruin_unique_2",
            skill_key = "wh2_main_skill_skv_unique_envoy_of_the_council",
            category_key = "character",
            indent = 1,
            tier = 1,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 12 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_main_skill_node_skv_grey_seer_ruin_combat_0",
            skill_key = "wh2_main_skill_skv_combat_tail_weapon",
            category_key = "character",
            indent = 2,
            tier = 0,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_main_skill_node_skv_grey_seer_ruin_combat_1_1",
            skill_key = "wh2_dlc11_skill_all_lord_self_wound-maker",
            category_key = "character",
            indent = 2,
            tier = 1,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_main_skill_node_skv_grey_seer_ruin_combat_1_2",
            skill_key = "wh2_dlc11_skill_all_lord_self_scarred_veteran",
            category_key = "character",
            indent = 2,
            tier = 2,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_main_skill_node_skv_grey_seer_ruin_combat_1_3",
            skill_key = "wh2_dlc11_skill_wef_lord_self_expeditious_endeavour",
            category_key = "character",
            indent = 2,
            tier = 3,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_main_skill_node_skv_grey_seer_ruin_magic_0",
            skill_key = "wh2_main_skill_all_magic_ruin_01_warp_lightning",
            category_key = "character",
            indent = 3,
            tier = 0,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_main_skill_node_skv_grey_seer_ruin_magic_1_4",
            skill_key = "wh2_main_skill_all_magic_ruin_03_lore_attribute",
            category_key = "character",
            indent = 3,
            tier = 1,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_main_skill_node_skv_grey_seer_ruin_magic_1_1",
            skill_key = "wh2_main_skill_all_magic_ruin_02_howling_warpgale_lord",
            category_key = "character",
            indent = 3,
            tier = 2,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_main_skill_node_skv_grey_seer_ruin_magic_1_2",
            skill_key = "wh2_main_skill_all_magic_ruin_04_death_frenzy_lord",
            category_key = "character",
            indent = 3,
            tier = 3,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_main_skill_node_skv_grey_seer_ruin_magic_1_3",
            skill_key = "wh2_main_skill_all_magic_ruin_05_skaven_scorch_lord",
            category_key = "character",
            indent = 3,
            tier = 4,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_main_skill_node_skv_grey_seer_ruin_magic_2",
            skill_key = "wh_main_skill_all_magic_all_06_evasion",
            category_key = "character",
            indent = 3,
            tier = 5,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_main_skill_node_skv_grey_seer_ruin_magic_3_1",
            skill_key = "wh2_main_skill_all_magic_ruin_09_cracks_call_lord",
            category_key = "character",
            indent = 3,
            tier = 6,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_main_skill_node_skv_grey_seer_ruin_magic_3_2",
            skill_key = "wh2_main_skill_all_magic_plague_10_dreaded_thirteenth",
            category_key = "character",
            indent = 3,
            tier = 7,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_main_skill_node_skv_grey_seer_ruin_magic_3_3",
            skill_key = "wh_main_skill_all_magic_all_07_earthing",
            category_key = "character",
            indent = 3,
            tier = 8,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_main_skill_node_skv_grey_seer_ruin_magic_3_4",
            skill_key = "wh_main_skill_all_magic_all_08_power_drain",
            category_key = "character",
            indent = 3,
            tier = 9,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_main_skill_node_skv_grey_seer_ruin_magic_4",
            skill_key = "wh_main_skill_all_magic_all_11_arcane_conduit",
            category_key = "character",
            indent = 3,
            tier = 10,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_main_skill_node_skv_grey_seer_ruin_magic_dummy",
            skill_key = "wh2_main_skill_all_magic_ruin_dummy_warp_lightning_howling_warpgale",
            category_key = "character",
            indent = 3,
            tier = 11,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_main_skill_node_skv_grey_seer_ruin_army_0",
            skill_key = "wh_main_skill_all_lord_battle_inspiring_presence",
            category_key = "battle",
            indent = 4,
            tier = 0,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_main_skill_node_skv_grey_seer_ruin_army_1_1",
            skill_key = "wh2_main_skill_skv_army_buff_clanrats",
            category_key = "battle",
            indent = 4,
            tier = 1,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_main_skill_node_skv_grey_seer_ruin_army_1_2",
            skill_key = "wh2_main_skill_skv_army_buff_runners",
            category_key = "battle",
            indent = 4,
            tier = 2,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_main_skill_node_skv_grey_seer_ruin_army_1_3",
            skill_key = "wh2_main_skill_skv_army_buff_weaponteams",
            category_key = "battle",
            indent = 4,
            tier = 3,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_main_skill_node_skv_grey_seer_ruin_army_1_4",
            skill_key = "wh2_main_skill_skv_army_buff_eliteinf",
            category_key = "battle",
            indent = 4,
            tier = 4,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_main_skill_node_skv_grey_seer_ruin_army_1_5",
            skill_key = "wh2_main_skill_skv_army_buff_monsters",
            category_key = "battle",
            indent = 4,
            tier = 5,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_main_skill_node_skv_grey_seer_ruin_army_1_6",
            skill_key = "wh2_main_skill_skv_army_buff_artillery",
            category_key = "battle",
            indent = 4,
            tier = 6,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_main_skill_node_skv_grey_seer_ruin_army_2",
            skill_key = "wh_main_skill_all_lord_battle_rally",
            category_key = "battle",
            indent = 4,
            tier = 7,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_main_skill_node_skv_grey_seer_ruin_army_3_1",
            skill_key = "wh2_main_skill_skv_army_buff_straight_to_the_point",
            category_key = "battle",
            indent = 4,
            tier = 8,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_main_skill_node_skv_grey_seer_ruin_army_3_2",
            skill_key = "wh2_main_skill_skv_army_buff_gutter_wise",
            category_key = "battle",
            indent = 4,
            tier = 9,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_main_skill_node_skv_grey_seer_ruin_army_3_3",
            skill_key = "wh2_main_skill_skv_army_buff_warped_workshops",
            category_key = "battle",
            indent = 4,
            tier = 10,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_main_skill_node_skv_grey_seer_ruin_army_3_4",
            skill_key = "wh2_main_skill_skv_army_buff_mutagenic_elixirs",
            category_key = "battle",
            indent = 4,
            tier = 11,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_main_skill_node_skv_grey_seer_ruin_army_4",
            skill_key = "wh_main_skill_chs_lord_battle_stand_or_die",
            category_key = "battle",
            indent = 4,
            tier = 12,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
    },
    wh2_main_skv_warlord = {
        {
            node_key = "wh2_main_skill_node_skv_warlord_mount_1",
            skill_key = "wh2_main_skill_skv_warlord_mount_bonebreaker",
            category_key = "character",
            indent = 0,
            tier = 0,
            max_level = 1,
            is_mount_skill = true,
            unlock_ranks_by_level = { 11 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_main_skill_node_skv_warlord_mount_2",
            skill_key = "wh2_dlc16_skill_skv_warlord_mount_2",
            category_key = "character",
            indent = 0,
            tier = 1,
            max_level = 1,
            is_mount_skill = true,
            unlock_ranks_by_level = { 13 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_main_skill_node_skv_warlord_generic_2",
            skill_key = "wh2_main_skill_skv_generic_missile_ward",
            category_key = "character",
            indent = 0,
            tier = 2,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 7 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_main_skill_node_skv_warlord_generic_3",
            skill_key = "wh2_main_skill_skv_generic_magic_ward",
            category_key = "character",
            indent = 0,
            tier = 3,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 7 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_main_skill_node_skv_warlord_generic_4",
            skill_key = "wh2_main_skill_skv_combat_warpstone_weapon",
            category_key = "character",
            indent = 0,
            tier = 4,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 12 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_main_skill_node_skv_warlord_unique_1",
            skill_key = "wh2_main_skill_skv_unique_life_is_cheap",
            category_key = "character",
            indent = 1,
            tier = 1,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 12 },
            locked_node_keys = {
                "wh2_main_skill_node_skv_warlord_unique_2",
                "wh2_main_skill_node_skv_warlord_unique_3",
            }
        },
        {
            node_key = "wh2_main_skill_node_skv_warlord_unique_2",
            skill_key = "wh2_main_skill_skv_unique_deviousness",
            category_key = "character",
            indent = 1,
            tier = 2,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 12 },
            locked_node_keys = {
                "wh2_main_skill_node_skv_warlord_unique_1",
                "wh2_main_skill_node_skv_warlord_unique_3",
            }
        },
        {
            node_key = "wh2_main_skill_node_skv_warlord_unique_3",
            skill_key = "wh2_main_skill_skv_unique_expansion",
            category_key = "character",
            indent = 1,
            tier = 3,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 12 },
            locked_node_keys = {
                "wh2_main_skill_node_skv_warlord_unique_1",
                "wh2_main_skill_node_skv_warlord_unique_2",
            }
        },
        {
            node_key = "wh2_main_skill_node_skv_warlord_combat_0",
            skill_key = "wh2_main_skill_skv_combat_tail_weapon",
            category_key = "character",
            indent = 2,
            tier = 0,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_main_skill_node_skv_warlord_combat_1_1",
            skill_key = "wh2_main_skill_skv_combat_ruin_and_decay",
            category_key = "character",
            indent = 2,
            tier = 1,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_main_skill_node_skv_warlord_combat_1_2",
            skill_key = "wh2_dlc11_skill_all_lord_self_thick-skinned",
            category_key = "character",
            indent = 2,
            tier = 2,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_main_skill_node_skv_warlord_combat_1_3",
            skill_key = "wh2_dlc11_skill_all_lord_self_blade_master",
            category_key = "character",
            indent = 2,
            tier = 3,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_main_skill_node_skv_warlord_combat_1_4",
            skill_key = "wh2_dlc11_skill_all_lord_self_self_indomitable",
            category_key = "character",
            indent = 2,
            tier = 4,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_main_skill_node_skv_warlord_combat_2",
            skill_key = "wh2_main_skill_skv_generic_verminous_valour",
            category_key = "character",
            indent = 2,
            tier = 5,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 3 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_main_skill_node_skv_warlord_combat_3_1",
            skill_key = "wh2_dlc11_skill_all_lord_self_wound-maker",
            category_key = "character",
            indent = 2,
            tier = 6,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_main_skill_node_skv_warlord_combat_3_2",
            skill_key = "wh2_dlc11_skill_all_lord_self_scarred_veteran",
            category_key = "character",
            indent = 2,
            tier = 7,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_main_skill_node_skv_warlord_combat_3_3",
            skill_key = "wh2_dlc11_skill_all_lord_self_blade_shield",
            category_key = "character",
            indent = 2,
            tier = 8,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_main_skill_node_skv_warlord_combat_3_4",
            skill_key = "wh2_dlc11_skill_wef_lord_self_expeditious_endeavour",
            category_key = "character",
            indent = 2,
            tier = 9,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_main_skill_node_skv_warlord_combat_4",
            skill_key = "wh_main_skill_all_all_self_deadly_onslaught",
            category_key = "character",
            indent = 2,
            tier = 10,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
                "wh_dlc05_skill_node_wef_glade_lord_fem_self_ranged_06",
                "wh_dlc05_skill_node_wef_glade_lord_self_ranged_06",
            }
        },
        {
            node_key = "wh2_main_skill_node_skv_warlord_army_0",
            skill_key = "wh_main_skill_all_lord_battle_inspiring_presence",
            category_key = "battle",
            indent = 4,
            tier = 0,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_main_skill_node_skv_warlord_army_1_1",
            skill_key = "wh2_main_skill_skv_army_buff_clanrats",
            category_key = "battle",
            indent = 4,
            tier = 1,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_main_skill_node_skv_warlord_army_1_2",
            skill_key = "wh2_main_skill_skv_army_buff_runners",
            category_key = "battle",
            indent = 4,
            tier = 2,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_main_skill_node_skv_warlord_army_1_3",
            skill_key = "wh2_main_skill_skv_army_buff_weaponteams",
            category_key = "battle",
            indent = 4,
            tier = 3,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_main_skill_node_skv_warlord_army_1_4",
            skill_key = "wh2_main_skill_skv_army_buff_eliteinf",
            category_key = "battle",
            indent = 4,
            tier = 4,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_main_skill_node_skv_warlord_army_1_5",
            skill_key = "wh2_main_skill_skv_army_buff_monsters",
            category_key = "battle",
            indent = 4,
            tier = 5,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_main_skill_node_skv_warlord_army_1_6",
            skill_key = "wh2_main_skill_skv_army_buff_artillery",
            category_key = "battle",
            indent = 4,
            tier = 6,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_main_skill_node_skv_warlord_army_2",
            skill_key = "wh_main_skill_all_lord_battle_rally",
            category_key = "battle",
            indent = 4,
            tier = 7,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_main_skill_node_skv_warlord_army_3_1",
            skill_key = "wh2_main_skill_skv_army_buff_straight_to_the_point",
            category_key = "battle",
            indent = 4,
            tier = 8,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_main_skill_node_skv_warlord_army_3_2",
            skill_key = "wh2_main_skill_skv_army_buff_gutter_wise",
            category_key = "battle",
            indent = 4,
            tier = 9,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_main_skill_node_skv_warlord_army_3_3",
            skill_key = "wh2_main_skill_skv_army_buff_warped_workshops",
            category_key = "battle",
            indent = 4,
            tier = 10,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_main_skill_node_skv_warlord_army_3_4",
            skill_key = "wh2_main_skill_skv_army_buff_mutagenic_elixirs",
            category_key = "battle",
            indent = 4,
            tier = 11,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_main_skill_node_skv_warlord_army_4",
            skill_key = "wh_main_skill_chs_lord_battle_stand_or_die",
            category_key = "battle",
            indent = 4,
            tier = 12,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
    },
}

return data
