local data = {}

-- AUTO-GENERATED by tools/adamrogue/generate_stage_d_data.py.
data.CONTENT_FACTION_KEY = "wh_main_brt_bretonnia"

data.CHARACTER_SKILL_PLANS_BY_SUBTYPE = {
    wh_dlc07_brt_prophetess_beasts = {
        {
            node_key = "wh_dlc07_skill_node_brt_prophetess_beasts_unique_08",
            skill_key = "wh_dlc07_skill_brt_prophetess_beasts_unique_barded_warhorse",
            category_key = "character",
            indent = 0,
            tier = 1,
            max_level = 1,
            is_mount_skill = true,
            unlock_ranks_by_level = { 4 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc07_skill_node_brt_prophetess_beast_unique_02",
            skill_key = "wh_dlc07_skill_brt_prophetess_beasts_unique_royal_pegasus",
            category_key = "character",
            indent = 0,
            tier = 2,
            max_level = 1,
            is_mount_skill = true,
            unlock_ranks_by_level = { 12 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc07_skill_node_brt_prophetess_beasts_unique_04",
            skill_key = "wh_main_skill_brt_wizard_unique_damsel_aura_of_the_lady",
            category_key = "character",
            indent = 0,
            tier = 3,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 11 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc07_skill_node_brt_prophetess_beasts_unique_05",
            skill_key = "wh_main_skill_brt_lord_battle_virtue_of_empathy",
            category_key = "character",
            indent = 0,
            tier = 4,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc07_skill_node_brt_prophetess_beasts_unique_06",
            skill_key = "wh_main_skill_brt_lord_battle_lionhearted",
            category_key = "character",
            indent = 0,
            tier = 5,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc07_skill_node_brt_prophetess_beasts_unique_07",
            skill_key = "wh_main_skill_brt_lord_battle_basic_training",
            category_key = "character",
            indent = 0,
            tier = 6,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc07_skill_node_brt_prophetess_beast_unique_03",
            skill_key = "wh_main_skill_brt_all_unique_ladys_mantle",
            category_key = "character",
            indent = 0,
            tier = 7,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 7 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_main_skill_node_brt_prophetess_beast_vows_01",
            skill_key = "wh_dlc07_skill_brt_knight_vow",
            category_key = "character",
            indent = 1,
            tier = 1,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 1 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_main_skill_node_brt_prophetess_beast_vows_02",
            skill_key = "wh_dlc07_skill_brt_questing_vow",
            category_key = "character",
            indent = 1,
            tier = 2,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 1 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_main_skill_node_brt_prophetess_beast_vows_03",
            skill_key = "wh_dlc07_skill_brt_grail_vow",
            category_key = "character",
            indent = 1,
            tier = 3,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 1 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc07_skill_node_brt_prophetess_beast_magic_01",
            skill_key = "wh_dlc03_skill_magic_beasts_wyssans_wildform",
            category_key = "character",
            indent = 3,
            tier = 0,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc07_skill_node_brt_prophetess_beast_magic_02",
            skill_key = "wh_dlc03_skill_magic_beasts_wild_heart",
            category_key = "character",
            indent = 3,
            tier = 1,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc07_skill_node_brt_prophetess_beast_magic_03",
            skill_key = "wh2_main_skill_magic_beasts_flock_of_doom_lord",
            category_key = "character",
            indent = 3,
            tier = 2,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc07_skill_node_brt_prophetess_beast_magic_04",
            skill_key = "wh2_main_skill_magic_beasts_panns_impenetrable_pelt_lord",
            category_key = "character",
            indent = 3,
            tier = 3,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc07_skill_node_brt_prophetess_beast_magic_05",
            skill_key = "wh2_main_skill_magic_beasts_the_amber_spear_lord",
            category_key = "character",
            indent = 3,
            tier = 4,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc07_skill_node_brt_prophetess_beast_magic_06",
            skill_key = "wh_main_skill_all_magic_all_06_evasion",
            category_key = "character",
            indent = 3,
            tier = 5,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc07_skill_node_brt_prophetess_beast_magic_09",
            skill_key = "wh2_main_skill_magic_beasts_the_curse_of_anraheir_lord",
            category_key = "character",
            indent = 3,
            tier = 6,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc07_skill_node_brt_prophetess_beast_magic_10",
            skill_key = "wh2_main_skill_magic_beasts_transformation_of_kadon_lord",
            category_key = "character",
            indent = 3,
            tier = 7,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc07_skill_node_brt_prophetess_beast_magic_07",
            skill_key = "wh_main_skill_all_magic_all_07_earthing",
            category_key = "character",
            indent = 3,
            tier = 8,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc07_skill_node_brt_prophetess_beast_magic_08",
            skill_key = "wh_main_skill_all_magic_all_08_power_drain",
            category_key = "character",
            indent = 3,
            tier = 9,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc07_skill_node_brt_prophetess_beast_magic_11",
            skill_key = "wh_main_skill_all_magic_all_11_arcane_conduit",
            category_key = "character",
            indent = 3,
            tier = 10,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc07_skill_node_brt_prophetess_beast_magic1_dummy",
            skill_key = "wh2_main_skill_magic_beasts_dummy_wyssans_wildform_flock_of_doom",
            category_key = "character",
            indent = 3,
            tier = 11,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc07_skill_node_brt_prophetess_beast_battle_01",
            skill_key = "wh_main_skill_all_lord_battle_inspiring_presence",
            category_key = "battle",
            indent = 4,
            tier = 0,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc07_skill_node_brt_prophetess_beast_battle_02",
            skill_key = "wh2_dlc11_skill_brt_army_buff_low_born_militia",
            category_key = "battle",
            indent = 4,
            tier = 1,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc07_skill_node_brt_prophetess_beast_battle_03",
            skill_key = "wh2_dlc11_skill_brt_army_buff_proficiency_of_peasants",
            category_key = "battle",
            indent = 4,
            tier = 2,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc07_skill_node_brt_prophetess_beast_battle_04",
            skill_key = "wh2_dlc11_skill_brt_army_buff_worshippers_of_the_grail",
            category_key = "battle",
            indent = 4,
            tier = 3,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc07_skill_node_brt_prophetess_beast_battle_05",
            skill_key = "wh2_dlc11_skill_brt_army_buff_glorfinials_progeny",
            category_key = "battle",
            indent = 4,
            tier = 4,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc07_skill_node_brt_prophetess_beast_battle_06",
            skill_key = "wh2_dlc11_skill_brt_army_buff_guardians_of_the_lady",
            category_key = "battle",
            indent = 4,
            tier = 5,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc07_skill_node_brt_prophetess_beast_battle_07",
            skill_key = "wh2_dlc11_skill_brt_army_buff_engines_of_war",
            category_key = "battle",
            indent = 4,
            tier = 6,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc07_skill_node_brt_prophetess_beast_battle_08",
            skill_key = "wh_main_skill_all_lord_battle_rally",
            category_key = "battle",
            indent = 4,
            tier = 7,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc07_skill_node_brt_prophetess_beast_battle_09",
            skill_key = "wh2_dlc11_skill_brt_army_buff_the_peasants_duty",
            category_key = "battle",
            indent = 4,
            tier = 8,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc07_skill_node_brt_prophetess_beast_battle_10",
            skill_key = "wh2_dlc11_skill_brt_army_buff_protectors_of_the_realm",
            category_key = "battle",
            indent = 4,
            tier = 9,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc07_skill_node_brt_prophetess_beast_battle_11",
            skill_key = "wh2_dlc11_skill_brt_army_buff_chivalric_code",
            category_key = "battle",
            indent = 4,
            tier = 10,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc07_skill_node_brt_prophetess_beast_battle_12",
            skill_key = "wh2_dlc11_skill_brt_army_buff_guided_by_the_lady",
            category_key = "battle",
            indent = 4,
            tier = 11,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc07_skill_node_brt_prophetess_beast_battle_13",
            skill_key = "wh_main_skill_all_lord_battle_stand_your_ground",
            category_key = "battle",
            indent = 4,
            tier = 12,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
    },
    wh_dlc07_brt_prophetess_heavens = {
        {
            node_key = "wh_dlc07_skill_node_brt_prophetess_heavens_unique_08",
            skill_key = "wh_dlc07_skill_brt_prophetess_unique_barded_warhorse",
            category_key = "character",
            indent = 0,
            tier = 1,
            max_level = 1,
            is_mount_skill = true,
            unlock_ranks_by_level = { 4 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc07_skill_node_brt_prophetess_heavens_unique_02",
            skill_key = "wh_dlc07_skill_brt_prophetess_unique_royal_pegasus",
            category_key = "character",
            indent = 0,
            tier = 2,
            max_level = 1,
            is_mount_skill = true,
            unlock_ranks_by_level = { 12 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc07_skill_node_brt_prophetess_heavens_unique_04",
            skill_key = "wh_main_skill_brt_wizard_unique_damsel_aura_of_the_lady",
            category_key = "character",
            indent = 0,
            tier = 3,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 11 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc07_skill_node_brt_prophetess_heavens_unique_05",
            skill_key = "wh_main_skill_brt_lord_battle_virtue_of_empathy",
            category_key = "character",
            indent = 0,
            tier = 4,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc07_skill_node_brt_prophetess_heavens_unique_06",
            skill_key = "wh_main_skill_brt_lord_battle_lionhearted",
            category_key = "character",
            indent = 0,
            tier = 5,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc07_skill_node_brt_prophetess_heavens_unique_07",
            skill_key = "wh_main_skill_brt_lord_battle_basic_training",
            category_key = "character",
            indent = 0,
            tier = 6,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc07_skill_node_brt_prophetess_heavens_unique_03",
            skill_key = "wh_main_skill_brt_all_unique_ladys_mantle",
            category_key = "character",
            indent = 0,
            tier = 7,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 7 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_main_skill_node_brt_prophetess_heavens_vows_01",
            skill_key = "wh_dlc07_skill_brt_knight_vow",
            category_key = "character",
            indent = 1,
            tier = 1,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 1 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_main_skill_node_brt_prophetess_heavens_vows_02",
            skill_key = "wh_dlc07_skill_brt_questing_vow",
            category_key = "character",
            indent = 1,
            tier = 2,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 1 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_main_skill_node_brt_prophetess_heavens_vows_03",
            skill_key = "wh_dlc07_skill_brt_grail_vow",
            category_key = "character",
            indent = 1,
            tier = 3,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 1 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc07_skill_node_brt_prophetess_heavens_magic_01",
            skill_key = "wh_main_skill_all_magic_heavens_01_harmonic_convergence",
            category_key = "character",
            indent = 3,
            tier = 0,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc07_skill_node_brt_prophetess_heavens_magic_02",
            skill_key = "wh2_main_skill_all_magic_heavens_02_wind_blast_lord",
            category_key = "character",
            indent = 3,
            tier = 1,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc07_skill_node_brt_prophetess_heavens_magic_03",
            skill_key = "wh_main_skill_all_magic_heavens_03_rolling_skies",
            category_key = "character",
            indent = 3,
            tier = 2,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc07_skill_node_brt_prophetess_heavens_magic_04",
            skill_key = "wh2_main_skill_all_magic_heavens_04_curse_of_the_midnight_wind_lord",
            category_key = "character",
            indent = 3,
            tier = 3,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc07_skill_node_brt_prophetess_heavens_magic_05",
            skill_key = "wh2_main_skill_all_magic_heavens_05_urannons_thunderbolt_lord",
            category_key = "character",
            indent = 3,
            tier = 4,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc07_skill_node_brt_prophetess_heavens_magic_06",
            skill_key = "wh_main_skill_all_magic_all_06_evasion",
            category_key = "character",
            indent = 3,
            tier = 5,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc07_skill_node_brt_prophetess_heavens_magic_09",
            skill_key = "wh2_main_skill_all_magic_heavens_09_comet_of_casandora_lord",
            category_key = "character",
            indent = 3,
            tier = 6,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc07_skill_node_brt_prophetess_heavens_magic_10",
            skill_key = "wh2_main_skill_all_magic_heavens_10_chain_lightning_lord",
            category_key = "character",
            indent = 3,
            tier = 7,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc07_skill_node_brt_prophetess_heavens_magic_07",
            skill_key = "wh_main_skill_all_magic_all_07_earthing",
            category_key = "character",
            indent = 3,
            tier = 8,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc07_skill_node_brt_prophetess_heavens_magic_08",
            skill_key = "wh_main_skill_all_magic_all_08_power_drain",
            category_key = "character",
            indent = 3,
            tier = 9,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc07_skill_node_brt_prophetess_heavens_magic_11",
            skill_key = "wh_main_skill_all_magic_all_11_arcane_conduit",
            category_key = "character",
            indent = 3,
            tier = 10,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc07_skill_node_brt_prophetess_heavens_magic_dummy",
            skill_key = "wh2_main_skill_all_magic_heavens_dummy_harmonic_convergence_wind_blast",
            category_key = "character",
            indent = 3,
            tier = 11,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc07_skill_node_brt_prophetess_heavens_battle_01",
            skill_key = "wh_main_skill_all_lord_battle_inspiring_presence",
            category_key = "battle",
            indent = 4,
            tier = 0,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc07_skill_node_brt_prophetess_heavens_battle_02",
            skill_key = "wh2_dlc11_skill_brt_army_buff_low_born_militia",
            category_key = "battle",
            indent = 4,
            tier = 1,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc07_skill_node_brt_prophetess_heavens_battle_03",
            skill_key = "wh2_dlc11_skill_brt_army_buff_proficiency_of_peasants",
            category_key = "battle",
            indent = 4,
            tier = 2,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc07_skill_node_brt_prophetess_heavens_battle_04",
            skill_key = "wh2_dlc11_skill_brt_army_buff_worshippers_of_the_grail",
            category_key = "battle",
            indent = 4,
            tier = 3,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc07_skill_node_brt_prophetess_heavens_battle_05",
            skill_key = "wh2_dlc11_skill_brt_army_buff_glorfinials_progeny",
            category_key = "battle",
            indent = 4,
            tier = 4,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc07_skill_node_brt_prophetess_heavens_battle_06",
            skill_key = "wh2_dlc11_skill_brt_army_buff_guardians_of_the_lady",
            category_key = "battle",
            indent = 4,
            tier = 5,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc07_skill_node_brt_prophetess_heavens_battle_07",
            skill_key = "wh2_dlc11_skill_brt_army_buff_engines_of_war",
            category_key = "battle",
            indent = 4,
            tier = 6,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc07_skill_node_brt_prophetess_heavens_battle_08",
            skill_key = "wh_main_skill_all_lord_battle_rally",
            category_key = "battle",
            indent = 4,
            tier = 7,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc07_skill_node_brt_prophetess_heavens_battle_09",
            skill_key = "wh2_dlc11_skill_brt_army_buff_the_peasants_duty",
            category_key = "battle",
            indent = 4,
            tier = 8,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc07_skill_node_brt_prophetess_heavens_battle_10",
            skill_key = "wh2_dlc11_skill_brt_army_buff_protectors_of_the_realm",
            category_key = "battle",
            indent = 4,
            tier = 9,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc07_skill_node_brt_prophetess_heavens_battle_11",
            skill_key = "wh2_dlc11_skill_brt_army_buff_chivalric_code",
            category_key = "battle",
            indent = 4,
            tier = 10,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc07_skill_node_brt_prophetess_heavens_battle_12",
            skill_key = "wh2_dlc11_skill_brt_army_buff_guided_by_the_lady",
            category_key = "battle",
            indent = 4,
            tier = 11,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc07_skill_node_brt_prophetess_heavens_battle_13",
            skill_key = "wh_main_skill_all_lord_battle_stand_your_ground",
            category_key = "battle",
            indent = 4,
            tier = 12,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
    },
    wh_dlc07_brt_prophetess_life = {
        {
            node_key = "wh_dlc07_skill_node_brt_prophetess_life_unique_08",
            skill_key = "wh_dlc07_skill_brt_prophetess_life_unique_barded_warhorse",
            category_key = "character",
            indent = 0,
            tier = 1,
            max_level = 1,
            is_mount_skill = true,
            unlock_ranks_by_level = { 4 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc07_skill_node_brt_prophetess_life_unique_02",
            skill_key = "wh_dlc07_skill_brt_prophetess_life_unique_royal_pegasus",
            category_key = "character",
            indent = 0,
            tier = 2,
            max_level = 1,
            is_mount_skill = true,
            unlock_ranks_by_level = { 12 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc07_skill_node_brt_prophetess_life_unique_04",
            skill_key = "wh_main_skill_brt_wizard_unique_damsel_aura_of_the_lady",
            category_key = "character",
            indent = 0,
            tier = 3,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 11 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc07_skill_node_brt_prophetess_life_unique_05",
            skill_key = "wh_main_skill_brt_lord_battle_virtue_of_empathy",
            category_key = "character",
            indent = 0,
            tier = 4,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc07_skill_node_brt_prophetess_life_unique_06",
            skill_key = "wh_main_skill_brt_lord_battle_lionhearted",
            category_key = "character",
            indent = 0,
            tier = 5,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc07_skill_node_brt_prophetess_life_unique_07",
            skill_key = "wh_main_skill_brt_lord_battle_basic_training",
            category_key = "character",
            indent = 0,
            tier = 6,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc07_skill_node_brt_prophetess_life_unique_03",
            skill_key = "wh_main_skill_brt_all_unique_ladys_mantle",
            category_key = "character",
            indent = 0,
            tier = 7,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 7 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_main_skill_node_brt_prophetess_life_vows_01",
            skill_key = "wh_dlc07_skill_brt_knight_vow",
            category_key = "character",
            indent = 1,
            tier = 1,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 1 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_main_skill_node_brt_prophetess_life_vows_02",
            skill_key = "wh_dlc07_skill_brt_questing_vow",
            category_key = "character",
            indent = 1,
            tier = 2,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 1 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_main_skill_node_brt_prophetess_life_vows_03",
            skill_key = "wh_dlc07_skill_brt_grail_vow",
            category_key = "character",
            indent = 1,
            tier = 3,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 1 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc07_skill_node_brt_prophetess_life_magic_01",
            skill_key = "wh_dlc05_skill_magic_life_wizard_awakening_of_the_wood",
            category_key = "character",
            indent = 3,
            tier = 0,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc07_skill_node_brt_prophetess_life_magic_02",
            skill_key = "wh_dlc05_skill_magic_life_life_bloom",
            category_key = "character",
            indent = 3,
            tier = 1,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc07_skill_node_brt_prophetess_life_magic_03",
            skill_key = "wh2_main_skill_magic_life_wizard_earth_blood_lord",
            category_key = "character",
            indent = 3,
            tier = 2,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc07_skill_node_brt_prophetess_life_magic_04",
            skill_key = "wh2_main_skill_magic_life_wizard_shield_of_thorns_lord",
            category_key = "character",
            indent = 3,
            tier = 3,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc07_skill_node_brt_prophetess_life_magic_05",
            skill_key = "wh2_main_skill_magic_life_wizard_flesh_to_stone_lord",
            category_key = "character",
            indent = 3,
            tier = 4,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc07_skill_node_brt_prophetess_life_magic_06",
            skill_key = "wh_main_skill_all_magic_all_06_evasion",
            category_key = "character",
            indent = 3,
            tier = 5,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc07_skill_node_brt_prophetess_life_magic_09",
            skill_key = "wh2_main_skill_magic_life_wizard_regrowth_lord",
            category_key = "character",
            indent = 3,
            tier = 6,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc07_skill_node_brt_prophetess_life_magic_10",
            skill_key = "wh2_main_skill_magic_life_wizard_the_dwellers_below_lord",
            category_key = "character",
            indent = 3,
            tier = 7,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc07_skill_node_brt_prophetess_life_magic_07",
            skill_key = "wh_main_skill_all_magic_all_07_earthing",
            category_key = "character",
            indent = 3,
            tier = 8,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc07_skill_node_brt_prophetess_life_magic_08",
            skill_key = "wh_main_skill_all_magic_all_08_power_drain",
            category_key = "character",
            indent = 3,
            tier = 9,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc07_skill_node_brt_prophetess_life_magic_11",
            skill_key = "wh_main_skill_all_magic_all_11_arcane_conduit",
            category_key = "character",
            indent = 3,
            tier = 10,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc07_skill_node_brt_prophetess_life_magic1_dummy",
            skill_key = "wh2_main_skill_magic_life_wizard_awakening_of_the_wood_earth_blood_dummy",
            category_key = "character",
            indent = 3,
            tier = 11,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc07_skill_node_brt_prophetess_life_battle_01",
            skill_key = "wh_main_skill_all_lord_battle_inspiring_presence",
            category_key = "battle",
            indent = 4,
            tier = 0,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc07_skill_node_brt_prophetess_life_battle_02",
            skill_key = "wh2_dlc11_skill_brt_army_buff_low_born_militia",
            category_key = "battle",
            indent = 4,
            tier = 1,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc07_skill_node_brt_prophetess_life_battle_03",
            skill_key = "wh2_dlc11_skill_brt_army_buff_proficiency_of_peasants",
            category_key = "battle",
            indent = 4,
            tier = 2,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc07_skill_node_brt_prophetess_life_battle_04",
            skill_key = "wh2_dlc11_skill_brt_army_buff_worshippers_of_the_grail",
            category_key = "battle",
            indent = 4,
            tier = 3,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc07_skill_node_brt_prophetess_life_battle_05",
            skill_key = "wh2_dlc11_skill_brt_army_buff_glorfinials_progeny",
            category_key = "battle",
            indent = 4,
            tier = 4,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc07_skill_node_brt_prophetess_life_battle_06",
            skill_key = "wh2_dlc11_skill_brt_army_buff_guardians_of_the_lady",
            category_key = "battle",
            indent = 4,
            tier = 5,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc07_skill_node_brt_prophetess_life_battle_07",
            skill_key = "wh2_dlc11_skill_brt_army_buff_engines_of_war",
            category_key = "battle",
            indent = 4,
            tier = 6,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc07_skill_node_brt_prophetess_life_battle_08",
            skill_key = "wh_main_skill_all_lord_battle_rally",
            category_key = "battle",
            indent = 4,
            tier = 7,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc07_skill_node_brt_prophetess_life_battle_09",
            skill_key = "wh2_dlc11_skill_brt_army_buff_the_peasants_duty",
            category_key = "battle",
            indent = 4,
            tier = 8,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc07_skill_node_brt_prophetess_life_battle_10",
            skill_key = "wh2_dlc11_skill_brt_army_buff_protectors_of_the_realm",
            category_key = "battle",
            indent = 4,
            tier = 9,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc07_skill_node_brt_prophetess_life_battle_11",
            skill_key = "wh2_dlc11_skill_brt_army_buff_chivalric_code",
            category_key = "battle",
            indent = 4,
            tier = 10,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc07_skill_node_brt_prophetess_life_battle_12",
            skill_key = "wh2_dlc11_skill_brt_army_buff_guided_by_the_lady",
            category_key = "battle",
            indent = 4,
            tier = 11,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc07_skill_node_brt_prophetess_life_battle_13",
            skill_key = "wh_main_skill_all_lord_battle_stand_your_ground",
            category_key = "battle",
            indent = 4,
            tier = 12,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
    },
    wh_main_brt_lord = {
        {
            node_key = "wh_main_skill_node_brt_lord_unique_01",
            skill_key = "wh_main_skill_brt_lord_unique_general_barded_warhorse",
            category_key = "character",
            indent = 0,
            tier = 0,
            max_level = 1,
            is_mount_skill = true,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_main_skill_node_brt_lord_unique_02",
            skill_key = "wh_main_skill_brt_lord_unique_general_royal_pegasus",
            category_key = "character",
            indent = 0,
            tier = 1,
            max_level = 1,
            is_mount_skill = true,
            unlock_ranks_by_level = { 7 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_main_skill_node_brt_lord_unique_03",
            skill_key = "wh_main_skill_brt_lord_unique_general_hippogryph",
            category_key = "character",
            indent = 0,
            tier = 2,
            max_level = 1,
            is_mount_skill = true,
            unlock_ranks_by_level = { 13 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_main_skill_node_brt_lord_unique_05",
            skill_key = "wh_main_skill_brt_lord_unique_general_lance_formation",
            category_key = "character",
            indent = 0,
            tier = 4,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 5 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_main_skill_node_brt_lord_unique_07",
            skill_key = "wh_main_skill_brt_lord_unique_the_blessing_of_the_lady",
            category_key = "character",
            indent = 0,
            tier = 5,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 11 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_main_skill_node_brt_lord_unique_08",
            skill_key = "wh_main_skill_brt_lord_battle_virtue_of_empathy",
            category_key = "character",
            indent = 0,
            tier = 6,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_main_skill_node_brt_lord_unique_09",
            skill_key = "wh_main_skill_brt_lord_battle_lionhearted",
            category_key = "character",
            indent = 0,
            tier = 7,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_main_skill_node_brt_lord_unique_10",
            skill_key = "wh_main_skill_brt_lord_battle_basic_training",
            category_key = "character",
            indent = 0,
            tier = 8,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_main_skill_node_brt_lord_unique_06",
            skill_key = "wh_main_skill_brt_all_unique_ladys_mantle",
            category_key = "character",
            indent = 0,
            tier = 9,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 7 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_main_skill_node_brt_lord_vows_01",
            skill_key = "wh_dlc07_skill_brt_knight_vow",
            category_key = "character",
            indent = 1,
            tier = 1,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 1 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_main_skill_node_brt_lord_vows_02",
            skill_key = "wh_dlc07_skill_brt_questing_vow",
            category_key = "character",
            indent = 1,
            tier = 2,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 1 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_main_skill_node_brt_lord_vows_03",
            skill_key = "wh_dlc07_skill_brt_grail_vow",
            category_key = "character",
            indent = 1,
            tier = 3,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 1 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_main_skill_node_brt_lord_self_01",
            skill_key = "wh_main_skill_all_all_self_blade_master_starter",
            category_key = "character",
            indent = 2,
            tier = 0,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_main_skill_node_brt_lord_self_02",
            skill_key = "wh2_dlc11_skill_all_lord_self_devastating_charge",
            category_key = "character",
            indent = 2,
            tier = 1,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_main_skill_node_brt_lord_self_03",
            skill_key = "wh2_dlc11_skill_all_lord_self_full_plate_armour",
            category_key = "character",
            indent = 2,
            tier = 2,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_main_skill_node_brt_lord_self_04",
            skill_key = "wh2_dlc11_skill_all_lord_self_scarred_veteran",
            category_key = "character",
            indent = 2,
            tier = 3,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_main_skill_node_brt_lord_self_05",
            skill_key = "wh2_dlc11_skill_all_lord_self_hard_to_hit",
            category_key = "character",
            indent = 2,
            tier = 4,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_main_skill_node_brt_lord_self_06",
            skill_key = "wh_main_skill_all_all_self_foe-seeker",
            category_key = "character",
            indent = 2,
            tier = 5,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_main_skill_node_brt_lord_self_07",
            skill_key = "wh2_dlc11_skill_all_lord_self_wound-maker",
            category_key = "character",
            indent = 2,
            tier = 6,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_main_skill_node_brt_lord_self_08",
            skill_key = "wh2_dlc11_skill_all_lord_self_deadly_blade",
            category_key = "character",
            indent = 2,
            tier = 7,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_main_skill_node_brt_lord_self_09",
            skill_key = "wh2_dlc11_skill_all_lord_self_self_indomitable",
            category_key = "character",
            indent = 2,
            tier = 8,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_main_skill_node_brt_lord_self_10",
            skill_key = "wh2_dlc11_skill_all_lord_self_blade_shield",
            category_key = "character",
            indent = 2,
            tier = 9,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_main_skill_node_brt_lord_self_11",
            skill_key = "wh_main_skill_all_all_self_deadly_onslaught",
            category_key = "character",
            indent = 2,
            tier = 10,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
                "wh_dlc05_skill_node_wef_glade_lord_fem_self_ranged_06",
                "wh_dlc05_skill_node_wef_glade_lord_self_ranged_06",
            }
        },
        {
            node_key = "wh_main_skill_node_brt_lord_battle_01",
            skill_key = "wh_main_skill_all_lord_battle_inspiring_presence",
            category_key = "battle",
            indent = 4,
            tier = 0,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_main_skill_node_brt_lord_battle_02",
            skill_key = "wh2_dlc11_skill_brt_army_buff_low_born_militia",
            category_key = "battle",
            indent = 4,
            tier = 1,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_main_skill_node_brt_lord_battle_03",
            skill_key = "wh2_dlc11_skill_brt_army_buff_proficiency_of_peasants",
            category_key = "battle",
            indent = 4,
            tier = 2,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_main_skill_node_brt_lord_battle_04",
            skill_key = "wh2_dlc11_skill_brt_army_buff_worshippers_of_the_grail",
            category_key = "battle",
            indent = 4,
            tier = 3,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_main_skill_node_brt_lord_battle_05",
            skill_key = "wh2_dlc11_skill_brt_army_buff_glorfinials_progeny",
            category_key = "battle",
            indent = 4,
            tier = 4,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_main_skill_node_brt_lord_battle_06",
            skill_key = "wh2_dlc11_skill_brt_army_buff_guardians_of_the_lady",
            category_key = "battle",
            indent = 4,
            tier = 5,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_main_skill_node_brt_lord_battle_07",
            skill_key = "wh2_dlc11_skill_brt_army_buff_engines_of_war",
            category_key = "battle",
            indent = 4,
            tier = 6,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_main_skill_node_brt_lord_battle_08",
            skill_key = "wh_main_skill_all_lord_battle_rally",
            category_key = "battle",
            indent = 4,
            tier = 7,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_main_skill_node_brt_lord_battle_09",
            skill_key = "wh2_dlc11_skill_brt_army_buff_the_peasants_duty",
            category_key = "battle",
            indent = 4,
            tier = 8,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_main_skill_node_brt_lord_battle_10",
            skill_key = "wh2_dlc11_skill_brt_army_buff_protectors_of_the_realm",
            category_key = "battle",
            indent = 4,
            tier = 9,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_main_skill_node_brt_lord_battle_11",
            skill_key = "wh2_dlc11_skill_brt_army_buff_chivalric_code",
            category_key = "battle",
            indent = 4,
            tier = 10,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_main_skill_node_brt_lord_battle_12",
            skill_key = "wh2_dlc11_skill_brt_army_buff_guided_by_the_lady",
            category_key = "battle",
            indent = 4,
            tier = 11,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_main_skill_node_brt_lord_battle_13",
            skill_key = "wh_main_skill_all_lord_battle_stand_your_ground",
            category_key = "battle",
            indent = 4,
            tier = 12,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
    },
}

return data
