local data = {}

-- AUTO-GENERATED by tools/adamrogue/generate_stage_d_data.py.
data.CONTENT_FACTION_KEY = "wh3_dlc23_chd_astragoth"

data.CHARACTER_SKILL_PLANS_BY_SUBTYPE = {
    wh3_dlc23_chd_overseer = {
        {
            node_key = "wh3_dlc23_skill_node_chd_overseer_mount_great_taurus",
            skill_key = "wh3_dlc23_skill_chd_overseer_mount_great_taurus",
            category_key = "character",
            indent = 0,
            tier = 0,
            max_level = 1,
            is_mount_skill = true,
            unlock_ranks_by_level = { 9 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_overseer_mount_lammasu",
            skill_key = "wh3_dlc23_skill_chd_overseer_mount_lammasu",
            category_key = "character",
            indent = 0,
            tier = 1,
            max_level = 1,
            is_mount_skill = true,
            unlock_ranks_by_level = { 14 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_overseer_character_2",
            skill_key = "wh3_dlc23_skill_chd_unyielding_command",
            category_key = "character",
            indent = 0,
            tier = 3,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 7 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_overseer_character_4",
            skill_key = "wh3_dlc23_skill_chd_hashuts_scales",
            category_key = "character",
            indent = 0,
            tier = 4,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 7 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_overseer_character_5",
            skill_key = "wh3_dlc23_skill_chd_headdress_of_zharr",
            category_key = "character",
            indent = 0,
            tier = 5,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 7 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_overseer_personal_0",
            skill_key = "wh3_dlc23_skill_chd_overseer_sorcerers_thrall",
            category_key = "character",
            indent = 1,
            tier = 0,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 12 },
            locked_node_keys = {
                "wh3_dlc23_skill_node_chd_overseer_personal_2",
                "wh3_dlc23_skill_node_chd_overseer_personal_4",
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_overseer_personal_1",
            skill_key = "wh3_dlc23_skill_chd_overseer_dark_pact",
            category_key = "character",
            indent = 1,
            tier = 1,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_overseer_personal_2",
            skill_key = "wh3_dlc23_skill_chd_overseer_adjutant",
            category_key = "character",
            indent = 1,
            tier = 2,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 12 },
            locked_node_keys = {
                "wh3_dlc23_skill_node_chd_overseer_personal_0",
                "wh3_dlc23_skill_node_chd_overseer_personal_4",
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_overseer_personal_3",
            skill_key = "wh3_dlc23_skill_chd_overseer_armourer",
            category_key = "character",
            indent = 1,
            tier = 3,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_overseer_personal_4",
            skill_key = "wh3_dlc23_skill_chd_overseer_taskmaster",
            category_key = "character",
            indent = 1,
            tier = 4,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 12 },
            locked_node_keys = {
                "wh3_dlc23_skill_node_chd_overseer_personal_0",
                "wh3_dlc23_skill_node_chd_overseer_personal_2",
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_overseer_personal_5",
            skill_key = "wh3_dlc23_skill_chd_overseer_harsh_master",
            category_key = "character",
            indent = 1,
            tier = 5,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 6 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_overseer_combat_0",
            skill_key = "wh3_dlc23_skill_chd_all_self_survivalist",
            category_key = "character",
            indent = 2,
            tier = 0,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_overseer_combat_1_1",
            skill_key = "wh2_dlc11_skill_all_lord_self_blade_master",
            category_key = "character",
            indent = 2,
            tier = 1,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_overseer_combat_1_2",
            skill_key = "wh2_dlc11_skill_all_lord_self_hard_to_hit",
            category_key = "character",
            indent = 2,
            tier = 2,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_overseer_combat_1_3",
            skill_key = "wh2_dlc11_skill_wef_lord_self_expeditious_endeavour",
            category_key = "character",
            indent = 2,
            tier = 3,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_overseer_combat_1_4",
            skill_key = "wh2_dlc11_skill_all_lord_self_wound-maker",
            category_key = "character",
            indent = 2,
            tier = 4,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_overseer_combat_2",
            skill_key = "wh_main_skill_all_all_self_foe-seeker",
            category_key = "character",
            indent = 2,
            tier = 5,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_overseer_combat_3_1",
            skill_key = "wh2_dlc11_skill_all_lord_self_full_plate_armour",
            category_key = "character",
            indent = 2,
            tier = 6,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_overseer_combat_3_2",
            skill_key = "wh3_dlc23_skill_chd_all_self_violent_delights",
            category_key = "character",
            indent = 2,
            tier = 7,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_overseer_combat_3_3",
            skill_key = "wh2_dlc11_skill_all_lord_self_self_indomitable",
            category_key = "character",
            indent = 2,
            tier = 8,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_overseer_combat_3_4",
            skill_key = "wh2_dlc11_skill_all_lord_self_scarred_veteran",
            category_key = "character",
            indent = 2,
            tier = 9,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_overseer_combat_4",
            skill_key = "wh_main_skill_all_all_self_deadly_onslaught",
            category_key = "character",
            indent = 2,
            tier = 10,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
                "wh_dlc05_skill_node_wef_glade_lord_fem_self_ranged_06",
                "wh_dlc05_skill_node_wef_glade_lord_self_ranged_06",
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_overseer_army_0",
            skill_key = "wh_main_skill_all_lord_battle_inspiring_presence",
            category_key = "battle",
            indent = 4,
            tier = 0,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_overseer_army_1_1",
            skill_key = "wh3_dlc23_skill_chd_army_buff_melee_labourer_hobgoblin",
            category_key = "battle",
            indent = 4,
            tier = 1,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_overseer_army_1_2",
            skill_key = "wh3_dlc23_skill_chd_army_buff_melee_chaos_dwarfs",
            category_key = "battle",
            indent = 4,
            tier = 2,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_overseer_army_1_3",
            skill_key = "wh3_dlc23_skill_chd_army_buff_missiles",
            category_key = "battle",
            indent = 4,
            tier = 3,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_overseer_army_1_4",
            skill_key = "wh3_dlc23_skill_chd_army_buff_artillery",
            category_key = "battle",
            indent = 4,
            tier = 4,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_overseer_army_1_5",
            skill_key = "wh3_dlc23_skill_chd_army_buff_bull_centaurs",
            category_key = "battle",
            indent = 4,
            tier = 5,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_overseer_army_1_6",
            skill_key = "wh3_dlc23_skill_chd_army_buff_monsters_kdaai_skullcracker",
            category_key = "battle",
            indent = 4,
            tier = 6,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_overseer_army_2",
            skill_key = "wh_main_skill_all_lord_battle_rally",
            category_key = "battle",
            indent = 4,
            tier = 7,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_overseer_army_3_1",
            skill_key = "wh3_dlc23_skill_chd_army_buff_labourer_hobgoblin_rank7",
            category_key = "battle",
            indent = 4,
            tier = 8,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_overseer_army_3_2",
            skill_key = "wh3_dlc23_skill_chd_army_buff_melee_chaos_dwarfs_rank7",
            category_key = "battle",
            indent = 4,
            tier = 9,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_overseer_army_3_3",
            skill_key = "wh3_dlc23_skill_chd_army_buff_artillery_chaos_dwarf_missiles_rank7",
            category_key = "battle",
            indent = 4,
            tier = 10,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_overseer_army_3_4",
            skill_key = "wh3_dlc23_skill_chd_army_buff_monsters_kdaai_skullcracker_bull_centaurs_rank7",
            category_key = "battle",
            indent = 4,
            tier = 11,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_overseer_army_4",
            skill_key = "wh_main_skill_chs_lord_battle_stand_or_die",
            category_key = "battle",
            indent = 4,
            tier = 12,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
    },
    wh3_dlc23_chd_sorcerer_prophet_death = {
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_death_mount_great_taurus",
            skill_key = "wh3_dlc23_skill_chd_sorcerer_prophet_death_mount_great_taurus",
            category_key = "character",
            indent = 0,
            tier = 0,
            max_level = 1,
            is_mount_skill = true,
            unlock_ranks_by_level = { 9 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_death_mount_lammasu",
            skill_key = "wh3_dlc23_skill_chd_sorcerer_prophet_death_mount_lammasu",
            category_key = "character",
            indent = 0,
            tier = 1,
            max_level = 1,
            is_mount_skill = true,
            unlock_ranks_by_level = { 14 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_death_mount_bale_taurus",
            skill_key = "wh3_dlc23_skill_chd_sorcerer_prophet_death_mount_bale_taurus",
            category_key = "character",
            indent = 0,
            tier = 2,
            max_level = 1,
            is_mount_skill = true,
            unlock_ranks_by_level = { 18 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_death_character_3",
            skill_key = "wh3_dlc23_skill_chd_unyielding_command",
            category_key = "character",
            indent = 0,
            tier = 3,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 7 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_death_character_4",
            skill_key = "wh3_dlc23_skill_chd_sorcerer_prophet_careful_casting",
            category_key = "character",
            indent = 0,
            tier = 4,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 16 },
            locked_node_keys = {
                "wh3_dlc23_skill_node_chd_sorcerer_prophet_death_character_5",
                "wh3_dlc23_skill_node_chd_sorcerer_prophet_fire_character_5",
                "wh3_dlc23_skill_node_chd_sorcerer_prophet_hashut_character_5",
                "wh3_dlc23_skill_node_chd_sorcerer_prophet_metal_character_5",
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_death_character_5",
            skill_key = "wh3_dlc23_skill_chd_sorcerer_prophet_sorcerers_curse",
            category_key = "character",
            indent = 0,
            tier = 5,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 16 },
            locked_node_keys = {
                "wh3_dlc23_skill_node_chd_sorcerer_prophet_death_character_4",
                "wh3_dlc23_skill_node_chd_sorcerer_prophet_fire_character_4",
                "wh3_dlc23_skill_node_chd_sorcerer_prophet_hashut_character_4",
                "wh3_dlc23_skill_node_chd_sorcerer_prophet_metal_character_4",
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_death_character_6",
            skill_key = "wh3_dlc23_skill_chd_hashuts_scales",
            category_key = "character",
            indent = 0,
            tier = 6,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 7 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_death_character_7",
            skill_key = "wh3_dlc23_skill_chd_headdress_of_zharr",
            category_key = "character",
            indent = 0,
            tier = 7,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 7 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_death_personal_0",
            skill_key = "wh3_dlc23_skill_chd_sorcerer_prophet_thirsty_for_magic",
            category_key = "character",
            indent = 1,
            tier = 0,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 11 },
            locked_node_keys = {
                "wh3_dlc23_skill_node_chd_sorcerer_prophet_death_personal_1",
                "wh3_dlc23_skill_node_chd_sorcerer_prophet_death_personal_2",
                "wh3_dlc23_skill_node_chd_sorcerer_prophet_fire_personal_1",
                "wh3_dlc23_skill_node_chd_sorcerer_prophet_fire_personal_2",
                "wh3_dlc23_skill_node_chd_sorcerer_prophet_hashut_personal_1",
                "wh3_dlc23_skill_node_chd_sorcerer_prophet_hashut_personal_2",
                "wh3_dlc23_skill_node_chd_sorcerer_prophet_metal_personal_1",
                "wh3_dlc23_skill_node_chd_sorcerer_prophet_metal_personal_2",
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_death_personal_1",
            skill_key = "wh3_dlc23_skill_chd_sorcerer_prophet_flesh_sacrifice",
            category_key = "character",
            indent = 1,
            tier = 1,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 11 },
            locked_node_keys = {
                "wh3_dlc23_skill_node_chd_sorcerer_prophet_death_personal_0",
                "wh3_dlc23_skill_node_chd_sorcerer_prophet_death_personal_2",
                "wh3_dlc23_skill_node_chd_sorcerer_prophet_fire_personal_0",
                "wh3_dlc23_skill_node_chd_sorcerer_prophet_fire_personal_2",
                "wh3_dlc23_skill_node_chd_sorcerer_prophet_hashut_personal_0",
                "wh3_dlc23_skill_node_chd_sorcerer_prophet_hashut_personal_2",
                "wh3_dlc23_skill_node_chd_sorcerer_prophet_metal_personal_0",
                "wh3_dlc23_skill_node_chd_sorcerer_prophet_metal_personal_2",
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_death_personal_2",
            skill_key = "wh3_dlc23_skill_chd_sorcerer_prophet_voice_of_hashut",
            category_key = "character",
            indent = 1,
            tier = 2,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 11 },
            locked_node_keys = {
                "wh3_dlc23_skill_node_chd_sorcerer_prophet_death_personal_0",
                "wh3_dlc23_skill_node_chd_sorcerer_prophet_death_personal_1",
                "wh3_dlc23_skill_node_chd_sorcerer_prophet_fire_personal_0",
                "wh3_dlc23_skill_node_chd_sorcerer_prophet_fire_personal_1",
                "wh3_dlc23_skill_node_chd_sorcerer_prophet_hashut_personal_0",
                "wh3_dlc23_skill_node_chd_sorcerer_prophet_hashut_personal_1",
                "wh3_dlc23_skill_node_chd_sorcerer_prophet_metal_personal_0",
                "wh3_dlc23_skill_node_chd_sorcerer_prophet_metal_personal_1",
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_death_magic_0",
            skill_key = "wh2_dlc11_skill_vmp_bloodline_necrarch_magic_spirit_leech",
            category_key = "character",
            indent = 2,
            tier = 0,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_death_magic_1_2",
            skill_key = "wh2_main_skill_all_magic_death_02_aspect_of_the_dreadknight_lord",
            category_key = "character",
            indent = 2,
            tier = 1,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_death_magic_1_1",
            skill_key = "wh_main_skill_all_magic_death_03_life_leeching",
            category_key = "character",
            indent = 2,
            tier = 2,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_death_magic_1_3",
            skill_key = "wh2_main_skill_all_magic_death_04_soulblight_lord",
            category_key = "character",
            indent = 2,
            tier = 3,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_death_magic_1_4",
            skill_key = "wh2_main_skill_all_magic_death_05_doom_and_darkness_lord",
            category_key = "character",
            indent = 2,
            tier = 4,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_death_magic_2",
            skill_key = "wh_main_skill_all_magic_all_06_evasion",
            category_key = "character",
            indent = 2,
            tier = 5,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_death_magic_3_3",
            skill_key = "wh2_main_skill_all_magic_death_09_the_fate_of_bjuna_lord",
            category_key = "character",
            indent = 2,
            tier = 6,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_death_magic_3_4",
            skill_key = "wh2_main_skill_all_magic_death_10_the_purple_sun_of_xereus_lord",
            category_key = "character",
            indent = 2,
            tier = 7,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_death_magic_3_1",
            skill_key = "wh_main_skill_all_magic_all_07_earthing",
            category_key = "character",
            indent = 2,
            tier = 8,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_death_magic_3_2",
            skill_key = "wh_main_skill_all_magic_all_08_power_drain",
            category_key = "character",
            indent = 2,
            tier = 9,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_death_magic_4",
            skill_key = "wh_main_skill_all_magic_all_11_arcane_conduit",
            category_key = "character",
            indent = 2,
            tier = 10,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_death_magic_dummy",
            skill_key = "wh2_main_skill_all_magic_death_dummy_spirit_leech_aspect_of_the_dreadknight",
            category_key = "character",
            indent = 2,
            tier = 11,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_death_combat_0",
            skill_key = "wh3_dlc23_skill_chd_all_self_survivalist",
            category_key = "character",
            indent = 3,
            tier = 0,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_death_combat_1_1",
            skill_key = "wh3_dlc23_skill_chd_lord_self_always_ready",
            category_key = "character",
            indent = 3,
            tier = 1,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_death_combat_1_2",
            skill_key = "wh3_dlc23_skill_chd_lord_self_bandolier",
            category_key = "character",
            indent = 3,
            tier = 2,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_death_combat_1_3",
            skill_key = "wh2_dlc11_skill_wef_lord_self_expeditious_endeavour",
            category_key = "character",
            indent = 3,
            tier = 3,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_death_combat_1_4",
            skill_key = "wh3_dlc23_skill_chd_lord_self_piercing_shots",
            category_key = "character",
            indent = 3,
            tier = 4,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_death_combat_2",
            skill_key = "wh_main_skill_all_all_self_foe-seeker",
            category_key = "character",
            indent = 3,
            tier = 5,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_death_army_0",
            skill_key = "wh_main_skill_all_lord_battle_inspiring_presence",
            category_key = "battle",
            indent = 4,
            tier = 0,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_death_army_1_1",
            skill_key = "wh3_dlc23_skill_chd_army_buff_melee_labourer_hobgoblin",
            category_key = "battle",
            indent = 4,
            tier = 1,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_death_army_1_2",
            skill_key = "wh3_dlc23_skill_chd_army_buff_melee_chaos_dwarfs",
            category_key = "battle",
            indent = 4,
            tier = 2,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_death_army_1_3",
            skill_key = "wh3_dlc23_skill_chd_army_buff_missiles",
            category_key = "battle",
            indent = 4,
            tier = 3,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_death_army_1_4",
            skill_key = "wh3_dlc23_skill_chd_army_buff_artillery",
            category_key = "battle",
            indent = 4,
            tier = 4,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_death_army_1_5",
            skill_key = "wh3_dlc23_skill_chd_army_buff_bull_centaurs",
            category_key = "battle",
            indent = 4,
            tier = 5,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_death_army_1_6",
            skill_key = "wh3_dlc23_skill_chd_army_buff_monsters_kdaai_skullcracker",
            category_key = "battle",
            indent = 4,
            tier = 6,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_death_army_2",
            skill_key = "wh_main_skill_all_lord_battle_rally",
            category_key = "battle",
            indent = 4,
            tier = 7,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_death_army_3_1",
            skill_key = "wh3_dlc23_skill_chd_army_buff_labourer_hobgoblin_rank7",
            category_key = "battle",
            indent = 4,
            tier = 8,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_death_army_3_2",
            skill_key = "wh3_dlc23_skill_chd_army_buff_melee_chaos_dwarfs_rank7",
            category_key = "battle",
            indent = 4,
            tier = 9,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_death_army_3_3",
            skill_key = "wh3_dlc23_skill_chd_army_buff_artillery_chaos_dwarf_missiles_rank7",
            category_key = "battle",
            indent = 4,
            tier = 10,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_death_army_3_4",
            skill_key = "wh3_dlc23_skill_chd_army_buff_monsters_kdaai_skullcracker_bull_centaurs_rank7",
            category_key = "battle",
            indent = 4,
            tier = 11,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_death_army_4",
            skill_key = "wh_main_skill_chs_lord_battle_stand_or_die",
            category_key = "battle",
            indent = 4,
            tier = 12,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
    },
    wh3_dlc23_chd_sorcerer_prophet_fire = {
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_fire_mount_great_taurus",
            skill_key = "wh3_dlc23_skill_chd_sorcerer_prophet_fire_mount_great_taurus",
            category_key = "character",
            indent = 0,
            tier = 0,
            max_level = 1,
            is_mount_skill = true,
            unlock_ranks_by_level = { 9 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_fire_mount_lammasu",
            skill_key = "wh3_dlc23_skill_chd_sorcerer_prophet_fire_mount_lammasu",
            category_key = "character",
            indent = 0,
            tier = 1,
            max_level = 1,
            is_mount_skill = true,
            unlock_ranks_by_level = { 14 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_fire_mount_bale_taurus",
            skill_key = "wh3_dlc23_skill_chd_sorcerer_prophet_fire_mount_bale_taurus",
            category_key = "character",
            indent = 0,
            tier = 2,
            max_level = 1,
            is_mount_skill = true,
            unlock_ranks_by_level = { 18 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_fire_character_3",
            skill_key = "wh3_dlc23_skill_chd_unyielding_command",
            category_key = "character",
            indent = 0,
            tier = 3,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 7 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_fire_character_4",
            skill_key = "wh3_dlc23_skill_chd_sorcerer_prophet_careful_casting",
            category_key = "character",
            indent = 0,
            tier = 4,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 16 },
            locked_node_keys = {
                "wh3_dlc23_skill_node_chd_sorcerer_prophet_death_character_5",
                "wh3_dlc23_skill_node_chd_sorcerer_prophet_fire_character_5",
                "wh3_dlc23_skill_node_chd_sorcerer_prophet_hashut_character_5",
                "wh3_dlc23_skill_node_chd_sorcerer_prophet_metal_character_5",
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_fire_character_5",
            skill_key = "wh3_dlc23_skill_chd_sorcerer_prophet_sorcerers_curse",
            category_key = "character",
            indent = 0,
            tier = 5,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 16 },
            locked_node_keys = {
                "wh3_dlc23_skill_node_chd_sorcerer_prophet_death_character_4",
                "wh3_dlc23_skill_node_chd_sorcerer_prophet_fire_character_4",
                "wh3_dlc23_skill_node_chd_sorcerer_prophet_hashut_character_4",
                "wh3_dlc23_skill_node_chd_sorcerer_prophet_metal_character_4",
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_fire_character_6",
            skill_key = "wh3_dlc23_skill_chd_hashuts_scales",
            category_key = "character",
            indent = 0,
            tier = 6,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 7 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_fire_character_7",
            skill_key = "wh3_dlc23_skill_chd_headdress_of_zharr",
            category_key = "character",
            indent = 0,
            tier = 7,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 7 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_fire_personal_0",
            skill_key = "wh3_dlc23_skill_chd_sorcerer_prophet_thirsty_for_magic",
            category_key = "character",
            indent = 1,
            tier = 0,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 11 },
            locked_node_keys = {
                "wh3_dlc23_skill_node_chd_sorcerer_prophet_death_personal_1",
                "wh3_dlc23_skill_node_chd_sorcerer_prophet_death_personal_2",
                "wh3_dlc23_skill_node_chd_sorcerer_prophet_fire_personal_1",
                "wh3_dlc23_skill_node_chd_sorcerer_prophet_fire_personal_2",
                "wh3_dlc23_skill_node_chd_sorcerer_prophet_hashut_personal_1",
                "wh3_dlc23_skill_node_chd_sorcerer_prophet_hashut_personal_2",
                "wh3_dlc23_skill_node_chd_sorcerer_prophet_metal_personal_1",
                "wh3_dlc23_skill_node_chd_sorcerer_prophet_metal_personal_2",
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_fire_personal_1",
            skill_key = "wh3_dlc23_skill_chd_sorcerer_prophet_flesh_sacrifice",
            category_key = "character",
            indent = 1,
            tier = 1,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 11 },
            locked_node_keys = {
                "wh3_dlc23_skill_node_chd_sorcerer_prophet_death_personal_0",
                "wh3_dlc23_skill_node_chd_sorcerer_prophet_death_personal_2",
                "wh3_dlc23_skill_node_chd_sorcerer_prophet_fire_personal_0",
                "wh3_dlc23_skill_node_chd_sorcerer_prophet_fire_personal_2",
                "wh3_dlc23_skill_node_chd_sorcerer_prophet_hashut_personal_0",
                "wh3_dlc23_skill_node_chd_sorcerer_prophet_hashut_personal_2",
                "wh3_dlc23_skill_node_chd_sorcerer_prophet_metal_personal_0",
                "wh3_dlc23_skill_node_chd_sorcerer_prophet_metal_personal_2",
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_fire_personal_2",
            skill_key = "wh3_dlc23_skill_chd_sorcerer_prophet_voice_of_hashut",
            category_key = "character",
            indent = 1,
            tier = 2,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 11 },
            locked_node_keys = {
                "wh3_dlc23_skill_node_chd_sorcerer_prophet_death_personal_0",
                "wh3_dlc23_skill_node_chd_sorcerer_prophet_death_personal_1",
                "wh3_dlc23_skill_node_chd_sorcerer_prophet_fire_personal_0",
                "wh3_dlc23_skill_node_chd_sorcerer_prophet_fire_personal_1",
                "wh3_dlc23_skill_node_chd_sorcerer_prophet_hashut_personal_0",
                "wh3_dlc23_skill_node_chd_sorcerer_prophet_hashut_personal_1",
                "wh3_dlc23_skill_node_chd_sorcerer_prophet_metal_personal_0",
                "wh3_dlc23_skill_node_chd_sorcerer_prophet_metal_personal_1",
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_fire_magic_0",
            skill_key = "wh_main_skill_all_magic_fire_01_fireball",
            category_key = "character",
            indent = 2,
            tier = 0,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_fire_magic_1_2",
            skill_key = "wh2_main_skill_all_magic_fire_02_cascading_fire-cloak_lord",
            category_key = "character",
            indent = 2,
            tier = 1,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_fire_magic_1_1",
            skill_key = "wh_main_skill_all_magic_fire_04_kindleflame",
            category_key = "character",
            indent = 2,
            tier = 2,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_fire_magic_1_3",
            skill_key = "wh2_main_skill_all_magic_fire_03_flaming_sword_of_rhuin_lord",
            category_key = "character",
            indent = 2,
            tier = 3,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_fire_magic_1_4",
            skill_key = "wh2_main_skill_all_magic_fire_05_the_burning_head_lord",
            category_key = "character",
            indent = 2,
            tier = 4,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_fire_magic_2",
            skill_key = "wh_main_skill_all_magic_all_06_evasion",
            category_key = "character",
            indent = 2,
            tier = 5,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_fire_magic_3_3",
            skill_key = "wh2_main_skill_all_magic_fire_09_piercing_bolts_of_burning_lord",
            category_key = "character",
            indent = 2,
            tier = 6,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_fire_magic_3_4",
            skill_key = "wh2_main_skill_all_magic_fire_10_flame_storm_lord",
            category_key = "character",
            indent = 2,
            tier = 7,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_fire_magic_3_1",
            skill_key = "wh_main_skill_all_magic_all_07_earthing",
            category_key = "character",
            indent = 2,
            tier = 8,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_fire_magic_3_2",
            skill_key = "wh_main_skill_all_magic_all_08_power_drain",
            category_key = "character",
            indent = 2,
            tier = 9,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_fire_magic_4",
            skill_key = "wh_main_skill_all_magic_all_11_arcane_conduit",
            category_key = "character",
            indent = 2,
            tier = 10,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_fire_magic_dummy",
            skill_key = "wh2_main_skill_all_magic_fire_dummy_fireball_cascading_fire_cloak",
            category_key = "character",
            indent = 2,
            tier = 11,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_fire_combat_0",
            skill_key = "wh3_dlc23_skill_chd_all_self_survivalist",
            category_key = "character",
            indent = 3,
            tier = 0,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_fire_combat_1_1",
            skill_key = "wh3_dlc23_skill_chd_lord_self_always_ready",
            category_key = "character",
            indent = 3,
            tier = 1,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_fire_combat_1_2",
            skill_key = "wh3_dlc23_skill_chd_lord_self_bandolier",
            category_key = "character",
            indent = 3,
            tier = 2,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_fire_combat_1_3",
            skill_key = "wh2_dlc11_skill_wef_lord_self_expeditious_endeavour",
            category_key = "character",
            indent = 3,
            tier = 3,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_fire_combat_1_4",
            skill_key = "wh3_dlc23_skill_chd_lord_self_piercing_shots",
            category_key = "character",
            indent = 3,
            tier = 4,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_fire_combat_2",
            skill_key = "wh_main_skill_all_all_self_foe-seeker",
            category_key = "character",
            indent = 3,
            tier = 5,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_fire_army_0",
            skill_key = "wh_main_skill_all_lord_battle_inspiring_presence",
            category_key = "battle",
            indent = 4,
            tier = 0,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_fire_army_1_1",
            skill_key = "wh3_dlc23_skill_chd_army_buff_melee_labourer_hobgoblin",
            category_key = "battle",
            indent = 4,
            tier = 1,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_fire_army_1_2",
            skill_key = "wh3_dlc23_skill_chd_army_buff_melee_chaos_dwarfs",
            category_key = "battle",
            indent = 4,
            tier = 2,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_fire_army_1_3",
            skill_key = "wh3_dlc23_skill_chd_army_buff_missiles",
            category_key = "battle",
            indent = 4,
            tier = 3,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_fire_army_1_4",
            skill_key = "wh3_dlc23_skill_chd_army_buff_artillery",
            category_key = "battle",
            indent = 4,
            tier = 4,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_fire_army_1_5",
            skill_key = "wh3_dlc23_skill_chd_army_buff_bull_centaurs",
            category_key = "battle",
            indent = 4,
            tier = 5,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_fire_army_1_6",
            skill_key = "wh3_dlc23_skill_chd_army_buff_monsters_kdaai_skullcracker",
            category_key = "battle",
            indent = 4,
            tier = 6,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_fire_army_2",
            skill_key = "wh_main_skill_all_lord_battle_rally",
            category_key = "battle",
            indent = 4,
            tier = 7,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_fire_army_3_1",
            skill_key = "wh3_dlc23_skill_chd_army_buff_labourer_hobgoblin_rank7",
            category_key = "battle",
            indent = 4,
            tier = 8,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_fire_army_3_2",
            skill_key = "wh3_dlc23_skill_chd_army_buff_melee_chaos_dwarfs_rank7",
            category_key = "battle",
            indent = 4,
            tier = 9,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_fire_army_3_3",
            skill_key = "wh3_dlc23_skill_chd_army_buff_artillery_chaos_dwarf_missiles_rank7",
            category_key = "battle",
            indent = 4,
            tier = 10,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_fire_army_3_4",
            skill_key = "wh3_dlc23_skill_chd_army_buff_monsters_kdaai_skullcracker_bull_centaurs_rank7",
            category_key = "battle",
            indent = 4,
            tier = 11,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_fire_army_4",
            skill_key = "wh_main_skill_chs_lord_battle_stand_or_die",
            category_key = "battle",
            indent = 4,
            tier = 12,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
    },
    wh3_dlc23_chd_sorcerer_prophet_hashut = {
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_hashut_mount_great_taurus",
            skill_key = "wh3_dlc23_skill_chd_sorcerer_prophet_hashut_mount_great_taurus",
            category_key = "character",
            indent = 0,
            tier = 0,
            max_level = 1,
            is_mount_skill = true,
            unlock_ranks_by_level = { 9 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_hashut_mount_lammasu",
            skill_key = "wh3_dlc23_skill_chd_sorcerer_prophet_hashut_mount_lammasu",
            category_key = "character",
            indent = 0,
            tier = 1,
            max_level = 1,
            is_mount_skill = true,
            unlock_ranks_by_level = { 14 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_hashut_mount_bale_taurus",
            skill_key = "wh3_dlc23_skill_chd_sorcerer_prophet_hashut_mount_bale_taurus",
            category_key = "character",
            indent = 0,
            tier = 2,
            max_level = 1,
            is_mount_skill = true,
            unlock_ranks_by_level = { 18 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_hashut_character_3",
            skill_key = "wh3_dlc23_skill_chd_unyielding_command",
            category_key = "character",
            indent = 0,
            tier = 3,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 7 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_hashut_character_4",
            skill_key = "wh3_dlc23_skill_chd_sorcerer_prophet_careful_casting",
            category_key = "character",
            indent = 0,
            tier = 4,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 16 },
            locked_node_keys = {
                "wh3_dlc23_skill_node_chd_sorcerer_prophet_death_character_5",
                "wh3_dlc23_skill_node_chd_sorcerer_prophet_fire_character_5",
                "wh3_dlc23_skill_node_chd_sorcerer_prophet_hashut_character_5",
                "wh3_dlc23_skill_node_chd_sorcerer_prophet_metal_character_5",
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_hashut_character_5",
            skill_key = "wh3_dlc23_skill_chd_sorcerer_prophet_sorcerers_curse",
            category_key = "character",
            indent = 0,
            tier = 5,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 16 },
            locked_node_keys = {
                "wh3_dlc23_skill_node_chd_sorcerer_prophet_death_character_4",
                "wh3_dlc23_skill_node_chd_sorcerer_prophet_fire_character_4",
                "wh3_dlc23_skill_node_chd_sorcerer_prophet_hashut_character_4",
                "wh3_dlc23_skill_node_chd_sorcerer_prophet_metal_character_4",
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_hashut_character_6",
            skill_key = "wh3_dlc23_skill_chd_hashuts_scales",
            category_key = "character",
            indent = 0,
            tier = 6,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 7 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_hashut_character_7",
            skill_key = "wh3_dlc23_skill_chd_headdress_of_zharr",
            category_key = "character",
            indent = 0,
            tier = 7,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 7 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_hashut_personal_0",
            skill_key = "wh3_dlc23_skill_chd_sorcerer_prophet_thirsty_for_magic",
            category_key = "character",
            indent = 1,
            tier = 0,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 11 },
            locked_node_keys = {
                "wh3_dlc23_skill_node_chd_sorcerer_prophet_death_personal_1",
                "wh3_dlc23_skill_node_chd_sorcerer_prophet_death_personal_2",
                "wh3_dlc23_skill_node_chd_sorcerer_prophet_fire_personal_1",
                "wh3_dlc23_skill_node_chd_sorcerer_prophet_fire_personal_2",
                "wh3_dlc23_skill_node_chd_sorcerer_prophet_hashut_personal_1",
                "wh3_dlc23_skill_node_chd_sorcerer_prophet_hashut_personal_2",
                "wh3_dlc23_skill_node_chd_sorcerer_prophet_metal_personal_1",
                "wh3_dlc23_skill_node_chd_sorcerer_prophet_metal_personal_2",
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_hashut_personal_1",
            skill_key = "wh3_dlc23_skill_chd_sorcerer_prophet_flesh_sacrifice",
            category_key = "character",
            indent = 1,
            tier = 1,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 11 },
            locked_node_keys = {
                "wh3_dlc23_skill_node_chd_sorcerer_prophet_death_personal_0",
                "wh3_dlc23_skill_node_chd_sorcerer_prophet_death_personal_2",
                "wh3_dlc23_skill_node_chd_sorcerer_prophet_fire_personal_0",
                "wh3_dlc23_skill_node_chd_sorcerer_prophet_fire_personal_2",
                "wh3_dlc23_skill_node_chd_sorcerer_prophet_hashut_personal_0",
                "wh3_dlc23_skill_node_chd_sorcerer_prophet_hashut_personal_2",
                "wh3_dlc23_skill_node_chd_sorcerer_prophet_metal_personal_0",
                "wh3_dlc23_skill_node_chd_sorcerer_prophet_metal_personal_2",
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_hashut_personal_2",
            skill_key = "wh3_dlc23_skill_chd_sorcerer_prophet_voice_of_hashut",
            category_key = "character",
            indent = 1,
            tier = 2,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 11 },
            locked_node_keys = {
                "wh3_dlc23_skill_node_chd_sorcerer_prophet_death_personal_0",
                "wh3_dlc23_skill_node_chd_sorcerer_prophet_death_personal_1",
                "wh3_dlc23_skill_node_chd_sorcerer_prophet_fire_personal_0",
                "wh3_dlc23_skill_node_chd_sorcerer_prophet_fire_personal_1",
                "wh3_dlc23_skill_node_chd_sorcerer_prophet_hashut_personal_0",
                "wh3_dlc23_skill_node_chd_sorcerer_prophet_hashut_personal_1",
                "wh3_dlc23_skill_node_chd_sorcerer_prophet_metal_personal_0",
                "wh3_dlc23_skill_node_chd_sorcerer_prophet_metal_personal_1",
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_hashut_magic_0",
            skill_key = "wh3_dlc23_skill_chd_magic_hashut_01_burning_wrath_lord",
            category_key = "character",
            indent = 2,
            tier = 0,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_hashut_magic_1_2",
            skill_key = "wh3_dlc23_skill_chd_magic_hashut_03_killing_fire",
            category_key = "character",
            indent = 2,
            tier = 1,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_hashut_magic_1_1",
            skill_key = "wh3_dlc23_skill_chd_magic_hashut_02_dark_subjugation_lord",
            category_key = "character",
            indent = 2,
            tier = 2,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_hashut_magic_1_3",
            skill_key = "wh3_dlc23_skill_chd_magic_hashut_04_ash_storm_lord",
            category_key = "character",
            indent = 2,
            tier = 3,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_hashut_magic_1_4",
            skill_key = "wh3_dlc23_skill_chd_magic_hashut_05_curse_of_hashut_lord",
            category_key = "character",
            indent = 2,
            tier = 4,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_hashut_magic_2",
            skill_key = "wh_main_skill_all_magic_all_06_evasion",
            category_key = "character",
            indent = 2,
            tier = 5,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_hashut_magic_3_3",
            skill_key = "wh3_dlc23_skill_chd_magic_hashut_06_hell_hammer_lord",
            category_key = "character",
            indent = 2,
            tier = 6,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_hashut_magic_3_4",
            skill_key = "wh3_dlc23_skill_chd_magic_hashut_07_flames_of_azgorh_lord",
            category_key = "character",
            indent = 2,
            tier = 7,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_hashut_magic_3_1",
            skill_key = "wh_main_skill_all_magic_all_07_earthing",
            category_key = "character",
            indent = 2,
            tier = 8,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_hashut_magic_3_2",
            skill_key = "wh_main_skill_all_magic_all_08_power_drain",
            category_key = "character",
            indent = 2,
            tier = 9,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_hashut_magic_4",
            skill_key = "wh_main_skill_all_magic_all_11_arcane_conduit",
            category_key = "character",
            indent = 2,
            tier = 10,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_hashut_magic_dummy",
            skill_key = "wh3_dlc23_skill_chd_magic_hashut_dummy_burning_wrath_dark_subjugation",
            category_key = "character",
            indent = 2,
            tier = 11,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_hashut_combat_0",
            skill_key = "wh3_dlc23_skill_chd_all_self_survivalist",
            category_key = "character",
            indent = 3,
            tier = 0,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_hashut_combat_1_1",
            skill_key = "wh3_dlc23_skill_chd_lord_self_always_ready",
            category_key = "character",
            indent = 3,
            tier = 1,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_hashut_combat_1_2",
            skill_key = "wh3_dlc23_skill_chd_lord_self_bandolier",
            category_key = "character",
            indent = 3,
            tier = 2,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_hashut_combat_1_3",
            skill_key = "wh2_dlc11_skill_wef_lord_self_expeditious_endeavour",
            category_key = "character",
            indent = 3,
            tier = 3,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_hashut_combat_1_4",
            skill_key = "wh3_dlc23_skill_chd_lord_self_piercing_shots",
            category_key = "character",
            indent = 3,
            tier = 4,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_hashut_combat_2",
            skill_key = "wh_main_skill_all_all_self_foe-seeker",
            category_key = "character",
            indent = 3,
            tier = 5,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_hashut_army_0",
            skill_key = "wh_main_skill_all_lord_battle_inspiring_presence",
            category_key = "battle",
            indent = 4,
            tier = 0,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_hashut_army_1_1",
            skill_key = "wh3_dlc23_skill_chd_army_buff_melee_labourer_hobgoblin",
            category_key = "battle",
            indent = 4,
            tier = 1,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_hashut_army_1_2",
            skill_key = "wh3_dlc23_skill_chd_army_buff_melee_chaos_dwarfs",
            category_key = "battle",
            indent = 4,
            tier = 2,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_hashut_army_1_3",
            skill_key = "wh3_dlc23_skill_chd_army_buff_missiles",
            category_key = "battle",
            indent = 4,
            tier = 3,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_hashut_army_1_4",
            skill_key = "wh3_dlc23_skill_chd_army_buff_artillery",
            category_key = "battle",
            indent = 4,
            tier = 4,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_hashut_army_1_5",
            skill_key = "wh3_dlc23_skill_chd_army_buff_bull_centaurs",
            category_key = "battle",
            indent = 4,
            tier = 5,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_hashut_army_1_6",
            skill_key = "wh3_dlc23_skill_chd_army_buff_monsters_kdaai_skullcracker",
            category_key = "battle",
            indent = 4,
            tier = 6,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_hashut_army_2",
            skill_key = "wh_main_skill_all_lord_battle_rally",
            category_key = "battle",
            indent = 4,
            tier = 7,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_hashut_army_3_1",
            skill_key = "wh3_dlc23_skill_chd_army_buff_labourer_hobgoblin_rank7",
            category_key = "battle",
            indent = 4,
            tier = 8,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_hashut_army_3_2",
            skill_key = "wh3_dlc23_skill_chd_army_buff_melee_chaos_dwarfs_rank7",
            category_key = "battle",
            indent = 4,
            tier = 9,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_hashut_army_3_3",
            skill_key = "wh3_dlc23_skill_chd_army_buff_artillery_chaos_dwarf_missiles_rank7",
            category_key = "battle",
            indent = 4,
            tier = 10,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_hashut_army_3_4",
            skill_key = "wh3_dlc23_skill_chd_army_buff_monsters_kdaai_skullcracker_bull_centaurs_rank7",
            category_key = "battle",
            indent = 4,
            tier = 11,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_hashut_army_4",
            skill_key = "wh_main_skill_chs_lord_battle_stand_or_die",
            category_key = "battle",
            indent = 4,
            tier = 12,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
    },
    wh3_dlc23_chd_sorcerer_prophet_metal = {
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_metal_mount_great_taurus",
            skill_key = "wh3_dlc23_skill_chd_sorcerer_prophet_metal_mount_great_taurus",
            category_key = "character",
            indent = 0,
            tier = 0,
            max_level = 1,
            is_mount_skill = true,
            unlock_ranks_by_level = { 9 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_metal_mount_lammasu",
            skill_key = "wh3_dlc23_skill_chd_sorcerer_prophet_metal_mount_lammasu",
            category_key = "character",
            indent = 0,
            tier = 1,
            max_level = 1,
            is_mount_skill = true,
            unlock_ranks_by_level = { 14 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_metal_mount_bale_taurus",
            skill_key = "wh3_dlc23_skill_chd_sorcerer_prophet_metal_mount_bale_taurus",
            category_key = "character",
            indent = 0,
            tier = 2,
            max_level = 1,
            is_mount_skill = true,
            unlock_ranks_by_level = { 18 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_metal_character_3",
            skill_key = "wh3_dlc23_skill_chd_unyielding_command",
            category_key = "character",
            indent = 0,
            tier = 3,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 7 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_metal_character_4",
            skill_key = "wh3_dlc23_skill_chd_sorcerer_prophet_careful_casting",
            category_key = "character",
            indent = 0,
            tier = 4,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 16 },
            locked_node_keys = {
                "wh3_dlc23_skill_node_chd_sorcerer_prophet_death_character_5",
                "wh3_dlc23_skill_node_chd_sorcerer_prophet_fire_character_5",
                "wh3_dlc23_skill_node_chd_sorcerer_prophet_hashut_character_5",
                "wh3_dlc23_skill_node_chd_sorcerer_prophet_metal_character_5",
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_metal_character_5",
            skill_key = "wh3_dlc23_skill_chd_sorcerer_prophet_sorcerers_curse",
            category_key = "character",
            indent = 0,
            tier = 5,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 16 },
            locked_node_keys = {
                "wh3_dlc23_skill_node_chd_sorcerer_prophet_death_character_4",
                "wh3_dlc23_skill_node_chd_sorcerer_prophet_fire_character_4",
                "wh3_dlc23_skill_node_chd_sorcerer_prophet_hashut_character_4",
                "wh3_dlc23_skill_node_chd_sorcerer_prophet_metal_character_4",
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_metal_character_6",
            skill_key = "wh3_dlc23_skill_chd_hashuts_scales",
            category_key = "character",
            indent = 0,
            tier = 6,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 7 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_metal_character_7",
            skill_key = "wh3_dlc23_skill_chd_headdress_of_zharr",
            category_key = "character",
            indent = 0,
            tier = 7,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 7 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_metal_personal_0",
            skill_key = "wh3_dlc23_skill_chd_sorcerer_prophet_thirsty_for_magic",
            category_key = "character",
            indent = 1,
            tier = 0,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 11 },
            locked_node_keys = {
                "wh3_dlc23_skill_node_chd_sorcerer_prophet_death_personal_1",
                "wh3_dlc23_skill_node_chd_sorcerer_prophet_death_personal_2",
                "wh3_dlc23_skill_node_chd_sorcerer_prophet_fire_personal_1",
                "wh3_dlc23_skill_node_chd_sorcerer_prophet_fire_personal_2",
                "wh3_dlc23_skill_node_chd_sorcerer_prophet_hashut_personal_1",
                "wh3_dlc23_skill_node_chd_sorcerer_prophet_hashut_personal_2",
                "wh3_dlc23_skill_node_chd_sorcerer_prophet_metal_personal_1",
                "wh3_dlc23_skill_node_chd_sorcerer_prophet_metal_personal_2",
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_metal_personal_1",
            skill_key = "wh3_dlc23_skill_chd_sorcerer_prophet_flesh_sacrifice",
            category_key = "character",
            indent = 1,
            tier = 1,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 11 },
            locked_node_keys = {
                "wh3_dlc23_skill_node_chd_sorcerer_prophet_death_personal_0",
                "wh3_dlc23_skill_node_chd_sorcerer_prophet_death_personal_2",
                "wh3_dlc23_skill_node_chd_sorcerer_prophet_fire_personal_0",
                "wh3_dlc23_skill_node_chd_sorcerer_prophet_fire_personal_2",
                "wh3_dlc23_skill_node_chd_sorcerer_prophet_hashut_personal_0",
                "wh3_dlc23_skill_node_chd_sorcerer_prophet_hashut_personal_2",
                "wh3_dlc23_skill_node_chd_sorcerer_prophet_metal_personal_0",
                "wh3_dlc23_skill_node_chd_sorcerer_prophet_metal_personal_2",
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_metal_personal_2",
            skill_key = "wh3_dlc23_skill_chd_sorcerer_prophet_voice_of_hashut",
            category_key = "character",
            indent = 1,
            tier = 2,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 11 },
            locked_node_keys = {
                "wh3_dlc23_skill_node_chd_sorcerer_prophet_death_personal_0",
                "wh3_dlc23_skill_node_chd_sorcerer_prophet_death_personal_1",
                "wh3_dlc23_skill_node_chd_sorcerer_prophet_fire_personal_0",
                "wh3_dlc23_skill_node_chd_sorcerer_prophet_fire_personal_1",
                "wh3_dlc23_skill_node_chd_sorcerer_prophet_hashut_personal_0",
                "wh3_dlc23_skill_node_chd_sorcerer_prophet_hashut_personal_1",
                "wh3_dlc23_skill_node_chd_sorcerer_prophet_metal_personal_0",
                "wh3_dlc23_skill_node_chd_sorcerer_prophet_metal_personal_1",
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_metal_magic_0",
            skill_key = "wh_main_skill_all_magic_metal_01_searing_doom",
            category_key = "character",
            indent = 2,
            tier = 0,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_metal_magic_1_2",
            skill_key = "wh2_main_skill_all_magic_metal_02_plague_of_rust_lord",
            category_key = "character",
            indent = 2,
            tier = 1,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_metal_magic_1_1",
            skill_key = "wh_main_skill_all_magic_metal_03_metalshifting",
            category_key = "character",
            indent = 2,
            tier = 2,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_metal_magic_1_3",
            skill_key = "wh2_main_skill_all_magic_metal_04_glittering_robe_lord",
            category_key = "character",
            indent = 2,
            tier = 3,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_metal_magic_1_4",
            skill_key = "wh2_main_skill_all_magic_metal_05_gehennas_golden_hounds_lord",
            category_key = "character",
            indent = 2,
            tier = 4,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_metal_magic_2",
            skill_key = "wh_main_skill_all_magic_all_06_evasion",
            category_key = "character",
            indent = 2,
            tier = 5,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_metal_magic_3_3",
            skill_key = "wh2_main_skill_all_magic_metal_09_transmutation_of_lead_lord",
            category_key = "character",
            indent = 2,
            tier = 6,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_metal_magic_3_4",
            skill_key = "wh2_main_skill_all_magic_metal_10_final_transmutation_lord",
            category_key = "character",
            indent = 2,
            tier = 7,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_metal_magic_3_1",
            skill_key = "wh_main_skill_all_magic_all_07_earthing",
            category_key = "character",
            indent = 2,
            tier = 8,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_metal_magic_3_2",
            skill_key = "wh_main_skill_all_magic_all_08_power_drain",
            category_key = "character",
            indent = 2,
            tier = 9,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_metal_magic_4",
            skill_key = "wh_main_skill_all_magic_all_11_arcane_conduit",
            category_key = "character",
            indent = 2,
            tier = 10,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_metal_magic_dummy",
            skill_key = "wh2_main_skill_all_magic_metal_dummy_searing_doom_plague_of_rust",
            category_key = "character",
            indent = 2,
            tier = 11,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_metal_combat_0",
            skill_key = "wh3_dlc23_skill_chd_all_self_survivalist",
            category_key = "character",
            indent = 3,
            tier = 0,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_metal_combat_1_1",
            skill_key = "wh3_dlc23_skill_chd_lord_self_always_ready",
            category_key = "character",
            indent = 3,
            tier = 1,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_metal_combat_1_2",
            skill_key = "wh3_dlc23_skill_chd_lord_self_bandolier",
            category_key = "character",
            indent = 3,
            tier = 2,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_metal_combat_1_3",
            skill_key = "wh2_dlc11_skill_wef_lord_self_expeditious_endeavour",
            category_key = "character",
            indent = 3,
            tier = 3,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_metal_combat_1_4",
            skill_key = "wh3_dlc23_skill_chd_lord_self_piercing_shots",
            category_key = "character",
            indent = 3,
            tier = 4,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_metal_combat_2",
            skill_key = "wh_main_skill_all_all_self_foe-seeker",
            category_key = "character",
            indent = 3,
            tier = 5,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_metal_army_0",
            skill_key = "wh_main_skill_all_lord_battle_inspiring_presence",
            category_key = "battle",
            indent = 4,
            tier = 0,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_metal_army_1_1",
            skill_key = "wh3_dlc23_skill_chd_army_buff_melee_labourer_hobgoblin",
            category_key = "battle",
            indent = 4,
            tier = 1,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_metal_army_1_2",
            skill_key = "wh3_dlc23_skill_chd_army_buff_melee_chaos_dwarfs",
            category_key = "battle",
            indent = 4,
            tier = 2,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_metal_army_1_3",
            skill_key = "wh3_dlc23_skill_chd_army_buff_missiles",
            category_key = "battle",
            indent = 4,
            tier = 3,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_metal_army_1_4",
            skill_key = "wh3_dlc23_skill_chd_army_buff_artillery",
            category_key = "battle",
            indent = 4,
            tier = 4,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_metal_army_1_5",
            skill_key = "wh3_dlc23_skill_chd_army_buff_bull_centaurs",
            category_key = "battle",
            indent = 4,
            tier = 5,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_metal_army_1_6",
            skill_key = "wh3_dlc23_skill_chd_army_buff_monsters_kdaai_skullcracker",
            category_key = "battle",
            indent = 4,
            tier = 6,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_metal_army_2",
            skill_key = "wh_main_skill_all_lord_battle_rally",
            category_key = "battle",
            indent = 4,
            tier = 7,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_metal_army_3_1",
            skill_key = "wh3_dlc23_skill_chd_army_buff_labourer_hobgoblin_rank7",
            category_key = "battle",
            indent = 4,
            tier = 8,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_metal_army_3_2",
            skill_key = "wh3_dlc23_skill_chd_army_buff_melee_chaos_dwarfs_rank7",
            category_key = "battle",
            indent = 4,
            tier = 9,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_metal_army_3_3",
            skill_key = "wh3_dlc23_skill_chd_army_buff_artillery_chaos_dwarf_missiles_rank7",
            category_key = "battle",
            indent = 4,
            tier = 10,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_metal_army_3_4",
            skill_key = "wh3_dlc23_skill_chd_army_buff_monsters_kdaai_skullcracker_bull_centaurs_rank7",
            category_key = "battle",
            indent = 4,
            tier = 11,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc23_skill_node_chd_sorcerer_prophet_metal_army_4",
            skill_key = "wh_main_skill_chs_lord_battle_stand_or_die",
            category_key = "battle",
            indent = 4,
            tier = 12,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
    },
}

return data
