local data = {}

-- AUTO-GENERATED by tools/adamrogue/generate_stage_d_data.py.
data.STARTING_NODE_KEY = "cathay"

data.NODE_POOL = {
    {
        node_key = "cathay",
        faction_key = "wh3_main_cth_the_northern_provinces",
        culture_key = "wh3_main_cth_cathay",
        display_name_key = "adamrogue_destination_node_name_cathay",
        choice_text_key = "adamrogue_destination_node_choice_cathay",
        enabled = true
    },
    {
        node_key = "kislev",
        faction_key = "wh3_main_ksl_the_ice_court",
        culture_key = "wh3_main_ksl_kislev",
        display_name_key = "adamrogue_destination_node_name_kislev",
        choice_text_key = "adamrogue_destination_node_choice_kislev",
        enabled = true
    },
    {
        node_key = "ogres",
        faction_key = "wh3_main_ogr_disciples_of_the_maw",
        culture_key = "wh3_main_ogr_ogre_kingdoms",
        display_name_key = "adamrogue_destination_node_name_ogres",
        choice_text_key = "adamrogue_destination_node_choice_ogres",
        enabled = true
    },
    {
        node_key = "khorne",
        faction_key = "wh3_main_kho_exiles_of_khorne",
        culture_key = "wh3_main_kho_khorne",
        display_name_key = "adamrogue_destination_node_name_khorne",
        choice_text_key = "adamrogue_destination_node_choice_khorne",
        enabled = true
    },
    {
        node_key = "nurgle",
        faction_key = "wh3_main_nur_poxmakers_of_nurgle",
        culture_key = "wh3_main_nur_nurgle",
        display_name_key = "adamrogue_destination_node_name_nurgle",
        choice_text_key = "adamrogue_destination_node_choice_nurgle",
        enabled = true
    },
    {
        node_key = "tzeentch",
        faction_key = "wh3_main_tze_oracles_of_tzeentch",
        culture_key = "wh3_main_tze_tzeentch",
        display_name_key = "adamrogue_destination_node_name_tzeentch",
        choice_text_key = "adamrogue_destination_node_choice_tzeentch",
        enabled = true
    },
    {
        node_key = "slaanesh",
        faction_key = "wh3_main_sla_seducers_of_slaanesh",
        culture_key = "wh3_main_sla_slaanesh",
        display_name_key = "adamrogue_destination_node_name_slaanesh",
        choice_text_key = "adamrogue_destination_node_choice_slaanesh",
        enabled = true
    },
    {
        node_key = "chaos_dwarfs",
        faction_key = "wh3_dlc23_chd_astragoth",
        culture_key = "wh3_dlc23_chd_chaos_dwarfs",
        display_name_key = "adamrogue_destination_node_name_chaos_dwarfs",
        choice_text_key = "adamrogue_destination_node_choice_chaos_dwarfs",
        enabled = true
    },
    {
        node_key = "empire",
        faction_key = "wh_main_emp_empire",
        culture_key = "wh_main_emp_empire",
        display_name_key = "adamrogue_destination_node_name_empire",
        choice_text_key = "adamrogue_destination_node_choice_empire",
        enabled = true
    },
    {
        node_key = "dwarfs",
        faction_key = "wh_main_dwf_dwarfs",
        culture_key = "wh_main_dwf_dwarfs",
        display_name_key = "adamrogue_destination_node_name_dwarfs",
        choice_text_key = "adamrogue_destination_node_choice_dwarfs",
        enabled = true
    },
    {
        node_key = "greenskins",
        faction_key = "wh_main_grn_greenskins",
        culture_key = "wh_main_grn_greenskins",
        display_name_key = "adamrogue_destination_node_name_greenskins",
        choice_text_key = "adamrogue_destination_node_choice_greenskins",
        enabled = true
    },
    {
        node_key = "vampire_counts",
        faction_key = "wh_main_vmp_schwartzhafen",
        culture_key = "wh_main_vmp_vampire_counts",
        display_name_key = "adamrogue_destination_node_name_vampire_counts",
        choice_text_key = "adamrogue_destination_node_choice_vampire_counts",
        enabled = true
    },
    {
        node_key = "bretonnia",
        faction_key = "wh_main_brt_bretonnia",
        culture_key = "wh_main_brt_bretonnia",
        display_name_key = "adamrogue_destination_node_name_bretonnia",
        choice_text_key = "adamrogue_destination_node_choice_bretonnia",
        enabled = true
    },
    {
        node_key = "warriors_of_chaos",
        faction_key = "wh_main_chs_chaos",
        culture_key = "wh_main_chs_chaos",
        display_name_key = "adamrogue_destination_node_name_warriors_of_chaos",
        choice_text_key = "adamrogue_destination_node_choice_warriors_of_chaos",
        enabled = true
    },
    {
        node_key = "beastmen",
        faction_key = "wh_dlc03_bst_beastmen",
        culture_key = "wh_dlc03_bst_beastmen",
        display_name_key = "adamrogue_destination_node_name_beastmen",
        choice_text_key = "adamrogue_destination_node_choice_beastmen",
        enabled = true
    },
    {
        node_key = "wood_elves",
        faction_key = "wh_dlc05_wef_argwylon",
        culture_key = "wh_dlc05_wef_wood_elves",
        display_name_key = "adamrogue_destination_node_name_wood_elves",
        choice_text_key = "adamrogue_destination_node_choice_wood_elves",
        enabled = true
    },
    {
        node_key = "norsca",
        faction_key = "wh_dlc08_nor_norsca",
        culture_key = "wh_dlc08_nor_norsca",
        display_name_key = "adamrogue_destination_node_name_norsca",
        choice_text_key = "adamrogue_destination_node_choice_norsca",
        enabled = true
    },
    {
        node_key = "high_elves",
        faction_key = "wh2_main_hef_eataine",
        culture_key = "wh2_main_hef_high_elves",
        display_name_key = "adamrogue_destination_node_name_high_elves",
        choice_text_key = "adamrogue_destination_node_choice_high_elves",
        enabled = true
    },
    {
        node_key = "dark_elves",
        faction_key = "wh2_main_def_naggarond",
        culture_key = "wh2_main_def_dark_elves",
        display_name_key = "adamrogue_destination_node_name_dark_elves",
        choice_text_key = "adamrogue_destination_node_choice_dark_elves",
        enabled = true
    },
    {
        node_key = "lizardmen",
        faction_key = "wh2_main_lzd_hexoatl",
        culture_key = "wh2_main_lzd_lizardmen",
        display_name_key = "adamrogue_destination_node_name_lizardmen",
        choice_text_key = "adamrogue_destination_node_choice_lizardmen",
        enabled = true
    },
    {
        node_key = "skaven",
        faction_key = "wh2_main_skv_clan_mors",
        culture_key = "wh2_main_skv_skaven",
        display_name_key = "adamrogue_destination_node_name_skaven",
        choice_text_key = "adamrogue_destination_node_choice_skaven",
        enabled = true
    },
    {
        node_key = "tomb_kings",
        faction_key = "wh2_dlc09_tmb_khemri",
        culture_key = "wh2_dlc09_tmb_tomb_kings",
        display_name_key = "adamrogue_destination_node_name_tomb_kings",
        choice_text_key = "adamrogue_destination_node_choice_tomb_kings",
        enabled = true
    },
    {
        node_key = "vampire_coast",
        faction_key = "wh2_dlc11_cst_noctilus",
        culture_key = "wh2_dlc11_cst_vampire_coast",
        display_name_key = "adamrogue_destination_node_name_vampire_coast",
        choice_text_key = "adamrogue_destination_node_choice_vampire_coast",
        enabled = true
    },
    {
        node_key = "daemons_of_chaos",
        faction_key = "wh3_main_dae_daemon_prince",
        culture_key = "wh3_main_dae_daemons",
        display_name_key = "adamrogue_destination_node_name_daemons_of_chaos",
        choice_text_key = "adamrogue_destination_node_choice_daemons_of_chaos",
        enabled = true
    },
}

return data
