local data = {}

-- AUTO-GENERATED by tools/adamrogue/generate_stage_d_data.py.
data.CONTENT_FACTION_KEY = "wh3_main_ksl_the_ice_court"

data.CHARACTER_SKILL_PLANS_BY_SUBTYPE = {
    wh3_dlc24_ksl_druzhina = {
        {
            node_key = "wh3_dlc24_skill_node_ksl_druzhina_mount_warhorse",
            skill_key = "wh3_dlc24_skill_ksl_druzhina_unique_warhorse",
            category_key = "character",
            indent = 0,
            tier = 0,
            max_level = 1,
            is_mount_skill = true,
            unlock_ranks_by_level = { 7 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc24_skill_node_ksl_druzhina_special_01",
            skill_key = "wh3_dlc23_skill_all_all_self_restock",
            category_key = "character",
            indent = 0,
            tier = 1,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_skill_node_ksl_boyar_unique_03",
            skill_key = "wh3_main_skill_ksl_all_unique_missile_resist",
            category_key = "character",
            indent = 0,
            tier = 2,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 6 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_skill_node_ksl_boyar_unique_04",
            skill_key = "wh_main_skill_all_lord_battle_brass-lunged",
            category_key = "character",
            indent = 0,
            tier = 3,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 3 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc24_skill_node_ksl_druzhina_choice_01",
            skill_key = "wh3_dlc24_skill_ksl_druzhina_choice_1",
            category_key = "character",
            indent = 1,
            tier = 7,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 9 },
            locked_node_keys = {
                "wh3_dlc24_skill_node_ksl_druzhina_choice_02",
                "wh3_dlc24_skill_node_ksl_druzhina_choice_03",
            }
        },
        {
            node_key = "wh3_dlc24_skill_node_ksl_druzhina_choice_02",
            skill_key = "wh3_dlc24_skill_ksl_druzhina_choice_2",
            category_key = "character",
            indent = 1,
            tier = 8,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 9 },
            locked_node_keys = {
                "wh3_dlc24_skill_node_ksl_druzhina_choice_01",
                "wh3_dlc24_skill_node_ksl_druzhina_choice_03",
            }
        },
        {
            node_key = "wh3_dlc24_skill_node_ksl_druzhina_choice_03",
            skill_key = "wh3_dlc24_skill_ksl_druzhina_choice_3",
            category_key = "character",
            indent = 1,
            tier = 9,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 9 },
            locked_node_keys = {
                "wh3_dlc24_skill_node_ksl_druzhina_choice_01",
                "wh3_dlc24_skill_node_ksl_druzhina_choice_02",
            }
        },
        {
            node_key = "wh3_dlc24_skill_node_ksl_druzhina_unique_01",
            skill_key = "wh3_dlc24_skill_ksl_druzhina_unique_taals_judgment",
            category_key = "character",
            indent = 2,
            tier = 1,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 11 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc24_skill_node_ksl_druzhina_unique_02",
            skill_key = "wh3_dlc24_skill_ksl_druzhina_unique_2",
            category_key = "character",
            indent = 2,
            tier = 2,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc24_skill_node_ksl_druzhina_unique_02_ostankya",
            skill_key = "wh3_dlc24_skill_ksl_druzhina_unique_2_ostankya",
            category_key = "character",
            indent = 2,
            tier = 2,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc24_skill_node_ksl_druzhina_unique_03",
            skill_key = "wh3_dlc24_skill_ksl_druzhina_unique_3",
            category_key = "character",
            indent = 2,
            tier = 3,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc24_skill_node_ksl_druzhina_unique_04",
            skill_key = "wh3_dlc24_skill_ksl_druzhina_unique_4",
            category_key = "character",
            indent = 2,
            tier = 4,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc24_skill_node_ksl_druzhina_unique_05",
            skill_key = "wh3_dlc24_skill_ksl_druzhina_unique_5",
            category_key = "character",
            indent = 2,
            tier = 5,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc24_skill_node_ksl_druzhina_combat_0",
            skill_key = "wh_main_skill_all_all_self_hard_to_hit_starter",
            category_key = "character",
            indent = 3,
            tier = 0,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc24_skill_node_ksl_druzhina_combat_1_1",
            skill_key = "wh2_dlc11_skill_all_lord_self_deadeye",
            category_key = "character",
            indent = 3,
            tier = 1,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc24_skill_node_ksl_druzhina_combat_1_2",
            skill_key = "wh2_dlc11_skill_all_lord_self_full_plate_armour",
            category_key = "character",
            indent = 3,
            tier = 2,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc24_skill_node_ksl_druzhina_combat_1_3",
            skill_key = "wh2_dlc11_skill_all_lord_self_scarred_veteran",
            category_key = "character",
            indent = 3,
            tier = 3,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc24_skill_node_ksl_druzhina_combat_1_4",
            skill_key = "wh2_dlc11_skill_all_lord_self_deadly_blade",
            category_key = "character",
            indent = 3,
            tier = 4,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc24_skill_node_ksl_druzhina_combat_2",
            skill_key = "wh3_dlc24_skill_ksl_druzhina_self_cursed_frontier",
            category_key = "character",
            indent = 3,
            tier = 5,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc24_skill_node_ksl_druzhina_combat_3_1",
            skill_key = "wh2_dlc11_skill_all_lord_self_wound-maker",
            category_key = "character",
            indent = 3,
            tier = 6,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc24_skill_node_ksl_druzhina_combat_3_2",
            skill_key = "wh2_dlc11_skill_all_lord_self_blade_master",
            category_key = "character",
            indent = 3,
            tier = 7,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc24_skill_node_ksl_druzhina_combat_3_3",
            skill_key = "wh2_dlc11_skill_all_lord_self_self_indomitable",
            category_key = "character",
            indent = 3,
            tier = 8,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc24_skill_node_ksl_druzhina_combat_3_4",
            skill_key = "wh2_dlc13_skill_emp_hunts_marshal_ranged_3",
            category_key = "character",
            indent = 3,
            tier = 9,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc24_skill_node_ksl_druzhina_combat_4",
            skill_key = "wh2_main_skill_hef_alastar_unique_heroic_killing_blow",
            category_key = "character",
            indent = 3,
            tier = 10,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_skill_node_ksl_boyar_army_0",
            skill_key = "wh_main_skill_all_lord_battle_inspiring_presence",
            category_key = "battle",
            indent = 4,
            tier = 0,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_skill_node_ksl_boyar_army_1_1",
            skill_key = "wh3_main_skill_ksl_army_buff_kossars_streltsi",
            category_key = "battle",
            indent = 4,
            tier = 1,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_skill_node_ksl_boyar_army_1_3",
            skill_key = "wh3_main_skill_ksl_army_buff_elite_infantry",
            category_key = "battle",
            indent = 4,
            tier = 2,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_skill_node_ksl_boyar_army_1_4",
            skill_key = "wh3_main_skill_ksl_army_buff_heavy_cavalry",
            category_key = "battle",
            indent = 4,
            tier = 3,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_skill_node_ksl_boyar_army_1_5",
            skill_key = "wh3_main_skill_ksl_army_buff_monsters",
            category_key = "battle",
            indent = 4,
            tier = 4,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_skill_node_ksl_boyar_army_1_6",
            skill_key = "wh3_main_skill_ksl_army_buff_war_machines",
            category_key = "battle",
            indent = 4,
            tier = 5,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_skill_node_ksl_boyar_army_2",
            skill_key = "wh_main_skill_all_lord_battle_rally",
            category_key = "battle",
            indent = 4,
            tier = 6,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_skill_node_ksl_boyar_army_3_1",
            skill_key = "wh3_main_skill_ksl_army_buff_kossars_streltsi_ice_guard_rank_7",
            category_key = "battle",
            indent = 4,
            tier = 7,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_skill_node_ksl_boyar_army_3_2",
            skill_key = "wh3_main_skill_ksl_army_buff_cavalry_rank_7",
            category_key = "battle",
            indent = 4,
            tier = 8,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_skill_node_ksl_boyar_army_3_3",
            skill_key = "wh3_main_skill_ksl_army_buff_bears_tsar_guard_rank_7",
            category_key = "battle",
            indent = 4,
            tier = 9,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_skill_node_ksl_boyar_army_3_4",
            skill_key = "wh3_main_skill_ksl_army_buff_war_machines_rank_7",
            category_key = "battle",
            indent = 4,
            tier = 10,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_skill_node_ksl_boyar_army_4",
            skill_key = "wh_main_skill_all_lord_battle_stand_your_ground",
            category_key = "battle",
            indent = 4,
            tier = 11,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
    },
    wh3_main_ksl_boyar = {
        {
            node_key = "wh3_main_skill_node_ksl_boyar_unique_01",
            skill_key = "wh3_main_skill_ksl_boyar_unique_warhorse",
            category_key = "character",
            indent = 0,
            tier = 0,
            max_level = 1,
            is_mount_skill = true,
            unlock_ranks_by_level = { 4 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_skill_node_ksl_boyar_unique_02",
            skill_key = "wh3_main_skill_ksl_boyar_unique_war_bear",
            category_key = "character",
            indent = 0,
            tier = 1,
            max_level = 1,
            is_mount_skill = true,
            unlock_ranks_by_level = { 10 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_skill_node_ksl_boyar_unique_03",
            skill_key = "wh3_main_skill_ksl_all_unique_missile_resist",
            category_key = "character",
            indent = 0,
            tier = 2,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 6 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_skill_node_ksl_boyar_unique_04",
            skill_key = "wh_main_skill_all_lord_battle_brass-lunged",
            category_key = "character",
            indent = 0,
            tier = 3,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 3 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_skill_node_ksl_boyar_unique_05",
            skill_key = "wh3_main_skill_ksl_generic_heroic_resilience",
            category_key = "character",
            indent = 0,
            tier = 4,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_skill_node_ksl_boyar_exclusive_1_1",
            skill_key = "wh3_main_skill_ksl_boyar_unique_1",
            category_key = "character",
            indent = 1,
            tier = 0,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 8 },
            locked_node_keys = {
                "wh3_main_skill_node_ksl_boyar_exclusive_1_2",
                "wh3_main_skill_node_ksl_boyar_exclusive_1_3",
            }
        },
        {
            node_key = "wh3_main_skill_node_ksl_boyar_exclusive_1_2",
            skill_key = "wh3_main_skill_ksl_boyar_unique_2",
            category_key = "character",
            indent = 1,
            tier = 1,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 8 },
            locked_node_keys = {
                "wh3_main_skill_node_ksl_boyar_exclusive_1_1",
                "wh3_main_skill_node_ksl_boyar_exclusive_1_3",
            }
        },
        {
            node_key = "wh3_main_skill_node_ksl_boyar_exclusive_1_3",
            skill_key = "wh3_main_skill_ksl_boyar_unique_3",
            category_key = "character",
            indent = 1,
            tier = 2,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 8 },
            locked_node_keys = {
                "wh3_main_skill_node_ksl_boyar_exclusive_1_1",
                "wh3_main_skill_node_ksl_boyar_exclusive_1_2",
            }
        },
        {
            node_key = "wh3_main_skill_node_ksl_boyar_exclusive_2_1",
            skill_key = "wh3_main_skill_ksl_boyar_unique_4",
            category_key = "character",
            indent = 2,
            tier = 0,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 12 },
            locked_node_keys = {
                "wh3_main_skill_node_ksl_boyar_exclusive_2_2",
                "wh3_main_skill_node_ksl_boyar_exclusive_2_3",
            }
        },
        {
            node_key = "wh3_main_skill_node_ksl_boyar_exclusive_2_2",
            skill_key = "wh3_main_skill_ksl_boyar_unique_5",
            category_key = "character",
            indent = 2,
            tier = 1,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 12 },
            locked_node_keys = {
                "wh3_main_skill_node_ksl_boyar_exclusive_2_1",
                "wh3_main_skill_node_ksl_boyar_exclusive_2_3",
            }
        },
        {
            node_key = "wh3_main_skill_node_ksl_boyar_exclusive_2_3",
            skill_key = "wh3_main_skill_ksl_boyar_unique_6",
            category_key = "character",
            indent = 2,
            tier = 2,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 12 },
            locked_node_keys = {
                "wh3_main_skill_node_ksl_boyar_exclusive_2_1",
                "wh3_main_skill_node_ksl_boyar_exclusive_2_2",
            }
        },
        {
            node_key = "wh3_main_skill_node_ksl_boyar_combat_0",
            skill_key = "wh_main_skill_all_all_self_hard_to_hit_starter",
            category_key = "character",
            indent = 3,
            tier = 0,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_skill_node_ksl_boyar_combat_1_1",
            skill_key = "wh2_dlc11_skill_all_lord_self_devastating_charge",
            category_key = "character",
            indent = 3,
            tier = 1,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_skill_node_ksl_boyar_combat_1_2",
            skill_key = "wh2_dlc11_skill_all_lord_self_full_plate_armour",
            category_key = "character",
            indent = 3,
            tier = 2,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_skill_node_ksl_boyar_combat_1_3",
            skill_key = "wh2_dlc11_skill_all_lord_self_scarred_veteran",
            category_key = "character",
            indent = 3,
            tier = 3,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_skill_node_ksl_boyar_combat_1_4",
            skill_key = "wh2_dlc11_skill_all_lord_self_deadly_blade",
            category_key = "character",
            indent = 3,
            tier = 4,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_skill_node_ksl_boyar_combat_2",
            skill_key = "wh_main_skill_all_all_self_foe-seeker",
            category_key = "character",
            indent = 3,
            tier = 5,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_skill_node_ksl_boyar_combat_3_1",
            skill_key = "wh2_dlc11_skill_all_lord_self_wound-maker",
            category_key = "character",
            indent = 3,
            tier = 6,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_skill_node_ksl_boyar_combat_3_2",
            skill_key = "wh2_dlc11_skill_all_lord_self_blade_master",
            category_key = "character",
            indent = 3,
            tier = 7,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_skill_node_ksl_boyar_combat_3_3",
            skill_key = "wh2_dlc11_skill_all_lord_self_self_indomitable",
            category_key = "character",
            indent = 3,
            tier = 8,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_skill_node_ksl_boyar_combat_3_4",
            skill_key = "wh2_dlc11_skill_all_lord_self_blade_shield",
            category_key = "character",
            indent = 3,
            tier = 9,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_skill_node_ksl_boyar_combat_4",
            skill_key = "wh_main_skill_all_all_self_deadly_onslaught",
            category_key = "character",
            indent = 3,
            tier = 10,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
                "wh_dlc05_skill_node_wef_glade_lord_fem_self_ranged_06",
                "wh_dlc05_skill_node_wef_glade_lord_self_ranged_06",
            }
        },
        {
            node_key = "wh3_main_skill_node_ksl_boyar_army_0",
            skill_key = "wh_main_skill_all_lord_battle_inspiring_presence",
            category_key = "battle",
            indent = 4,
            tier = 0,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_skill_node_ksl_boyar_army_1_1",
            skill_key = "wh3_main_skill_ksl_army_buff_kossars_streltsi",
            category_key = "battle",
            indent = 4,
            tier = 1,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_skill_node_ksl_boyar_army_1_3",
            skill_key = "wh3_main_skill_ksl_army_buff_elite_infantry",
            category_key = "battle",
            indent = 4,
            tier = 2,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_skill_node_ksl_boyar_army_1_4",
            skill_key = "wh3_main_skill_ksl_army_buff_heavy_cavalry",
            category_key = "battle",
            indent = 4,
            tier = 3,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_skill_node_ksl_boyar_army_1_5",
            skill_key = "wh3_main_skill_ksl_army_buff_monsters",
            category_key = "battle",
            indent = 4,
            tier = 4,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_skill_node_ksl_boyar_army_1_6",
            skill_key = "wh3_main_skill_ksl_army_buff_war_machines",
            category_key = "battle",
            indent = 4,
            tier = 5,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_skill_node_ksl_boyar_army_2",
            skill_key = "wh_main_skill_all_lord_battle_rally",
            category_key = "battle",
            indent = 4,
            tier = 6,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_skill_node_ksl_boyar_army_3_1",
            skill_key = "wh3_main_skill_ksl_army_buff_kossars_streltsi_ice_guard_rank_7",
            category_key = "battle",
            indent = 4,
            tier = 7,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_skill_node_ksl_boyar_army_3_2",
            skill_key = "wh3_main_skill_ksl_army_buff_cavalry_rank_7",
            category_key = "battle",
            indent = 4,
            tier = 8,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_skill_node_ksl_boyar_army_3_3",
            skill_key = "wh3_main_skill_ksl_army_buff_bears_tsar_guard_rank_7",
            category_key = "battle",
            indent = 4,
            tier = 9,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_skill_node_ksl_boyar_army_3_4",
            skill_key = "wh3_main_skill_ksl_army_buff_war_machines_rank_7",
            category_key = "battle",
            indent = 4,
            tier = 10,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_skill_node_ksl_boyar_army_4",
            skill_key = "wh_main_skill_all_lord_battle_stand_your_ground",
            category_key = "battle",
            indent = 4,
            tier = 11,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
    },
    wh3_main_ksl_ice_witch_ice = {
        {
            node_key = "wh3_main_skill_node_ksl_ice_witch_ice_unique_01",
            skill_key = "wh3_main_skill_ksl_ice_witch_ice_unique_warhorse",
            category_key = "character",
            indent = 0,
            tier = 0,
            max_level = 1,
            is_mount_skill = true,
            unlock_ranks_by_level = { 7 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_skill_node_ksl_ice_witch_ice_unique_02",
            skill_key = "wh3_main_skill_ksl_ice_witch_ice_unique_war_bear",
            category_key = "character",
            indent = 0,
            tier = 1,
            max_level = 1,
            is_mount_skill = true,
            unlock_ranks_by_level = { 13 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_skill_node_ksl_ice_witch_ice_unique_06",
            skill_key = "wh3_dlc24_skill_ksl_ice_witch_ice_unique_frost_wyrm",
            category_key = "character",
            indent = 0,
            tier = 2,
            max_level = 1,
            is_mount_skill = true,
            unlock_ranks_by_level = { 17 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_skill_node_ksl_ice_witch_ice_unique_03",
            skill_key = "wh3_main_skill_ksl_all_unique_missile_resist",
            category_key = "character",
            indent = 0,
            tier = 3,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 6 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_skill_node_ksl_ice_witch_ice_unique_04",
            skill_key = "wh3_main_skill_ksl_wizard_unique_guardian_call",
            category_key = "character",
            indent = 0,
            tier = 4,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 11 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_skill_node_ksl_ice_witch_ice_magic_0",
            skill_key = "wh3_main_skill_ksl_magic_ice_01_ice_maidens_kiss_lord",
            category_key = "character",
            indent = 2,
            tier = 0,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_skill_node_ksl_ice_witch_ice_magic_1_1",
            skill_key = "wh3_main_skill_ksl_magic_ice_05_frost_shield",
            category_key = "character",
            indent = 2,
            tier = 1,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_skill_node_ksl_ice_witch_ice_magic_1_2",
            skill_key = "wh3_main_skill_ksl_magic_ice_02_ice_sheet_lord",
            category_key = "character",
            indent = 2,
            tier = 2,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_skill_node_ksl_ice_witch_ice_magic_1_3",
            skill_key = "wh3_main_skill_ksl_magic_ice_03_frost_blades_lord",
            category_key = "character",
            indent = 2,
            tier = 3,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_skill_node_ksl_ice_witch_ice_magic_1_4",
            skill_key = "wh3_main_skill_ksl_magic_ice_04_death_frost_lord",
            category_key = "character",
            indent = 2,
            tier = 4,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_skill_node_ksl_ice_witch_ice_magic_2",
            skill_key = "wh_main_skill_all_magic_all_06_evasion",
            category_key = "character",
            indent = 2,
            tier = 5,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_skill_node_ksl_ice_witch_ice_magic_3_3",
            skill_key = "wh3_main_skill_ksl_magic_ice_07_crystal_sanctuary_lord",
            category_key = "character",
            indent = 2,
            tier = 6,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_skill_node_ksl_ice_witch_ice_magic_3_4",
            skill_key = "wh3_main_skill_ksl_magic_ice_08_heart_of_winter_lord",
            category_key = "character",
            indent = 2,
            tier = 7,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_skill_node_ksl_ice_witch_ice_magic_3_1",
            skill_key = "wh_main_skill_all_magic_all_07_earthing",
            category_key = "character",
            indent = 2,
            tier = 8,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_skill_node_ksl_ice_witch_ice_magic_3_2",
            skill_key = "wh_main_skill_all_magic_all_08_power_drain",
            category_key = "character",
            indent = 2,
            tier = 9,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_skill_node_ksl_ice_witch_ice_magic_4",
            skill_key = "wh_main_skill_all_magic_all_11_arcane_conduit",
            category_key = "character",
            indent = 2,
            tier = 10,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_skill_node_ksl_ice_witch_ice_magic_dummy",
            skill_key = "wh3_main_skill_ksl_magic_ice_dummy_ice_maidens_kiss_ice_sheet",
            category_key = "character",
            indent = 2,
            tier = 11,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_skill_node_ksl_ice_witch_ice_army_0",
            skill_key = "wh_main_skill_all_lord_battle_inspiring_presence",
            category_key = "battle",
            indent = 4,
            tier = 0,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_skill_node_ksl_ice_witch_ice_army_1_1",
            skill_key = "wh3_main_skill_ksl_army_buff_kossars_streltsi",
            category_key = "battle",
            indent = 4,
            tier = 1,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_skill_node_ksl_ice_witch_ice_army_1_3",
            skill_key = "wh3_main_skill_ksl_army_buff_elite_infantry",
            category_key = "battle",
            indent = 4,
            tier = 2,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_skill_node_ksl_ice_witch_ice_army_1_4",
            skill_key = "wh3_main_skill_ksl_army_buff_heavy_cavalry",
            category_key = "battle",
            indent = 4,
            tier = 3,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_skill_node_ksl_ice_witch_ice_army_1_5",
            skill_key = "wh3_main_skill_ksl_army_buff_monsters",
            category_key = "battle",
            indent = 4,
            tier = 4,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_skill_node_ksl_ice_witch_ice_army_1_6",
            skill_key = "wh3_main_skill_ksl_army_buff_war_machines",
            category_key = "battle",
            indent = 4,
            tier = 5,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_skill_node_ksl_ice_witch_ice_army_2",
            skill_key = "wh_main_skill_all_lord_battle_rally",
            category_key = "battle",
            indent = 4,
            tier = 6,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_skill_node_ksl_ice_witch_ice_army_3_1",
            skill_key = "wh3_main_skill_ksl_army_buff_kossars_streltsi_ice_guard_rank_7",
            category_key = "battle",
            indent = 4,
            tier = 7,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_skill_node_ksl_ice_witch_ice_army_3_2",
            skill_key = "wh3_main_skill_ksl_army_buff_cavalry_rank_7",
            category_key = "battle",
            indent = 4,
            tier = 8,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_skill_node_ksl_ice_witch_ice_army_3_3",
            skill_key = "wh3_main_skill_ksl_army_buff_bears_tsar_guard_rank_7",
            category_key = "battle",
            indent = 4,
            tier = 9,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_skill_node_ksl_ice_witch_ice_army_3_4",
            skill_key = "wh3_main_skill_ksl_army_buff_war_machines_rank_7",
            category_key = "battle",
            indent = 4,
            tier = 10,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_skill_node_ksl_ice_witch_ice_army_4",
            skill_key = "wh_main_skill_all_lord_battle_stand_your_ground",
            category_key = "battle",
            indent = 4,
            tier = 11,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
    },
    wh3_main_ksl_ice_witch_tempest = {
        {
            node_key = "wh3_main_skill_node_ksl_ice_witch_tempest_unique_01",
            skill_key = "wh3_main_skill_ksl_ice_witch_tempest_unique_warhorse",
            category_key = "character",
            indent = 0,
            tier = 0,
            max_level = 1,
            is_mount_skill = true,
            unlock_ranks_by_level = { 7 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_skill_node_ksl_ice_witch_tempest_unique_02",
            skill_key = "wh3_main_skill_ksl_ice_witch_tempest_unique_war_bear",
            category_key = "character",
            indent = 0,
            tier = 1,
            max_level = 1,
            is_mount_skill = true,
            unlock_ranks_by_level = { 13 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_skill_node_ksl_ice_witch_tempest_unique_06",
            skill_key = "wh3_dlc24_skill_ksl_ice_witch_tempest_unique_frost_wyrm",
            category_key = "character",
            indent = 0,
            tier = 2,
            max_level = 1,
            is_mount_skill = true,
            unlock_ranks_by_level = { 17 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_skill_node_ksl_ice_witch_tempest_unique_03",
            skill_key = "wh3_main_skill_ksl_all_unique_missile_resist",
            category_key = "character",
            indent = 0,
            tier = 3,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 6 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_skill_node_ksl_ice_witch_tempest_unique_04",
            skill_key = "wh3_main_skill_ksl_wizard_unique_guardian_call",
            category_key = "character",
            indent = 0,
            tier = 4,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 11 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_skill_node_ksl_ice_witch_tempest_magic_0",
            skill_key = "wh3_main_skill_ksl_magic_tempest_01_hailstorm_lord",
            category_key = "character",
            indent = 2,
            tier = 0,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_skill_node_ksl_ice_witch_tempest_magic_1_1",
            skill_key = "wh3_main_skill_ksl_magic_tempest_05_freezing_winds",
            category_key = "character",
            indent = 2,
            tier = 1,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_skill_node_ksl_ice_witch_tempest_magic_1_2",
            skill_key = "wh3_main_skill_ksl_magic_tempest_02_gust_of_true_flight_lord",
            category_key = "character",
            indent = 2,
            tier = 2,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_skill_node_ksl_ice_witch_tempest_magic_1_3",
            skill_key = "wh3_main_skill_ksl_magic_tempest_03_swiftwing_lord",
            category_key = "character",
            indent = 2,
            tier = 3,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_skill_node_ksl_ice_witch_tempest_magic_1_4",
            skill_key = "wh3_main_skill_ksl_magic_tempest_04_biting_wind_lord",
            category_key = "character",
            indent = 2,
            tier = 4,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_skill_node_ksl_ice_witch_tempest_magic_2",
            skill_key = "wh_main_skill_all_magic_all_06_evasion",
            category_key = "character",
            indent = 2,
            tier = 5,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_skill_node_ksl_ice_witch_tempest_magic_3_3",
            skill_key = "wh3_main_skill_ksl_magic_tempest_07_blizzard_lord",
            category_key = "character",
            indent = 2,
            tier = 6,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_skill_node_ksl_ice_witch_tempest_magic_3_4",
            skill_key = "wh3_main_skill_ksl_magic_tempest_07_hawks_of_miska_lord",
            category_key = "character",
            indent = 2,
            tier = 7,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_skill_node_ksl_ice_witch_tempest_magic_3_1",
            skill_key = "wh_main_skill_all_magic_all_07_earthing",
            category_key = "character",
            indent = 2,
            tier = 8,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_skill_node_ksl_ice_witch_tempest_magic_3_2",
            skill_key = "wh_main_skill_all_magic_all_08_power_drain",
            category_key = "character",
            indent = 2,
            tier = 9,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_skill_node_ksl_ice_witch_tempest_magic_4",
            skill_key = "wh_main_skill_all_magic_all_11_arcane_conduit",
            category_key = "character",
            indent = 2,
            tier = 10,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_skill_node_ksl_ice_witch_tempest_magic_dummy",
            skill_key = "wh3_main_skill_ksl_magic_tempest_dummy_hailstorm_gust_of_true_flight",
            category_key = "character",
            indent = 2,
            tier = 11,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_skill_node_ksl_ice_witch_tempest_army_0",
            skill_key = "wh_main_skill_all_lord_battle_inspiring_presence",
            category_key = "battle",
            indent = 4,
            tier = 0,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_skill_node_ksl_ice_witch_tempest_army_1_1",
            skill_key = "wh3_main_skill_ksl_army_buff_kossars_streltsi",
            category_key = "battle",
            indent = 4,
            tier = 1,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_skill_node_ksl_ice_witch_tempest_army_1_3",
            skill_key = "wh3_main_skill_ksl_army_buff_elite_infantry",
            category_key = "battle",
            indent = 4,
            tier = 2,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_skill_node_ksl_ice_witch_tempest_army_1_4",
            skill_key = "wh3_main_skill_ksl_army_buff_heavy_cavalry",
            category_key = "battle",
            indent = 4,
            tier = 3,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_skill_node_ksl_ice_witch_tempest_army_1_5",
            skill_key = "wh3_main_skill_ksl_army_buff_monsters",
            category_key = "battle",
            indent = 4,
            tier = 4,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_skill_node_ksl_ice_witch_tempest_army_1_6",
            skill_key = "wh3_main_skill_ksl_army_buff_war_machines",
            category_key = "battle",
            indent = 4,
            tier = 5,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_skill_node_ksl_ice_witch_tempest_army_2",
            skill_key = "wh_main_skill_all_lord_battle_rally",
            category_key = "battle",
            indent = 4,
            tier = 6,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_skill_node_ksl_ice_witch_tempest_army_3_1",
            skill_key = "wh3_main_skill_ksl_army_buff_kossars_streltsi_ice_guard_rank_7",
            category_key = "battle",
            indent = 4,
            tier = 7,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_skill_node_ksl_ice_witch_tempest_army_3_2",
            skill_key = "wh3_main_skill_ksl_army_buff_cavalry_rank_7",
            category_key = "battle",
            indent = 4,
            tier = 8,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_skill_node_ksl_ice_witch_tempest_army_3_3",
            skill_key = "wh3_main_skill_ksl_army_buff_bears_tsar_guard_rank_7",
            category_key = "battle",
            indent = 4,
            tier = 9,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_skill_node_ksl_ice_witch_tempest_army_3_4",
            skill_key = "wh3_main_skill_ksl_army_buff_war_machines_rank_7",
            category_key = "battle",
            indent = 4,
            tier = 10,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_skill_node_ksl_ice_witch_tempest_army_4",
            skill_key = "wh_main_skill_all_lord_battle_stand_your_ground",
            category_key = "battle",
            indent = 4,
            tier = 11,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
    },
    wh3_main_pro_kho_bloodthirster = {
        {
            node_key = "wh3_dlc26_skill_node_kho_character_hates_slaanesh",
            skill_key = "wh3_main_skill_kho_generic_hates_slaanesh",
            category_key = "character",
            indent = 0,
            tier = 4,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 6 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc26_skill_node_kho_character_thick_skin",
            skill_key = "wh3_main_skill_kho_all_unique_missile_resist",
            category_key = "character",
            indent = 0,
            tier = 9,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 6 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc26_skill_node_kho_character_brass_collar",
            skill_key = "wh3_main_skill_kho_all_unique_magic_resist",
            category_key = "character",
            indent = 0,
            tier = 10,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 6 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_skill_node_kho_exalted_bloodthirster_unique_0_prologue",
            skill_key = "wh3_main_skill_kho_exalted_bloodthirster_self_unique_wrath",
            category_key = "character",
            indent = 1,
            tier = 0,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 16 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_skill_node_kho_exalted_bloodthirster_unique_1_prologue",
            skill_key = "wh3_main_skill_kho_exalted_bloodthirster_self_unique_fury",
            category_key = "character",
            indent = 1,
            tier = 1,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 16 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_skill_node_kho_exalted_bloodthirster_unique_2_prologue",
            skill_key = "wh3_main_skill_kho_exalted_bloodthirster_self_unique_rage",
            category_key = "character",
            indent = 1,
            tier = 2,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 16 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_skill_node_kho_exalted_bloodthirster_self_0_prologue",
            skill_key = "wh3_main_skill_kho_all_self_brutal_charge",
            category_key = "character",
            indent = 2,
            tier = 0,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_skill_node_kho_exalted_bloodthirster_self_1_1_prologue",
            skill_key = "wh3_main_skill_kho_lord_self_1_1",
            category_key = "character",
            indent = 2,
            tier = 1,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_skill_node_kho_exalted_bloodthirster_self_1_2_prologue",
            skill_key = "wh3_main_skill_kho_lord_self_1_2",
            category_key = "character",
            indent = 2,
            tier = 2,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_skill_node_kho_exalted_bloodthirster_self_1_3_prologue",
            skill_key = "wh3_main_skill_kho_lord_self_1_3",
            category_key = "character",
            indent = 2,
            tier = 3,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_skill_node_kho_exalted_bloodthirster_self_1_4_prologue",
            skill_key = "wh3_main_skill_kho_lord_self_1_4",
            category_key = "character",
            indent = 2,
            tier = 4,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_skill_node_kho_exalted_bloodthirster_self_2_prologue",
            skill_key = "wh3_main_skill_kho_exalted_bloodthirster_self_bloodthirst",
            category_key = "character",
            indent = 2,
            tier = 5,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_skill_node_kho_exalted_bloodthirster_self_3_1_prologue",
            skill_key = "wh3_main_skill_kho_lord_self_3_1",
            category_key = "character",
            indent = 2,
            tier = 6,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_skill_node_kho_exalted_bloodthirster_self_3_2_prologue",
            skill_key = "wh3_main_skill_kho_lord_self_3_2",
            category_key = "character",
            indent = 2,
            tier = 7,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_skill_node_kho_exalted_bloodthirster_self_3_3_prologue",
            skill_key = "wh3_main_skill_kho_lord_self_3_3",
            category_key = "character",
            indent = 2,
            tier = 8,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_skill_node_kho_exalted_bloodthirster_self_3_4_prologue",
            skill_key = "wh3_main_skill_kho_lord_self_3_4",
            category_key = "character",
            indent = 2,
            tier = 9,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_skill_node_kho_exalted_bloodthirster_self_4_prologue",
            skill_key = "wh3_main_skill_kho_exalted_bloodthirster_self_deathbringer",
            category_key = "character",
            indent = 2,
            tier = 10,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_skill_node_kho_exalted_bloodthirster_army_0_prologue",
            skill_key = "wh_main_skill_all_lord_battle_inspiring_presence",
            category_key = "battle",
            indent = 4,
            tier = 0,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_skill_node_kho_exalted_bloodthirster_army_1_1_prologue",
            skill_key = "wh3_main_skill_kho_lord_army_buff_1_1",
            category_key = "battle",
            indent = 4,
            tier = 1,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_skill_node_kho_exalted_bloodthirster_army_1_2_prologue",
            skill_key = "wh3_main_skill_kho_lord_army_buff_1_2",
            category_key = "battle",
            indent = 4,
            tier = 2,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_skill_node_kho_exalted_bloodthirster_army_1_3_prologue",
            skill_key = "wh3_main_skill_kho_lord_army_buff_1_3",
            category_key = "battle",
            indent = 4,
            tier = 3,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_skill_node_kho_exalted_bloodthirster_army_1_5_prologue",
            skill_key = "wh3_main_skill_kho_lord_army_buff_1_5",
            category_key = "battle",
            indent = 4,
            tier = 4,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_skill_node_kho_exalted_bloodthirster_army_1_6_prologue",
            skill_key = "wh3_main_skill_kho_lord_army_buff_1_6",
            category_key = "battle",
            indent = 4,
            tier = 5,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_skill_node_kho_exalted_bloodthirster_army_2_prologue",
            skill_key = "wh3_main_skill_kho_lord_army_kill_for_khorne",
            category_key = "battle",
            indent = 4,
            tier = 6,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_skill_node_kho_exalted_bloodthirster_army_3_1_prologue",
            skill_key = "wh3_main_skill_kho_lord_army_buff_3_1",
            category_key = "battle",
            indent = 4,
            tier = 7,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_skill_node_kho_exalted_bloodthirster_army_3_2_prologue",
            skill_key = "wh3_main_skill_kho_lord_army_buff_3_2",
            category_key = "battle",
            indent = 4,
            tier = 8,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_skill_node_kho_exalted_bloodthirster_army_3_3_prologue",
            skill_key = "wh3_main_skill_kho_lord_army_buff_3_3",
            category_key = "battle",
            indent = 4,
            tier = 9,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_skill_node_kho_exalted_bloodthirster_army_3_4_prologue",
            skill_key = "wh3_main_skill_kho_lord_army_buff_3_4",
            category_key = "battle",
            indent = 4,
            tier = 10,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_skill_node_kho_exalted_bloodthirster_army_4_prologue",
            skill_key = "wh3_main_skill_kho_lord_army_revel_in_slaughter",
            category_key = "battle",
            indent = 4,
            tier = 11,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
    },
    wh3_main_pro_ksl_boyar = {
        {
            node_key = "wh3_main_pro_skill_node_ksl_boyar_unique_01",
            skill_key = "wh3_main_skill_ksl_boyar_unique_warhorse",
            category_key = "character",
            indent = 0,
            tier = 0,
            max_level = 1,
            is_mount_skill = true,
            unlock_ranks_by_level = { 4 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_pro_skill_node_ksl_boyar_unique_02",
            skill_key = "wh3_main_skill_ksl_boyar_unique_war_bear",
            category_key = "character",
            indent = 0,
            tier = 1,
            max_level = 1,
            is_mount_skill = true,
            unlock_ranks_by_level = { 10 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_pro_skill_node_ksl_boyar_unique_03",
            skill_key = "wh3_main_skill_ksl_all_unique_missile_resist",
            category_key = "character",
            indent = 0,
            tier = 2,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 6 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_pro_skill_node_ksl_boyar_unique_04",
            skill_key = "wh_main_skill_all_lord_battle_brass-lunged",
            category_key = "character",
            indent = 0,
            tier = 3,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 3 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_pro_skill_node_ksl_boyar_unique_05",
            skill_key = "wh3_main_skill_ksl_generic_heroic_resilience",
            category_key = "character",
            indent = 0,
            tier = 4,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_pro_skill_node_ksl_boyar_combat_0",
            skill_key = "wh_main_skill_all_all_self_hard_to_hit_starter",
            category_key = "character",
            indent = 1,
            tier = 0,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_pro_skill_node_ksl_boyar_combat_1_1",
            skill_key = "wh2_dlc11_skill_all_lord_self_devastating_charge",
            category_key = "character",
            indent = 1,
            tier = 1,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_pro_skill_node_ksl_boyar_combat_1_2",
            skill_key = "wh2_dlc11_skill_all_lord_self_full_plate_armour",
            category_key = "character",
            indent = 1,
            tier = 2,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_pro_skill_node_ksl_boyar_combat_1_3",
            skill_key = "wh2_dlc11_skill_all_lord_self_scarred_veteran",
            category_key = "character",
            indent = 1,
            tier = 3,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_pro_skill_node_ksl_boyar_combat_1_4",
            skill_key = "wh2_dlc11_skill_all_lord_self_deadly_blade",
            category_key = "character",
            indent = 1,
            tier = 4,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_pro_skill_node_ksl_boyar_combat_2",
            skill_key = "wh_main_skill_all_all_self_foe-seeker",
            category_key = "character",
            indent = 1,
            tier = 5,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_pro_skill_node_ksl_boyar_combat_3_1",
            skill_key = "wh2_dlc11_skill_all_lord_self_wound-maker",
            category_key = "character",
            indent = 1,
            tier = 6,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_pro_skill_node_ksl_boyar_combat_3_2",
            skill_key = "wh2_dlc11_skill_all_lord_self_blade_master",
            category_key = "character",
            indent = 1,
            tier = 7,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_pro_skill_node_ksl_boyar_combat_3_3",
            skill_key = "wh2_dlc11_skill_all_lord_self_self_indomitable",
            category_key = "character",
            indent = 1,
            tier = 8,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_pro_skill_node_ksl_boyar_combat_3_4",
            skill_key = "wh2_dlc11_skill_all_lord_self_blade_shield",
            category_key = "character",
            indent = 1,
            tier = 9,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_pro_skill_node_ksl_boyar_combat_4",
            skill_key = "wh_main_skill_all_all_self_deadly_onslaught",
            category_key = "character",
            indent = 1,
            tier = 10,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
                "wh_dlc05_skill_node_wef_glade_lord_fem_self_ranged_06",
                "wh_dlc05_skill_node_wef_glade_lord_self_ranged_06",
            }
        },
        {
            node_key = "wh3_main_pro_skill_node_ksl_boyar_army_0",
            skill_key = "wh_main_skill_all_lord_battle_inspiring_presence",
            category_key = "battle",
            indent = 4,
            tier = 0,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_pro_skill_node_ksl_boyar_army_1_1",
            skill_key = "wh3_main_skill_ksl_army_buff_kossars_streltsi",
            category_key = "battle",
            indent = 4,
            tier = 1,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_pro_skill_node_ksl_boyar_army_1_3",
            skill_key = "wh3_main_skill_ksl_army_buff_elite_infantry",
            category_key = "battle",
            indent = 4,
            tier = 2,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_pro_skill_node_ksl_boyar_army_1_4",
            skill_key = "wh3_main_skill_ksl_army_buff_heavy_cavalry",
            category_key = "battle",
            indent = 4,
            tier = 3,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_pro_skill_node_ksl_boyar_army_1_5",
            skill_key = "wh3_main_skill_ksl_army_buff_monsters",
            category_key = "battle",
            indent = 4,
            tier = 4,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_pro_skill_node_ksl_boyar_army_1_6",
            skill_key = "wh3_main_skill_ksl_army_buff_war_machines",
            category_key = "battle",
            indent = 4,
            tier = 5,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_pro_skill_node_ksl_boyar_army_2",
            skill_key = "wh_main_skill_all_lord_battle_rally",
            category_key = "battle",
            indent = 4,
            tier = 6,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_pro_skill_node_ksl_boyar_army_3_1",
            skill_key = "wh3_main_skill_ksl_army_buff_kossars_streltsi_ice_guard_rank_7",
            category_key = "battle",
            indent = 4,
            tier = 7,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_pro_skill_node_ksl_boyar_army_3_2",
            skill_key = "wh3_main_skill_ksl_army_buff_cavalry_rank_7",
            category_key = "battle",
            indent = 4,
            tier = 8,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_pro_skill_node_ksl_boyar_army_3_3",
            skill_key = "wh3_main_skill_ksl_army_buff_bears_tsar_guard_rank_7",
            category_key = "battle",
            indent = 4,
            tier = 9,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_pro_skill_node_ksl_boyar_army_3_4",
            skill_key = "wh3_main_skill_ksl_army_buff_war_machines_rank_7",
            category_key = "battle",
            indent = 4,
            tier = 10,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_main_pro_skill_node_ksl_boyar_army_4",
            skill_key = "wh_main_skill_all_lord_battle_stand_your_ground",
            category_key = "battle",
            indent = 4,
            tier = 11,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
    },
    wh3_main_pro_ksl_yuri_0 = {
        {
            node_key = "wh3_prologue_skill_node_generic_1_1",
            skill_key = "wh3_main_skill_ksl_all_unique_missile_resist",
            category_key = "character",
            indent = 0,
            tier = 0,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 6 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_prologue_skill_node_generic_1_2",
            skill_key = "wh3_main_skill_ksl_yuri_unique_warhorse",
            category_key = "character",
            indent = 0,
            tier = 1,
            max_level = 1,
            is_mount_skill = true,
            unlock_ranks_by_level = { 7 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_prologue_skill_node_generic_1_3",
            skill_key = "wh3_main_skill_ksl_yuri_unique_war_bear",
            category_key = "character",
            indent = 0,
            tier = 2,
            max_level = 1,
            is_mount_skill = true,
            unlock_ranks_by_level = { 11 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_prologue_skill_node_generic_1_4",
            skill_key = "wh3_main_skill_ksl_generic_heroic_resilience",
            category_key = "character",
            indent = 0,
            tier = 3,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_prologue_skill_node_generic_2",
            skill_key = "wh3_main_pro_skill_ksl_unique_yuri_ursuns_roar_1",
            category_key = "character",
            indent = 0,
            tier = 4,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_prologue_skill_node_combat_0",
            skill_key = "wh_main_skill_all_all_self_blade_master_starter",
            category_key = "character",
            indent = 2,
            tier = 0,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_prologue_skill_node_combat_1_1",
            skill_key = "wh_main_skill_all_all_self_blade_shield",
            category_key = "character",
            indent = 2,
            tier = 1,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_prologue_skill_node_combat_1_2",
            skill_key = "wh_main_skill_all_lord_self_full_plate_armour",
            category_key = "character",
            indent = 2,
            tier = 2,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_prologue_skill_node_combat_2",
            skill_key = "wh3_main_pro_skill_ksl_unique_yuri_heroic_killing_blow_1",
            category_key = "character",
            indent = 2,
            tier = 3,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_prologue_skill_node_combat_3_1",
            skill_key = "wh_main_skill_all_all_self_deadly_blade",
            category_key = "character",
            indent = 2,
            tier = 4,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_prologue_skill_node_combat_3_2",
            skill_key = "wh_main_skill_all_all_self_indomitable",
            category_key = "character",
            indent = 2,
            tier = 5,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_prologue_skill_node_combat_4",
            skill_key = "wh3_main_pro_skill_ksl_unique_yuri_heroic_killing_blow_2",
            category_key = "character",
            indent = 2,
            tier = 6,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_prologue_skill_node_army_0",
            skill_key = "wh_main_skill_all_lord_battle_inspiring_presence",
            category_key = "character",
            indent = 3,
            tier = 0,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_prologue_skill_node_army_1_1",
            skill_key = "wh3_main_skill_ksl_army_buff_kossars_streltsi",
            category_key = "character",
            indent = 3,
            tier = 1,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_prologue_skill_node_army_1_3",
            skill_key = "wh3_main_skill_ksl_army_buff_elite_infantry",
            category_key = "character",
            indent = 3,
            tier = 3,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_prologue_skill_node_army_2",
            skill_key = "wh3_main_pro_skill_ksl_unique_yuri_ursuns_roar_2",
            category_key = "character",
            indent = 3,
            tier = 4,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_prologue_skill_node_army_3_1",
            skill_key = "wh3_main_skill_ksl_army_buff_kossars_streltsi_ice_guard_rank_7",
            category_key = "character",
            indent = 3,
            tier = 5,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_prologue_skill_node_army_3_2",
            skill_key = "wh3_main_skill_ksl_army_buff_cavalry_rank_7",
            category_key = "character",
            indent = 3,
            tier = 6,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
    },
}

return data
