local data = {}

-- AUTO-GENERATED by tools/adamrogue/generate_stage_d_data.py.
data.CONTENT_FACTION_KEY = "wh_main_emp_empire"

data.CHARACTER_SKILL_PLANS_BY_SUBTYPE = {
    wh2_dlc13_emp_cha_huntsmarshal = {
        {
            node_key = "wh_dlc13_skill_node_emp_huntsmarshal_unique_05",
            skill_key = "wh_main_skill_all_lord_battle_brass-lunged",
            category_key = "character",
            indent = 0,
            tier = 1,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 3 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc13_skill_node_emp_huntsmarshal_unique_06",
            skill_key = "wh_main_skill_emp_lord_battle_hold_the_line",
            category_key = "character",
            indent = 0,
            tier = 2,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 5 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc13_skill_node_emp_huntsmarshal_unique_07",
            skill_key = "wh3_dlc25_skill_emp_all_unique_mark_of_hysh",
            category_key = "character",
            indent = 0,
            tier = 3,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 7 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc13_skill_node_emp_huntsmarshal_unique_04",
            skill_key = "wh_main_skill_emp_all_unique_sigmars_ward",
            category_key = "character",
            indent = 0,
            tier = 4,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 7 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_dlc13_skill_emp_hunts_marshal_unique_0",
            skill_key = "wh2_dlc13_skill_emp_hunts_marshal_unique_0",
            category_key = "character",
            indent = 1,
            tier = 1,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 11 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_dlc13_skill_emp_hunts_marshal_unique_1",
            skill_key = "wh2_dlc13_skill_emp_hunts_marshal_unique_1",
            category_key = "character",
            indent = 1,
            tier = 2,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 11 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_dlc13_skill_emp_hunts_marshal_unique_2",
            skill_key = "wh2_dlc13_skill_emp_hunts_marshal_unique_2",
            category_key = "character",
            indent = 1,
            tier = 3,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 11 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_dlc13_skill_emp_hunts_marshal_ranged_0",
            skill_key = "wh2_dlc13_skill_emp_hunts_marshal_ranged_0",
            category_key = "character",
            indent = 2,
            tier = 0,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 6 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_dlc13_skill_emp_hunts_marshal_ranged_1",
            skill_key = "wh2_dlc13_skill_emp_hunts_marshal_ranged_1",
            category_key = "character",
            indent = 2,
            tier = 1,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_dlc13_skill_emp_hunts_marshal_ranged_2",
            skill_key = "wh2_dlc13_skill_emp_hunts_marshal_ranged_2",
            category_key = "character",
            indent = 2,
            tier = 2,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_dlc13_skill_emp_hunts_marshal_ranged_3",
            skill_key = "wh2_dlc13_skill_emp_hunts_marshal_ranged_3",
            category_key = "character",
            indent = 2,
            tier = 3,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_dlc13_skill_emp_hunts_marshal_ranged_4",
            skill_key = "wh2_dlc13_skill_emp_hunts_marshal_ranged_4",
            category_key = "character",
            indent = 2,
            tier = 4,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh2_dlc13_skill_emp_hunts_marshal_ranged_5",
            skill_key = "wh2_dlc13_skill_emp_hunts_marshal_ranged_5",
            category_key = "character",
            indent = 2,
            tier = 5,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc13_skill_node_emp_huntsmarshal_self_01",
            skill_key = "wh_main_skill_all_all_self_hard_to_hit_starter",
            category_key = "character",
            indent = 3,
            tier = 0,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc13_skill_node_emp_huntsmarshal_self_02",
            skill_key = "wh2_dlc11_skill_all_lord_self_devastating_charge",
            category_key = "character",
            indent = 3,
            tier = 1,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc13_skill_node_emp_huntsmarshal_self_03",
            skill_key = "wh2_dlc11_skill_all_lord_self_full_plate_armour",
            category_key = "character",
            indent = 3,
            tier = 2,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc13_skill_node_emp_huntsmarshal_self_04",
            skill_key = "wh2_dlc11_skill_all_lord_self_scarred_veteran",
            category_key = "character",
            indent = 3,
            tier = 3,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc13_skill_node_emp_huntsmarshal_self_05",
            skill_key = "wh2_dlc11_skill_all_lord_self_deadly_blade",
            category_key = "character",
            indent = 3,
            tier = 4,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc13_skill_node_emp_huntsmarshal_self_06",
            skill_key = "wh2_dlc13_skill_emp_hunts_marshal_personal_5",
            category_key = "character",
            indent = 3,
            tier = 5,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc13_skill_node_emp_huntsmarshal_self_07",
            skill_key = "wh2_dlc11_skill_all_lord_self_wound-maker",
            category_key = "character",
            indent = 3,
            tier = 6,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc13_skill_node_emp_huntsmarshal_self_08",
            skill_key = "wh2_dlc11_skill_all_lord_self_blade_master",
            category_key = "character",
            indent = 3,
            tier = 7,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc13_skill_node_emp_huntsmarshal_self_09",
            skill_key = "wh2_dlc11_skill_all_lord_self_self_indomitable",
            category_key = "character",
            indent = 3,
            tier = 8,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc13_skill_node_emp_huntsmarshal_self_10",
            skill_key = "wh2_dlc11_skill_all_lord_self_blade_shield",
            category_key = "character",
            indent = 3,
            tier = 9,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc13_skill_node_emp_huntsmarshal_self_11",
            skill_key = "wh2_dlc13_skill_emp_hunts_marshal_personal_10",
            category_key = "character",
            indent = 3,
            tier = 10,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc13_skill_node_emp_huntsmarshal_battle_01",
            skill_key = "wh_main_skill_all_lord_battle_inspiring_presence",
            category_key = "battle",
            indent = 4,
            tier = 0,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc13_skill_node_emp_huntsmarshal_battle_02",
            skill_key = "wh2_dlc11_skill_emp_army_buff_emperors_finest",
            category_key = "battle",
            indent = 4,
            tier = 1,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc13_skill_node_emp_huntsmarshal_battle_03",
            skill_key = "wh2_dlc11_skill_emp_army_buff_speed_of_horse",
            category_key = "battle",
            indent = 4,
            tier = 2,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc13_skill_node_emp_huntsmarshal_battle_04",
            skill_key = "wh2_dlc11_skill_emp_army_buff_pistolkorps",
            category_key = "battle",
            indent = 4,
            tier = 3,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc13_skill_node_emp_huntsmarshal_battle_05",
            skill_key = "wh2_dlc11_skill_emp_army_buff_honest_steel",
            category_key = "battle",
            indent = 4,
            tier = 4,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc13_skill_node_emp_huntsmarshal_battle_06",
            skill_key = "wh2_dlc11_skill_emp_army_buff_mighty_forge",
            category_key = "battle",
            indent = 4,
            tier = 5,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc13_skill_node_emp_huntsmarshal_battle_07",
            skill_key = "wh2_dlc11_skill_emp_army_buff_imperial_gunnery",
            category_key = "battle",
            indent = 4,
            tier = 6,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc13_skill_node_emp_huntsmarshal_battle_08",
            skill_key = "wh_main_skill_all_lord_battle_rally",
            category_key = "battle",
            indent = 4,
            tier = 7,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc13_skill_node_emp_huntsmarshal_battle_09",
            skill_key = "wh2_dlc11_skill_emp_army_buff_strength_of_hardship",
            category_key = "battle",
            indent = 4,
            tier = 8,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc13_skill_node_emp_huntsmarshal_battle_10",
            skill_key = "wh2_dlc11_skill_emp_army_buff_sharpshooter",
            category_key = "battle",
            indent = 4,
            tier = 9,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc13_skill_node_emp_huntsmarshal_battle_11",
            skill_key = "wh2_dlc11_skill_emp_army_buff_taste_for_battle",
            category_key = "battle",
            indent = 4,
            tier = 10,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc13_skill_node_emp_huntsmarshal_battle_12",
            skill_key = "wh2_dlc11_skill_emp_army_buff_artillery_master",
            category_key = "battle",
            indent = 4,
            tier = 11,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc13_skill_node_emp_huntsmarshal_battle_13",
            skill_key = "wh_main_skill_all_lord_battle_stand_your_ground",
            category_key = "battle",
            indent = 4,
            tier = 12,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
    },
    wh3_dlc25_emp_master_engineer = {
        {
            node_key = "wh3_dlc25_skill_node_emp_master_engineer_top_1",
            skill_key = "wh3_dlc25_skill_emp_master_engineer_barded_warhorse",
            category_key = "character",
            indent = 0,
            tier = 0,
            max_level = 1,
            is_mount_skill = true,
            unlock_ranks_by_level = { 6 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc25_skill_node_emp_master_engineer_top_11",
            skill_key = "wh3_dlc25_skill_emp_master_engineer_mechanical_steed",
            category_key = "character",
            indent = 0,
            tier = 1,
            max_level = 1,
            is_mount_skill = true,
            unlock_ranks_by_level = { 12 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc25_skill_node_emp_master_engineer_top_12",
            skill_key = "wh3_dlc25_skill_emp_master_engineer_steam_tank",
            category_key = "character",
            indent = 0,
            tier = 2,
            max_level = 1,
            is_mount_skill = true,
            unlock_ranks_by_level = { 19 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc25_skill_node_emp_master_engineer_top_3",
            skill_key = "wh3_dlc25_skill_emp_master_engineer_unique_2_3",
            category_key = "character",
            indent = 0,
            tier = 3,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 14 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc25_skill_node_emp_master_engineer_top_2",
            skill_key = "wh_main_skill_emp_lord_battle_hold_the_line",
            category_key = "character",
            indent = 0,
            tier = 4,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 5 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc25_skill_node_emp_master_engineer_top_7",
            skill_key = "wh3_dlc25_skill_emp_all_unique_mark_of_hysh",
            category_key = "character",
            indent = 0,
            tier = 8,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 7 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc25_skill_node_emp_master_engineer_top_8",
            skill_key = "wh_main_skill_emp_all_unique_sigmars_ward",
            category_key = "character",
            indent = 0,
            tier = 9,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 7 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc25_skill_node_emp_master_engineer_unique_2_1",
            skill_key = "wh3_dlc25_skill_emp_master_engineer_unique_3_1",
            category_key = "character",
            indent = 1,
            tier = 0,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 11 },
            locked_node_keys = {
                "wh3_dlc25_skill_node_emp_master_engineer_unique_1_2",
            }
        },
        {
            node_key = "wh3_dlc25_skill_node_emp_master_engineer_unique_2_2",
            skill_key = "wh3_dlc25_skill_master_engineer_restock_upgrade",
            category_key = "character",
            indent = 1,
            tier = 1,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc25_skill_node_emp_master_engineer_unique_2_3",
            skill_key = "wh3_dlc25_skill_emp_master_engineer_unique_3_2",
            category_key = "character",
            indent = 1,
            tier = 2,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc25_skill_node_emp_master_engineer_unique_2_4",
            skill_key = "wh_main_skill_dwf_engineer_self_ballistics_calibration",
            category_key = "character",
            indent = 1,
            tier = 3,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc25_skill_node_emp_master_engineer_unique_2_5",
            skill_key = "wh3_dlc25_skill_emp_master_engineer_self_ballistics_instructor",
            category_key = "character",
            indent = 1,
            tier = 4,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc25_skill_node_emp_master_engineer_unique_1_2",
            skill_key = "wh3_dlc25_skill_emp_master_engineer_unique_2_2",
            category_key = "character",
            indent = 2,
            tier = 0,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 11 },
            locked_node_keys = {
                "wh3_dlc25_skill_node_emp_master_engineer_unique_2_1",
            }
        },
        {
            node_key = "wh3_dlc25_skill_node_emp_master_engineer_unique_1_1",
            skill_key = "wh3_dlc25_skill_emp_master_engineer_unique_2_1",
            category_key = "character",
            indent = 2,
            tier = 1,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc25_skill_node_emp_master_engineer_unique_1_3",
            skill_key = "wh3_dlc25_skill_emp_master_engineer_unique_2_6",
            category_key = "character",
            indent = 2,
            tier = 2,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc25_skill_node_emp_master_engineer_unique_1_4",
            skill_key = "wh3_dlc25_skill_emp_master_engineer_unique_2_4",
            category_key = "character",
            indent = 2,
            tier = 3,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc25_skill_node_emp_master_engineer_unique_1_5",
            skill_key = "wh3_dlc25_skill_emp_master_engineer_unique_3_5",
            category_key = "character",
            indent = 2,
            tier = 4,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc25_skill_node_emp_master_engineer_self_0",
            skill_key = "wh2_dlc11_skill_all_lord_self_survivalist",
            category_key = "character",
            indent = 3,
            tier = 0,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc25_skill_node_emp_master_engineer_self_1",
            skill_key = "wh2_dlc11_skill_all_lord_self_self_indomitable",
            category_key = "character",
            indent = 3,
            tier = 1,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc25_skill_node_emp_master_engineer_self_2",
            skill_key = "wh3_dlc25_skill_emp_master_engineer_self_requisition",
            category_key = "character",
            indent = 3,
            tier = 2,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc25_skill_node_emp_master_engineer_self_3",
            skill_key = "wh2_dlc11_skill_all_lord_self_fleet-footed",
            category_key = "character",
            indent = 3,
            tier = 3,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc25_skill_node_emp_master_engineer_self_4",
            skill_key = "wh3_dlc23_skill_chd_lord_self_piercing_shots",
            category_key = "character",
            indent = 3,
            tier = 4,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc25_skill_node_emp_master_engineer_self_5",
            skill_key = "wh_main_skill_dwf_engineer_self_extra_powder",
            category_key = "character",
            indent = 3,
            tier = 5,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc25_skill_node_emp_master_engineer_self_6",
            skill_key = "wh_main_skill_all_all_self_hard_to_hit",
            category_key = "character",
            indent = 3,
            tier = 6,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc25_skill_node_emp_master_engineer_self_7",
            skill_key = "wh2_dlc11_skill_cst_ranged_4",
            category_key = "character",
            indent = 3,
            tier = 7,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc25_skill_node_emp_master_engineer_self_8",
            skill_key = "wh3_dlc23_skill_chd_lord_self_always_ready",
            category_key = "character",
            indent = 3,
            tier = 8,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc25_skill_node_emp_master_engineer_self_9",
            skill_key = "wh2_dlc11_skill_all_lord_self_scarred_veteran",
            category_key = "character",
            indent = 3,
            tier = 9,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc25_skill_node_emp_master_engineer_self_10",
            skill_key = "wh_main_skill_all_all_self_deadly_onslaught",
            category_key = "character",
            indent = 3,
            tier = 10,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
                "wh_dlc05_skill_node_wef_glade_lord_fem_self_ranged_06",
                "wh_dlc05_skill_node_wef_glade_lord_self_ranged_06",
            }
        },
        {
            node_key = "wh3_dlc25_skill_node_emp_master_engineer_army_1",
            skill_key = "wh_main_skill_all_lord_battle_inspiring_presence",
            category_key = "battle",
            indent = 4,
            tier = 0,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc25_skill_node_emp_master_engineer_army_2_1",
            skill_key = "wh2_dlc11_skill_emp_army_buff_emperors_finest",
            category_key = "battle",
            indent = 4,
            tier = 1,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc25_skill_node_emp_master_engineer_army_2_2",
            skill_key = "wh2_dlc11_skill_emp_army_buff_speed_of_horse",
            category_key = "battle",
            indent = 4,
            tier = 2,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc25_skill_node_emp_master_engineer_army_2_3",
            skill_key = "wh2_dlc11_skill_emp_army_buff_pistolkorps",
            category_key = "battle",
            indent = 4,
            tier = 3,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc25_skill_node_emp_master_engineer_army_2_4",
            skill_key = "wh2_dlc11_skill_emp_army_buff_honest_steel",
            category_key = "battle",
            indent = 4,
            tier = 4,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc25_skill_node_emp_master_engineer_army_2_5",
            skill_key = "wh2_dlc11_skill_emp_army_buff_mighty_forge",
            category_key = "battle",
            indent = 4,
            tier = 5,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc25_skill_node_emp_master_engineer_army_2_6",
            skill_key = "wh2_dlc11_skill_emp_army_buff_imperial_gunnery",
            category_key = "battle",
            indent = 4,
            tier = 6,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc25_skill_node_emp_master_engineer_army_3",
            skill_key = "wh_main_skill_all_lord_battle_rally",
            category_key = "battle",
            indent = 4,
            tier = 7,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc25_skill_node_emp_master_engineer_army_4_1",
            skill_key = "wh2_dlc11_skill_emp_army_buff_strength_of_hardship",
            category_key = "battle",
            indent = 4,
            tier = 8,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc25_skill_node_emp_master_engineer_army_4_2",
            skill_key = "wh2_dlc11_skill_emp_army_buff_sharpshooter",
            category_key = "battle",
            indent = 4,
            tier = 9,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc25_skill_node_emp_master_engineer_army_4_3",
            skill_key = "wh2_dlc11_skill_emp_army_buff_taste_for_battle",
            category_key = "battle",
            indent = 4,
            tier = 10,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc25_skill_node_emp_master_engineer_army_4_4",
            skill_key = "wh2_dlc11_skill_emp_army_buff_artillery_master",
            category_key = "battle",
            indent = 4,
            tier = 11,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc25_skill_node_emp_master_engineer_army_5",
            skill_key = "wh_main_skill_all_lord_battle_stand_your_ground",
            category_key = "battle",
            indent = 4,
            tier = 12,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
    },
    wh_dlc04_emp_arch_lector = {
        {
            node_key = "wh_dlc04_skill_node_emp_arch_lector_unique_11",
            skill_key = "wh_dlc04_skill_emp_lord_unique_arch_lector_barded_warhorse",
            category_key = "character",
            indent = 0,
            tier = 1,
            max_level = 1,
            is_mount_skill = true,
            unlock_ranks_by_level = { 3 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc04_skill_node_emp_arch_lector_unique_06",
            skill_key = "wh_main_skill_all_lord_battle_brass-lunged",
            category_key = "character",
            indent = 0,
            tier = 2,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 3 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc04_skill_node_emp_arch_lector_unique_07",
            skill_key = "wh_main_skill_emp_lord_battle_hold_the_line",
            category_key = "character",
            indent = 0,
            tier = 3,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 5 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc04_skill_node_emp_arch_lector_unique_08",
            skill_key = "wh_main_skill_emp_dignitary_unique_warrior_priest_righteous_fury",
            category_key = "character",
            indent = 0,
            tier = 4,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 17 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc25_skill_node_emp_arch_lector_unique_12",
            skill_key = "wh3_dlc25_skill_emp_all_unique_mark_of_hysh",
            category_key = "character",
            indent = 0,
            tier = 5,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 7 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc04_skill_node_emp_arch_lector_unique_05",
            skill_key = "wh_main_skill_emp_all_unique_sigmars_ward",
            category_key = "character",
            indent = 0,
            tier = 6,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 7 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc04_skill_node_emp_arch_lector_unique_02",
            skill_key = "wh_main_skill_emp_dignitary_unique_volkmar_hammer_of_sigmar",
            category_key = "character",
            indent = 1,
            tier = 0,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 4 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc04_skill_node_emp_arch_lector_unique_03",
            skill_key = "wh_main_skill_emp_dignitary_unique_volkmar_priest_shield_of_faith",
            category_key = "character",
            indent = 1,
            tier = 1,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 10 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc04_skill_node_emp_arch_lector_unique_04",
            skill_key = "wh_main_skill_emp_dignitary_unique_volkmar_soulfire",
            category_key = "character",
            indent = 1,
            tier = 2,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 14 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc04_skill_node_emp_arch_lector_self_01",
            skill_key = "wh_main_skill_all_all_self_hard_to_hit_starter",
            category_key = "character",
            indent = 2,
            tier = 0,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc04_skill_node_emp_arch_lector_self_02",
            skill_key = "wh2_dlc11_skill_all_lord_self_devastating_charge",
            category_key = "character",
            indent = 2,
            tier = 1,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc04_skill_node_emp_arch_lector_self_03",
            skill_key = "wh2_dlc11_skill_all_lord_self_full_plate_armour",
            category_key = "character",
            indent = 2,
            tier = 2,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc04_skill_node_emp_arch_lector_self_04",
            skill_key = "wh2_dlc11_skill_all_lord_self_scarred_veteran",
            category_key = "character",
            indent = 2,
            tier = 3,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc04_skill_node_emp_arch_lector_self_05",
            skill_key = "wh2_dlc11_skill_all_lord_self_deadly_blade",
            category_key = "character",
            indent = 2,
            tier = 4,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc04_skill_node_emp_arch_lector_self_06",
            skill_key = "wh_main_skill_emp_dignitary_self_faiths_bastion",
            category_key = "character",
            indent = 2,
            tier = 5,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc04_skill_node_emp_arch_lector_self_07",
            skill_key = "wh2_dlc11_skill_all_lord_self_wound-maker",
            category_key = "character",
            indent = 2,
            tier = 6,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc04_skill_node_emp_arch_lector_self_08",
            skill_key = "wh2_dlc11_skill_all_lord_self_blade_master",
            category_key = "character",
            indent = 2,
            tier = 7,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc04_skill_node_emp_arch_lector_self_09",
            skill_key = "wh2_dlc11_skill_all_lord_self_self_indomitable",
            category_key = "character",
            indent = 2,
            tier = 8,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc04_skill_node_emp_arch_lector_self_10",
            skill_key = "wh2_dlc11_skill_all_lord_self_blade_shield",
            category_key = "character",
            indent = 2,
            tier = 9,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc04_skill_node_emp_arch_lector_self_11",
            skill_key = "wh_main_skill_emp_dignitary_self_benediction",
            category_key = "character",
            indent = 2,
            tier = 10,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc04_skill_node_emp_arch_lector_battle_01",
            skill_key = "wh_main_skill_all_lord_battle_inspiring_presence",
            category_key = "battle",
            indent = 4,
            tier = 0,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc04_skill_node_emp_arch_lector_battle_02",
            skill_key = "wh2_dlc11_skill_emp_army_buff_emperors_finest",
            category_key = "battle",
            indent = 4,
            tier = 1,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc04_skill_node_emp_arch_lector_battle_03",
            skill_key = "wh2_dlc11_skill_emp_army_buff_speed_of_horse",
            category_key = "battle",
            indent = 4,
            tier = 2,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc04_skill_node_emp_arch_lector_battle_04",
            skill_key = "wh2_dlc11_skill_emp_army_buff_pistolkorps",
            category_key = "battle",
            indent = 4,
            tier = 3,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc04_skill_node_emp_arch_lector_battle_05",
            skill_key = "wh2_dlc11_skill_emp_army_buff_honest_steel",
            category_key = "battle",
            indent = 4,
            tier = 4,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc04_skill_node_emp_arch_lector_battle_06",
            skill_key = "wh2_dlc11_skill_emp_army_buff_mighty_forge",
            category_key = "battle",
            indent = 4,
            tier = 5,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc04_skill_node_emp_arch_lector_battle_07",
            skill_key = "wh2_dlc11_skill_emp_army_buff_imperial_gunnery",
            category_key = "battle",
            indent = 4,
            tier = 6,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc04_skill_node_emp_arch_lector_battle_08",
            skill_key = "wh_main_skill_all_lord_battle_rally",
            category_key = "battle",
            indent = 4,
            tier = 7,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc04_skill_node_emp_arch_lector_battle_09",
            skill_key = "wh2_dlc11_skill_emp_army_buff_strength_of_hardship",
            category_key = "battle",
            indent = 4,
            tier = 8,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc04_skill_node_emp_arch_lector_battle_10",
            skill_key = "wh2_dlc11_skill_emp_army_buff_sharpshooter",
            category_key = "battle",
            indent = 4,
            tier = 9,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc04_skill_node_emp_arch_lector_battle_11",
            skill_key = "wh2_dlc11_skill_emp_army_buff_taste_for_battle",
            category_key = "battle",
            indent = 4,
            tier = 10,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc04_skill_node_emp_arch_lector_battle_12",
            skill_key = "wh2_dlc11_skill_emp_army_buff_artillery_master",
            category_key = "battle",
            indent = 4,
            tier = 11,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_dlc04_skill_node_emp_arch_lector_battle_13",
            skill_key = "wh_main_skill_all_lord_battle_stand_your_ground",
            category_key = "battle",
            indent = 4,
            tier = 12,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
    },
    wh_main_emp_lord = {
        {
            node_key = "wh_main_skill_node_emp_lord_unique_07",
            skill_key = "wh_main_skill_emp_lord_unique_general_barded_warhorse",
            category_key = "character",
            indent = 0,
            tier = 1,
            max_level = 1,
            is_mount_skill = true,
            unlock_ranks_by_level = { 3 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_main_skill_node_emp_lord_unique_02",
            skill_key = "wh_main_skill_emp_lord_unique_general_imperial_pegasus",
            category_key = "character",
            indent = 0,
            tier = 2,
            max_level = 1,
            is_mount_skill = true,
            unlock_ranks_by_level = { 11 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_main_skill_node_emp_lord_unique_03",
            skill_key = "wh_main_skill_emp_lord_unique_general_imperial_griffon",
            category_key = "character",
            indent = 0,
            tier = 3,
            max_level = 1,
            is_mount_skill = true,
            unlock_ranks_by_level = { 15 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_main_skill_node_emp_lord_unique_05",
            skill_key = "wh_main_skill_all_lord_battle_brass-lunged",
            category_key = "character",
            indent = 0,
            tier = 4,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 3 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_main_skill_node_emp_lord_unique_06",
            skill_key = "wh_main_skill_emp_lord_battle_hold_the_line",
            category_key = "character",
            indent = 0,
            tier = 5,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 5 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh3_dlc25_skill_node_emp_general_mark_of_hysh",
            skill_key = "wh3_dlc25_skill_emp_all_unique_mark_of_hysh",
            category_key = "character",
            indent = 0,
            tier = 6,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 7 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_main_skill_node_emp_lord_unique_04",
            skill_key = "wh_main_skill_emp_all_unique_sigmars_ward",
            category_key = "character",
            indent = 0,
            tier = 7,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 7 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_main_skill_node_emp_lord_special_01",
            skill_key = "wh3_dlc25_skill_emp_lord_general_special_1",
            category_key = "character",
            indent = 1,
            tier = 0,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 11 },
            locked_node_keys = {
                "wh_main_skill_node_emp_lord_special_05",
                "wh_main_skill_node_emp_lord_special_06",
                "wh_main_skill_node_emp_lord_special_07",
                "wh_main_skill_node_emp_lord_special_08",
            }
        },
        {
            node_key = "wh_main_skill_node_emp_lord_special_02",
            skill_key = "wh3_dlc25_skill_emp_lord_general_special_2",
            category_key = "character",
            indent = 1,
            tier = 1,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_main_skill_node_emp_lord_special_03",
            skill_key = "wh3_dlc25_skill_emp_lord_general_special_3",
            category_key = "character",
            indent = 1,
            tier = 2,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_main_skill_node_emp_lord_special_04",
            skill_key = "wh3_dlc25_skill_emp_lord_general_special_4",
            category_key = "character",
            indent = 1,
            tier = 3,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_main_skill_node_emp_lord_special_05",
            skill_key = "wh3_dlc25_skill_emp_lord_general_special_5",
            category_key = "character",
            indent = 2,
            tier = 0,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 11 },
            locked_node_keys = {
                "wh_main_skill_node_emp_lord_special_01",
                "wh_main_skill_node_emp_lord_special_02",
                "wh_main_skill_node_emp_lord_special_03",
                "wh_main_skill_node_emp_lord_special_04",
            }
        },
        {
            node_key = "wh_main_skill_node_emp_lord_special_06",
            skill_key = "wh3_dlc25_skill_emp_lord_general_special_6",
            category_key = "character",
            indent = 2,
            tier = 1,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_main_skill_node_emp_lord_special_07",
            skill_key = "wh3_dlc25_skill_emp_lord_general_special_7",
            category_key = "character",
            indent = 2,
            tier = 2,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_main_skill_node_emp_lord_special_08",
            skill_key = "wh3_dlc25_skill_emp_lord_general_special_8",
            category_key = "character",
            indent = 2,
            tier = 3,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_main_skill_node_emp_lord_self_01",
            skill_key = "wh_main_skill_all_all_self_hard_to_hit_starter",
            category_key = "character",
            indent = 3,
            tier = 0,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_main_skill_node_emp_lord_self_02",
            skill_key = "wh2_dlc11_skill_all_lord_self_devastating_charge",
            category_key = "character",
            indent = 3,
            tier = 1,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_main_skill_node_emp_lord_self_03",
            skill_key = "wh2_dlc11_skill_all_lord_self_full_plate_armour",
            category_key = "character",
            indent = 3,
            tier = 2,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_main_skill_node_emp_lord_self_04",
            skill_key = "wh2_dlc11_skill_all_lord_self_scarred_veteran",
            category_key = "character",
            indent = 3,
            tier = 3,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_main_skill_node_emp_lord_self_05",
            skill_key = "wh2_dlc11_skill_all_lord_self_deadly_blade",
            category_key = "character",
            indent = 3,
            tier = 4,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_main_skill_node_emp_lord_self_06",
            skill_key = "wh_main_skill_all_all_self_foe-seeker",
            category_key = "character",
            indent = 3,
            tier = 5,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_main_skill_node_emp_lord_self_07",
            skill_key = "wh2_dlc11_skill_all_lord_self_wound-maker",
            category_key = "character",
            indent = 3,
            tier = 6,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_main_skill_node_emp_lord_self_08",
            skill_key = "wh2_dlc11_skill_all_lord_self_blade_master",
            category_key = "character",
            indent = 3,
            tier = 7,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_main_skill_node_emp_lord_self_09",
            skill_key = "wh2_dlc11_skill_all_lord_self_self_indomitable",
            category_key = "character",
            indent = 3,
            tier = 8,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_main_skill_node_emp_lord_self_10",
            skill_key = "wh2_dlc11_skill_all_lord_self_blade_shield",
            category_key = "character",
            indent = 3,
            tier = 9,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_main_skill_node_emp_lord_self_11",
            skill_key = "wh_main_skill_all_all_self_deadly_onslaught",
            category_key = "character",
            indent = 3,
            tier = 10,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
                "wh_dlc05_skill_node_wef_glade_lord_fem_self_ranged_06",
                "wh_dlc05_skill_node_wef_glade_lord_self_ranged_06",
            }
        },
        {
            node_key = "wh_main_skill_node_emp_lord_battle_01",
            skill_key = "wh_main_skill_all_lord_battle_inspiring_presence",
            category_key = "battle",
            indent = 4,
            tier = 0,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_main_skill_node_emp_lord_battle_02",
            skill_key = "wh2_dlc11_skill_emp_army_buff_emperors_finest",
            category_key = "battle",
            indent = 4,
            tier = 1,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_main_skill_node_emp_lord_battle_03",
            skill_key = "wh2_dlc11_skill_emp_army_buff_speed_of_horse",
            category_key = "battle",
            indent = 4,
            tier = 2,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_main_skill_node_emp_lord_battle_04",
            skill_key = "wh2_dlc11_skill_emp_army_buff_pistolkorps",
            category_key = "battle",
            indent = 4,
            tier = 3,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_main_skill_node_emp_lord_battle_05",
            skill_key = "wh2_dlc11_skill_emp_army_buff_honest_steel",
            category_key = "battle",
            indent = 4,
            tier = 4,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_main_skill_node_emp_lord_battle_06",
            skill_key = "wh2_dlc11_skill_emp_army_buff_mighty_forge",
            category_key = "battle",
            indent = 4,
            tier = 5,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_main_skill_node_emp_lord_battle_07",
            skill_key = "wh2_dlc11_skill_emp_army_buff_imperial_gunnery",
            category_key = "battle",
            indent = 4,
            tier = 6,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_main_skill_node_emp_lord_battle_08",
            skill_key = "wh_main_skill_all_lord_battle_rally",
            category_key = "battle",
            indent = 4,
            tier = 7,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_main_skill_node_emp_lord_battle_09",
            skill_key = "wh2_dlc11_skill_emp_army_buff_strength_of_hardship",
            category_key = "battle",
            indent = 4,
            tier = 8,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_main_skill_node_emp_lord_battle_10",
            skill_key = "wh2_dlc11_skill_emp_army_buff_sharpshooter",
            category_key = "battle",
            indent = 4,
            tier = 9,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_main_skill_node_emp_lord_battle_11",
            skill_key = "wh2_dlc11_skill_emp_army_buff_taste_for_battle",
            category_key = "battle",
            indent = 4,
            tier = 10,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_main_skill_node_emp_lord_battle_12",
            skill_key = "wh2_dlc11_skill_emp_army_buff_artillery_master",
            category_key = "battle",
            indent = 4,
            tier = 11,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_main_skill_node_emp_lord_battle_13",
            skill_key = "wh_main_skill_all_lord_battle_stand_your_ground",
            category_key = "battle",
            indent = 4,
            tier = 12,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
    },
    wh_main_teb_lord = {
        {
            node_key = "wh_main_skill_node_teb_lord_unique_01",
            skill_key = "wh_main_skill_teb_lord_unique_general_warhorse",
            category_key = "character",
            indent = 0,
            tier = 0,
            max_level = 1,
            is_mount_skill = true,
            unlock_ranks_by_level = { 1 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_main_skill_node_teb_lord_unique_02",
            skill_key = "wh_main_skill_emp_all_unique_sigmars_ward",
            category_key = "character",
            indent = 0,
            tier = 1,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 7 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_main_skill_node_teb_lord_self_01",
            skill_key = "wh_main_skill_all_all_self_hard_to_hit_starter",
            category_key = "character",
            indent = 1,
            tier = 0,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_main_skill_node_teb_lord_self_02",
            skill_key = "wh_main_skill_all_all_self_devastating_charge",
            category_key = "character",
            indent = 1,
            tier = 1,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_main_skill_node_teb_lord_self_03",
            skill_key = "wh_main_skill_all_lord_self_full_plate_armour",
            category_key = "character",
            indent = 1,
            tier = 2,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_main_skill_node_teb_lord_self_04",
            skill_key = "wh_main_skill_all_all_self_scarred_veteran",
            category_key = "character",
            indent = 1,
            tier = 3,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_main_skill_node_teb_lord_self_05",
            skill_key = "wh_main_skill_all_all_self_deadly_blade",
            category_key = "character",
            indent = 1,
            tier = 4,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_main_skill_node_teb_lord_self_06",
            skill_key = "wh_main_skill_all_all_self_foe-seeker",
            category_key = "character",
            indent = 1,
            tier = 5,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_main_skill_node_teb_lord_self_07",
            skill_key = "wh_main_skill_all_all_self_wound-maker",
            category_key = "character",
            indent = 1,
            tier = 6,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_main_skill_node_teb_lord_self_08",
            skill_key = "wh_main_skill_all_all_self_blade_master",
            category_key = "character",
            indent = 1,
            tier = 7,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_main_skill_node_teb_lord_self_09",
            skill_key = "wh_main_skill_all_all_self_indomitable",
            category_key = "character",
            indent = 1,
            tier = 8,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_main_skill_node_teb_lord_self_10",
            skill_key = "wh_main_skill_all_all_self_blade_shield",
            category_key = "character",
            indent = 1,
            tier = 9,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_main_skill_node_teb_lord_self_11",
            skill_key = "wh_main_skill_all_all_self_deadly_onslaught",
            category_key = "character",
            indent = 1,
            tier = 10,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
                "wh_dlc05_skill_node_wef_glade_lord_fem_self_ranged_06",
                "wh_dlc05_skill_node_wef_glade_lord_self_ranged_06",
            }
        },
        {
            node_key = "wh_main_skill_node_teb_lord_battle_01",
            skill_key = "wh_main_skill_all_lord_battle_inspiring_presence",
            category_key = "battle",
            indent = 4,
            tier = 0,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_main_skill_node_teb_lord_battle_02",
            skill_key = "wh_main_skill_emp_lord_battle_hold_the_line",
            category_key = "battle",
            indent = 4,
            tier = 1,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 5 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_main_skill_node_teb_lord_battle_03",
            skill_key = "wh_main_skill_emp_lord_battle_honest_steel",
            category_key = "battle",
            indent = 4,
            tier = 2,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_main_skill_node_teb_lord_battle_04",
            skill_key = "wh_main_skill_emp_lord_battle_pistolkorps",
            category_key = "battle",
            indent = 4,
            tier = 3,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_main_skill_node_teb_lord_battle_05",
            skill_key = "wh_main_skill_emp_lord_battle_speed_of_horse",
            category_key = "battle",
            indent = 4,
            tier = 4,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_main_skill_node_teb_lord_battle_06",
            skill_key = "wh_main_skill_all_lord_battle_rally",
            category_key = "battle",
            indent = 4,
            tier = 5,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_main_skill_node_teb_lord_battle_07",
            skill_key = "wh_main_skill_all_lord_battle_brass-lunged",
            category_key = "battle",
            indent = 4,
            tier = 6,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 3 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_main_skill_node_teb_lord_battle_08",
            skill_key = "wh_main_skill_emp_lord_battle_emperors_finest",
            category_key = "battle",
            indent = 4,
            tier = 7,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_main_skill_node_teb_lord_battle_09",
            skill_key = "wh_main_skill_emp_lord_battle_imperial_gunnery",
            category_key = "battle",
            indent = 4,
            tier = 8,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_main_skill_node_teb_lord_battle_10",
            skill_key = "wh_main_skill_emp_lord_battle_mighty_forge",
            category_key = "battle",
            indent = 4,
            tier = 9,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
        {
            node_key = "wh_main_skill_node_teb_lord_battle_11",
            skill_key = "wh_main_skill_all_lord_battle_stand_your_ground",
            category_key = "battle",
            indent = 4,
            tier = 10,
            max_level = 1,
            is_mount_skill = false,
            unlock_ranks_by_level = { 0 },
            locked_node_keys = {
            }
        },
    },
}

return data
